// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/promise/all dojo/Deferred dojo/json dojo/i18n!../nls/strings ./util esri/lang esri/request esri/arcgis/utils esri/layers/ArcGISDynamicMapServiceLayer esri/layers/ArcGISImageServiceLayer esri/layers/ArcGISTiledMapServiceLayer esri/layers/DynamicLayerInfo esri/layers/FeatureLayer esri/layers/ImageParameters esri/layers/ImageServiceParameters esri/layers/KMLLayer esri/layers/LayerDrawingOptions esri/layers/MosaicRule esri/layers/RasterFunction esri/layers/RasterXLayer esri/layers/TileInfo esri/layers/VectorTileLayer esri/layers/WFSLayer esri/layers/WMSLayer esri/layers/WMSLayerInfo esri/layers/WMTSLayer esri/layers/WMTSLayerInfo esri/layers/WebTiledLayer esri/dijit/PopupTemplate esri/InfoTemplate esri/renderers/jsonUtils esri/geometry/Extent esri/SpatialReference jimu/utils".split(" "),
function(L,B,q,M,E,r,y,F,G,k,w,N,O,P,H,Q,I,R,S,T,U,V,W,X,Y,Z,aa,ba,ca,ia,ja,da,z,ea,J,C,fa,ha){return L(null,{item:null,itemUrl:null,map:null,serviceUrl:null,constructor:function(a){B.mixin(this,a)},addItem:function(a,b){var c=new r;this.map=b;this.item=a;this.itemUrl=this._checkMixedContent(a.itemUrl);this.serviceUrl=this._checkMixedContent(a.url);if("Feature Service"===a.type)return this._addFeatureService();if("Image Service"===a.type)return this._addImageService();if("KML"===a.type)return this._addKML();
if("Map Service"===a.type)return this._addMapService();if("Vector Tile Service"===a.type)return this._addVectorTileService();if("WFS"===a.type)return this._addWFS();if("WMS"===a.type)return this._addWMS();if("WMTS"===a.type)return this._addWMTS();console.warn("Unsupported item type: ",a.type);c.resolve(null);return c},_addFeatureService:function(){var a=this,b=new r,c=this.serviceUrl,f=this.item,g={},d=null,h=[],l=[];a._readItemJsonData().then(function(e){(g=e||{},g.layers)&&0<g.layers.length&&q.forEach(g.layers,
function(m){"undefined"!==typeof m.id&&null!==m.id&&(null===d&&(d=[]),d.push(m.id))});return a._readRestInfo(c)}).then(function(e){if(!e||"string"!==typeof e.type||"Feature Layer"!==e.type&&"Table"!==e.type){var m=[];e&&e.layers&&0<e.layers.length&&q.forEach(e.layers,function(t){m.push(t)});e&&e.tables&&0<e.tables.length&&q.forEach(e.tables,function(t){m.push(t)});0<m.length?q.forEach(m,function(t){var p=!0;null!==d&&0<d.length&&(p=q.some(d,function(u){return u===t.id}));p&&(p=new I(c+"/"+t.id,{id:a._generateLayerId(),
outFields:["*"]}),h.push(a._waitForLayer(p)))}):console.warn("No layers or tables...")}else e=new I(c,{id:a._generateLayerId(),outFields:["*"]}),h.push(a._waitForLayer(e));return E(h)}).then(function(e){q.forEach(e,function(m){l.push(m)});l.reverse();return l}).then(function(){q.forEach(l,function(e){var m=a._processFeatureLayer(e,f,g);e.arcgisProps={title:m.title};e._titleForLegend=m.title;k.isDefined(e.title)||(e.title=m.title);a._addLayer(e)})}).then(function(){b.resolve(l)}).otherwise(function(e){b.reject(e)});
return b},_addImageService:function(){var a=this,b=new r;a._readItemJsonData().then(function(c){return a._newImageServiceLayer(c||{})}).then(function(c){a._addLayer(c);b.resolve(c)}).otherwise(function(c){b.reject(c)});return b},_addKML:function(){var a=this,b=new r;a._newKMLLayer().then(function(c){c&&(c.title=a.item.title);a._addLayer(c);b.resolve(c)}).otherwise(function(c){b.reject(c)});return b},_addMapService:function(){var a=this,b=new r;a._readItemJsonData().then(function(c){return a._newMapServiceLayer(c||
{})}).then(function(c){a._addLayer(c);b.resolve(c)}).otherwise(function(c){b.reject(c)});return b},_addVectorTileService:function(){var a=this,b=new r;a._newVectorTileLayer().then(function(c){a._addLayer(c);b.resolve(c)}).otherwise(function(c){b.reject(c)});return b},_addWFS:function(){var a=this,b=new r;a._readItemJsonData().then(function(c){return a._newWFSLayer(c||{})}).then(function(c){c&&(c.title=a.item.title);a._addLayer(c);b.resolve(c)}).otherwise(function(c){console.log("Error adding WFS",
c);b.reject(c)});return b},_addWMS:function(){var a=this,b=new r;a._readItemJsonData().then(function(c){return a._newWMSLayer(c||{})}).then(function(c){c&&(c.title=a.item.title);a._addLayer(c);b.resolve(c)}).otherwise(function(c){b.reject(c)});return b},_addWMTS:function(){var a=this,b=new r;a._readItemJsonData().then(function(c){return a._newWMTSLayer(c||{})}).then(function(c){c&&(c.title=a.item.title);a._addLayer(c);b.resolve(c)}).otherwise(function(c){b.reject(c)});return b},_addLayer:function(a){var b=
this.item;a&&(a.xtnItemId=b.id,a.xtnAddData=!0,!a.arcgisProps&&b&&(a.arcgisProps={title:b.title},a._titleForLegend=b.title),k.isDefined(a.title)||(a.title=b.title),a._wabProperties={itemLayerInfo:{itemId:b.id,itemUrl:this.itemUrl,portalUrl:b.portalUrl}},this.map.addLayer(a))},_checkMixedContent:function(a){return G.checkMixedContent(a)},_checkUrl:function(a){return N._checkUrl(a)},_checkVectorTileUrl:function(a,b){var c=new r;if(function(g,d){return-1!==g.indexOf(d,g.length-d.length)}(a,".json"))return b.styleUrl=
a,c.resolve(a),c;var f={url:null,content:{},handleAs:"json",callbackParamName:"callback"};this.itemUrl?(f.url=this.itemUrl+"/resources/styles/root.json",w(f,{}).then(function(){b.styleUrl=f.url;c.resolve(f.url)}).otherwise(function(){f.url=a+"/resources/styles/root.json";w(f,{}).then(function(){b.styleUrl=f.url;c.resolve(f.url)}).otherwise(function(){b.url=a;c.resolve(a)})})):(f.url=a+"/resources/styles/root.json",w(f,{}).then(function(){b.styleUrl=f.url;c.resolve(f.url)}).otherwise(function(){b.url=
a;c.resolve(a)}));return c},_generateLayerId:function(){return this._generateLayerIds(1)[0]},_generateLayerIds:function(a){var b,c=[];for(b=0;b<a;b++)c.push(this._generateRandomId());return c},_generateRandomId:function(){var a=null;a="function"===typeof Date.now?Date.now():(new Date).getTime();var b=(""+Math.random()).replace("0.","r");return(a+""+b).replace(/-/g,"")},_makeFeatureLayerTitle:function(a,b,c){try{if(b&&c&&b===c)return b;if(b&&c){var f=c.indexOf(b);if(0===f){var g=c.substring(f+b.length+
1);if(13<=g.length){var d=/^\d+$/;if(d.test(g))return b}}}}catch(h){}return a.replace("{serviceName}",b).replace("{layerName}",c)},_newImageServiceLayer:function(a){var b=new r,c=this._generateLayerId(),f=this.serviceUrl,g=this.serviceUrl,d={mapLayerId:c,bandIds:null,format:null,compressionQuality:null,opacity:1,visibility:!0};k.isDefined(a.visibility)&&!1===a.visibility&&(d.visibility=!1);k.isDefined(a.opacity)&&(d.opacity=a.opacity);k.isDefined(a.minScale)&&!k.isDefined(d.minScale)&&(d.minScale=
a.minScale);k.isDefined(a.maxScale)&&!k.isDefined(d.maxScale)&&(d.maxScale=a.maxScale);k.isDefined(a.refreshInterval)&&!k.isDefined(d.refreshInterval)&&(d.refreshInterval=a.refreshInterval);!a.popupInfo||d.popupInfo||d.disablePopup||(d.popupInfo=a.popupInfo);a.renderingRule&&!d.renderingRule&&(d.renderingRule=a.renderingRule,a.renderingRule.functionName&&(d.renderingRule.rasterFunction=a.renderingRule.functionName));a.bandIds&&!d.bandIds&&(d.bandIds=a.bandIds);a.mosaicRule&&!d.mosaicRule&&(d.mosaicRule=
a.mosaicRule);a.format&&!d.format&&(d.format=a.format);k.isDefined(a.compressionQuality)&&!k.isDefined(d.compressionQuality)&&(d.compressionQuality=a.compressionQuality);!a.layerDefinition||!a.layerDefinition.definitionExpression||k.isDefined(d.layerDefinition)&&k.isDefined(d.layerDefinition.definitionExpression)||(d.layerDefinition=d.layerDefinition||{},d.layerDefinition.definitionExpression=a.layerDefinition.definitionExpression);a=new S;null!==d.bandIds&&(a.bandIds=d.bandIds);null!==d.format&&
(a.format=d.format,null!==d.compressionQuality&&(a.compressionQuality=d.compressionQuality));if(d.renderingRule&&d.renderingRule.rasterFunction){var h=new W(d.renderingRule);a.renderingRule=h}d.mosaicRule&&(h=new V(d.mosaicRule),a.mosaicRule=h);k.isDefined(d.noData)&&(a.noData=d.noData);k.isDefined(d.noDataInterpretation)&&(a.noDataInterpretation=d.noDataInterpretation);k.isDefined(d.interpolation)&&(a.interpolation=d.interpolation);var l={imageServiceParameters:a,opacity:d.opacity,visible:d.visibility};
k.isDefined(d.mapLayerId)&&(l.id=d.mapLayerId);k.isDefined(d.minScale)&&(l.minScale=d.minScale);k.isDefined(d.maxScale)&&(l.maxScale=d.maxScale);k.isDefined(d.refreshInterval)&&(l.refreshInterval=d.refreshInterval);k.isDefined(d.resourceInfo)&&(l.resourceInfo=d.resourceInfo);var e=this,m,t;e._readRestInfo(f).then(function(p){var u=null;if(p&&p.tileInfo&&p.singleFusedMapCache)return u="Raster"===p.cacheType?new X(f,{id:c}):new H(f,{id:c}),e._waitForLayer(u).then(function(n){t=n});u=new P(e._checkUrl(g),
l);return e._waitForLayer(u).then(function(n){m=n})}).then(function(){if(m){var p=m;d.layerDefinition&&d.layerDefinition.definitionExpression&&p.setDefinitionExpression(d.layerDefinition.definitionExpression,!0);!d.disablePopup&&d.popupInfo&&p.setInfoTemplate(new z(d.popupInfo));b.resolve(p)}else t?b.resolve(t):b.resolve()}).otherwise(function(p){b.reject(p)});return b},_newInfoTemplate:function(a,b){if(a)try{return new z({description:a.description,title:a.title,showAttachments:a.showAttachments,
fieldInfos:a.fieldInfos,mediaInfos:a.mediaInfos})}catch(c){console.error(c)}a=new ea;k.isDefined(b)&&a.setTitle(b);return a},_newKMLLayer:function(){var a={id:this._generateLayerId()};a=new T(this.serviceUrl,a);return this._waitForLayer(a)},_newMapServiceLayer:function(a){var b=this,c=new r,f=this.serviceUrl,g=this._generateLayerId();w({url:f,content:{f:"json"},handleAs:"json",callbackParamName:"callback"},{}).then(function(d){var h=null;h={id:g};if(d.tileInfo)h=new H(f,h);else if(d&&d.supportedImageFormatTypes&&
-1!==d.supportedImageFormatTypes.indexOf("PNG32")&&(h.imageParameters=new R,h.imageParameters.format="png32"),h=new O(f,h),a&&a.layers&&0<a.layers.length){var l=[],e,m=[],t,p=[],u;q.forEach(a.layers,function(n){n.layerDefinition&&n.layerDefinition.definitionExpression&&(l[n.id]=n.layerDefinition.definitionExpression);if(n.layerDefinition&&n.layerDefinition.source){e=null;u=n.layerDefinition.source;if("mapLayer"===u.type){var v=q.filter(d.layers,function(x){return x.id===u.mapLayerId});v.length&&(e=
B.mixin(v[0],n))}else e=B.mixin({},n);e&&(e.source=u,delete e.popupInfo,e=new Q(e),a.visibleLayers&&(v="string"===typeof a.visibleLayers?a.visibleLayers.split(","):a.visibleLayers,-1<q.indexOf(v,n.id)?e.defaultVisibility=!0:e.defaultVisibility=!1),m.push(e))}n.layerDefinition&&n.layerDefinition.source&&n.layerDefinition.drawingInfo&&(t=new U(n.layerDefinition.drawingInfo),p[n.id]=t)});0<l.length&&h.setLayerDefinitions(l);0<m.length&&(h.setDynamicLayerInfos(m,!0),0<p.length&&h.setLayerDrawingOptions(p,
!0))}b._waitForLayer(h).then(function(n){var v=null;q.forEach(n.layerInfos,function(x){var A=null;a&&q.some(a.layers,function(K){if(x.id===K.id)return A=K,!0});var D=null;A&&A.popupInfo&&(D=A.popupInfo);D&&(null===v&&(v={}),v[x.id]={infoTemplate:b._newInfoTemplate(D,x.name)})});null===n.infoTemplates&&(v?n.infoTemplates=v:b._setDynamicLayerInfoTemplates(n));c.resolve(n)},function(n){c.reject(n)})},function(d){c.reject(d)});return c},_getVisibleFeatureLayers:function(a,b){if(!a||!b||0===b.length)return[];
b=","+b+",";var c=[],f,g=",";for(f=0;f<a.length;f++)if(null!==a[f].subLayerIds){if(-1===b.indexOf(","+a[f].id+",")||-1<g.indexOf(","+a[f].id+","))g+=a[f].subLayerIds.toString()+","}else-1<b.indexOf(","+a[f].id+",")&&-1===g.indexOf(","+a[f].id+",")&&c.push(a[f].id);return c},_newPopupInfo:function(a,b){if(a&&a.fields){var c={title:a.name,fieldInfos:[],description:null,showAttachments:!0,mediaInfos:[]};"string"===typeof b&&0<b.length&&(c.title=b);q.forEach(a.fields,function(f){var g=ha.getDefaultPortalFieldInfo(f);
g.visible=!0;g.isEditable=f.editable;c.fieldInfos.push(g)});return c}return null},_newVectorTileLayer:function(){var a=this,b=new r,c={},f=this.serviceUrl,g=this._generateLayerId();"string"===typeof f&&0<f.length?this._checkVectorTileUrl(f,c).then(function(d){"string"===typeof d&&0<d.length?(d=a._checkMixedContent(d),d=new Z(d,{id:g,opacity:1,visible:!0}),a._waitForLayer(d).then(function(h){b.resolve(h)},function(h){b.reject(h)})):b.resolve(null)},function(d){b.reject(d)}):b.resolve(null);return b},
_newWFSLayer:function(a){var b=new r;try{var c=this._generateLayerId();if(a&&a.wfsInfo&&a.layerDefinition)var f={id:c,mode:a.mode,showLabels:!0,title:a.title,url:this._checkMixedContent(a.url),customParameters:a.wfsInfo.customParameters,maxFeatures:a.wfsInfo.maxFeatures,name:a.wfsInfo.name,swapXY:a.wfsInfo.swapXY,version:a.wfsInfo.version,geometryType:a.layerDefinition.geometryType,labelingInfo:a.layerDefinition.drawingInfo.labelingInfo};else{var g=this.serviceUrl;g?G.loadWFSByUrl(b,map,this,g,c,
!1):b.reject(Error("Error adding WFS, no URL"));return b}var d=new aa,h=d.on("error",function(l){h&&h.remove();b.reject(l.error)});d.fromJson(f,function(){try{h&&h.remove();if(a&&a.wfsInfo&&a.layerDefinition){k.isDefined(a.opacity)&&d.setOpacity(a.opacity);k.isDefined(a.visibility)&&d.setVisibility(a.visibility);(a.minScale||a.maxScale)&&d.setScaleRange(a.minScale,a.maxScale);var l=a.layerDefinition.drawingInfo;l&&l.renderer&&(d.renderer=J.fromJson(l.renderer,{geometryType:f.geometryType}));a.popupInfo&&
d.setInfoTemplate(new z(a.popupInfo))}b.resolve(d)}catch(e){console.error("Error adding WFS",e),b.reject(ex)}})}catch(l){console.error("Error adding WFS",l),b.reject(l)}return b},_newWMSLayer:function(a){var b=this,c=this.item,f=!1,g=null,d={id:this._generateLayerId()};if(a){var h=[],l=[];q.forEach(a.layers,function(e){f=!0;l.push(new ca({name:e.name,title:e.title,legendURL:e.legendURL,queryable:e.queryable,showPopup:e.showPopup}));h.push(e.name)},this);a.visibleLayers&&(h=a.visibleLayers);d={customLayerParameters:a.customLayerParameters,
customParameters:a.customParameters,layerInfos:l,version:a.version,maxWidth:a.maxWidth,maxHeight:a.maxHeight,featureInfoFormat:a.featureInfoFormat,getFeatureInfoURL:a.featureInfoUrl,getMapURL:a.mapUrl,spatialReferences:a.spatialReferences,title:a.title,copyright:a.copyright,minScale:a.minScale||0,maxScale:a.maxScale||0,format:a.format};c&&c.extent&&(c=new C(c.extent[0][0],c.extent[0][1],c.extent[1][0],c.extent[1][1],new fa({wkid:4326})),d.extent=c);a.spatialReferences&&0<a.spatialReferences.length&&
(g=a.spatialReferences[0]);d={id:this._generateLayerId(),visibleLayers:h,format:"png",transparent:a.firstLayer?!1:!0,opacity:a.opacity,visible:null!==a.visibility?a.visibility:!0,resourceInfo:d,refreshInterval:a.refreshInterval}}a=new ba(this.serviceUrl,d);a=this._waitForLayer(a);a.then(function(e){f||b._setWMSVisibleLayers(e);g&&e.spatialReference&&(e.spatialReference.wkid=g)});return a},_newWMTSLayer:function(a){if(a){var b=new da(a.templateUrl,{id:this._generateLayerId(),visible:null!==a.visibility?
a.visibility:!0,opacity:a.opacity,copyright:a.copyright,fullExtent:a.fullExtent&&new C(a.fullExtent),initialExtent:a.fullExtent&&new C(a.fullExtent),subDomains:a.subDomains,tileInfo:a.tileInfo?new Y(a.tileInfo):null,refreshInterval:a.refreshInterval,wmtsInfo:a.wmtsInfo});if(k.isDefined(a.minScale)||k.isDefined(a.maxScale))b.loaded?b.setScaleRange(a.minScale,a.maxScale):M.connect(b,"onLoad",function(){b.setScaleRange(a.minScale,a.maxScale)});return this._waitForLayer(b)}var c=new r;c.resolve();return c},
_processFeatureLayer:function(a,b,c){var f=this,g=F.search.featureLayerTitlePattern,d=null;c&&c.layers&&0<c.layers.length?q.some(c.layers,function(h){var l=!1;if(h.id===a.layerId){if(h.popupInfo){var e=h.popupInfo;e=y.parse(y.stringify(e));e=new z(e);a.setInfoTemplate(e);l=!0}k.isDefined(h.showLabels)&&a.setShowLabels(h.showLabels);k.isDefined(h.refreshInterval)&&a.setRefreshInterval(h.refreshInterval);k.isDefined(h.showLegend)&&console.log("");k.isDefined(h.timeAnimation)&&!1===h.timeAnimation&&
console.log("");if(e=h.layerDefinition){e.definitionExpression&&a.setDefinitionExpression(e.definitionExpression);e.displayField&&a.displayField(e.displayField);if(e.drawingInfo){if(e.drawingInfo.renderer){var m=y.parse(y.stringify(e.drawingInfo.renderer));var t=J.fromJson(m);m.type&&"classBreaks"===m.type&&(t.isMaxInclusive=!0);a.setRenderer(t)}k.isDefined(e.drawingInfo.transparency)&&a.setOpacity(1-e.drawingInfo.transparency/100)}k.isDefined(e.minScale)&&a.setMinScale(e.minScale);k.isDefined(e.maxScale)&&
a.setMaxScale(e.maxScale);k.isDefined(e.defaultVisibility)&&!1===e.defaultVisibility&&a.setVisibility(!1)}l||f._setFeatureLayerInfoTemplate(a,h.popupInfo);d={url:a.url,id:a.id,itemId:b.id,title:f._makeFeatureLayerTitle(g,b.title,a.name)};return!0}}):(d={url:a.url,id:a.id,itemId:b.id,title:f._makeFeatureLayerTitle(g,b.title,a.name)},f._setFeatureLayerInfoTemplate(a,null,d.title));return d},_readItemJsonData:function(){return w({url:this.itemUrl+"/data",content:{f:"json"},handleAs:"json"},{})},_readRestInfo:function(a){return w({url:a,
content:{f:"json"},handleAs:"json",callbackParamName:"callback"},{})},_setDynamicLayerInfoTemplates:function(a){var b=this,c=null,f=[],g=function(d){var h=b._readRestInfo(a.url+"/"+d.id);h.then(function(l){try{var e=b._newPopupInfo(l);e&&(c[d.id]={infoTemplate:b._newInfoTemplate(e)})}catch(m){console.warn("Error setting popup."),console.error(m)}});return h};null===a.infoTemplates&&q.forEach(a.layerInfos,function(d){null===c&&(c={});d.subLayerIds||f.push(g(d))});0<f.length&&E(f).then(function(){c&&
(a.infoTemplates=c)}).otherwise(function(d){console.warn("Error reading sublayers.");console.error(d)})},_setFeatureLayerInfoTemplate:function(a,b,c){b||(b=this._newPopupInfo(a,c));b=this._newInfoTemplate(b,c);a.setInfoTemplate(b)},_setWMSVisibleLayers:function(a){var b=[];a&&(q.some(a.layerInfos,function(c){if("string"===typeof c.name&&0<c.name.length)if(10>b.length)b.push(c.name);else return!0}),10>=b.length&&a.setVisibleLayers(b))},_waitForLayer:function(a){var b=new r,c=[];if(a.loaded)return b.resolve(a),
b;if(a.loadError)return b.reject(a.loadError),b;var f=function(){q.forEach(c,function(g){g.remove()})};c.push(a.on("load",function(g){f();b.resolve(g.layer)}));c.push(a.on("error",function(g){f();g=g.error;try{g.message&&-1!==g.message.indexOf("Unable to complete")?(console.warn("layerAccessError",g),b.reject(Error(F.search.layerInaccessible))):b.reject(g)}catch(d){b.reject(g)}}));return b}})});