// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/setting/nls/strings":{transparencyLabel:"Gennemsigtighed",outline:"Kontur",fill:"Fyld (farve anvendes kun, n\u00e5r typografien er indstillet til massiv)",style:"Type",selectOpLayerLabel:"V\u00e6lg et operationelt lag for at opn\u00e5 resultater",selectDefaultMeasurementLabel:"V\u00e6lg en standardm\u00e5leenhed",helpIconTooltip:"Listen med operationelle lag best\u00e5r af lag fra det aktuelle webkort, der er af geometritypen polygon.",lineStyles:{esriSLSDash:"Streg",
esriSLSDashDot:"Streg-prik",esriSLSDashDotDot:"Streg-prik-prik",esriSLSDot:"Prik",esriSLSLongDash:"Lang streg",esriSLSLongDashDot:"Lang streg-prik",esriSLSNull:"Nul",esriSLSShortDash:"Kort streg",esriSLSShortDashDot:"Kort streg-prik",esriSLSShortDashDotDot:"Kort streg-prik-prik",esriSLSShortDot:"Kort prik",esriSLSSolid:"Udfyldt"},fillStyles:{esriSFSBackwardDiagonal:"Bagl\u00e6ns",esriSFSCross:"Kryds",esriSFSDiagonalCross:"Diagonalt",esriSFSForwardDiagonal:"Frem",esriSFSHorizontal:"Vandret",esriSFSNull:"Nul",
esriSFSSolid:"Udfyldt",esriSFSVertical:"Lodret"},threatTypeLabel:"Trusselstype",generalLabel:"Generelt",addThreatTypesLabel:"Tilf\u00f8j trusselstype",actions:"Handlinger",newThreatTypePopupLabel:"Ny trusselstype",units:"Enheder",chooseDefaultThreatLabel:"V\u00e6lg standard-trusselstype",defaultThreatTypePopUpLabel:"Standard-trusselstyper",editThreatLabel:"Rediger trussel",defaultThreatTypeIconTooltip:"Liste over standard-trusselstyper",uniqueThreatTypeMsg:"Indtast unik trusselstype, en trusselstype med dette navn findes allerede.",
requiredMsg:"Dette felt er obligatorisk.",unitMeasureLabel:"Afstand er i {0}",chooseDefaultThreatTypeIconLabel:"V\u00e6lg fra standard",pipeBombLabel:"R\u00f8rbombe",suicideBombLabel:"Selvmordsbombe",briefcaseLabel:"Dokumentmappe",carLabel:"Bil",suvVanLabel:"SUV/VAN",smallDeliveryTruckLabel:"Lille varevogn",containerWaterTruckLabel:"Container-/vandlastbil",semiTrailerLabel:"S\u00e6ttevogn",chemicalThreatLegendLabel:"Kemisk trussel",lpgThreatLegendLabel:"LPG-trussel",smallLPGTank:"Lille LPG-tank",
largeLPGTank:"Stor LPG-tank",commercialResidentialLPGTank:"LPG-tank til handels-/boligomr\u00e5de",smallLPGTruck:"Lille LPG-lastvogn",semiTankerLPG:"Semi-tanker LPG",threatDescriptionColLabel:"Trusselsbeskrivelse",addThreatZoneButtonLabel:"Tilf\u00f8j trusselszone",zoneDescColLabel:"Zonebeskrivelse",distanceLabel:"Afstand (${unitAbbr})",threatTypeHelp:"\x3cp\x3eS\u00f8rg for, at f\u00f8lgende betingelser er opfyldt for en trusselstype:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eTrusselstypen m\u00e5 ikke v\u00e6re tom, og den skal v\u00e6re entydig\x3c/li\x3e\x3cli\x3eTruslen skal have mindst \u00e9n gyldig zone\x3c/li\x3e\x3cli\x3eZonebeskrivelsen skal v\u00e6re entydig for en trussel\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e",
descriptionLabel:"Beskrivelse",newThreatZonePopupLabel:"Ny trusselszone",editThreatZonePopupLabel:"Redig\u00e9r trusselszone",uniqueZoneDescriptionMsg:"Indtast en entydig zonebeskrivelse, der findes allerede en zonebeskrivelse med dette navn.",symbologyColLabel:"Symbologi",zoneDescriptionColLabel:"Zonebeskrivelse",uniqueZoneRequiredMsg:"Zonenavnet skal v\u00e6re entydigt for",interactive:"Interaktiv",fromCoord:"Fast koordinat",existingFeature:"Fra eksisterende objekter",defaultInputLocationLabel:"Standard-inputplacering",
defaultInputLayer:"Standard-inputlag",defaultThreatType:"Standard-trusselstype",selectLabel:"V\u00e6lg",mandatoryLabel:"Obligatorisk evakueringsafstand",safeLabel:"Sikker evakueringsafstand",lpgSafeDistanceLable:"Sikker afstand",fireBallDiameterLable:"Fireball-diameter",_localized:{}}});