// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/setting/nls/strings":{transparencyLabel:"Prozirnost",outline:"Obris",fill:"Ispuni (boja se primjenjuje samo kad je stil postavljen na jednobojno)",style:"Stil",selectOpLayerLabel:"Odabir operativnog sloja za rezultate",selectDefaultMeasurementLabel:"Odabir zadane mjerne jedinice",helpIconTooltip:"Operativni sloj popunjen je slojevima poligonalnog tipa geometrije iz trenuta\u010dne web-karte.",lineStyles:{esriSLSDash:"Linija s crticom",esriSLSDashDot:"Linija s crticom i to\u010dkom",
esriSLSDashDotDot:"Linija s crticom i dvije to\u010dke",esriSLSDot:"To\u010dka",esriSLSLongDash:"Duga crtica",esriSLSLongDashDot:"Duga crtica i to\u010dka",esriSLSNull:"Nema vrijednosti",esriSLSShortDash:"Kratka crtica",esriSLSShortDashDot:"Kratka crtica i to\u010dka",esriSLSShortDashDotDot:"Kratka crtica i dvije to\u010dke",esriSLSShortDot:"Kratka to\u010dka",esriSLSSolid:"Puna linija"},fillStyles:{esriSFSBackwardDiagonal:"Unatrag",esriSFSCross:"Kri\u017e",esriSFSDiagonalCross:"Dijagonalno",esriSFSForwardDiagonal:"Naprijed",
esriSFSHorizontal:"Vodoravni",esriSFSNull:"Nema vrijednosti",esriSFSSolid:"Puna linija",esriSFSVertical:"Uspravno"},threatTypeLabel:"Vrsta prijetnje",generalLabel:"Op\u0107enito",addThreatTypesLabel:"Dodaj vrstu prijetnje",actions:"Radnje",newThreatTypePopupLabel:"Nova vrsta prijetnje",units:"Jedinice",chooseDefaultThreatLabel:"Odaberi zadanu vrstu prijetnje",defaultThreatTypePopUpLabel:"Zadane vrste prijetnje",editThreatLabel:"Uredi prijetnju",defaultThreatTypeIconTooltip:"Popis zadanih vrsta prijetnje",
uniqueThreatTypeMsg:"Unesite jedinstvenu vrstu prijetnje. Vrsta prijetnje s tim nazivom ve\u0107 postoji.",requiredMsg:"Ovo je polje obavezno",unitMeasureLabel:"Udaljenosti su u: {0}",chooseDefaultThreatTypeIconLabel:"Izaberi iz zadanih opcija",pipeBombLabel:"Cijevna bomba",suicideBombLabel:"Bomba za samoubila\u010dki napad",briefcaseLabel:"Aktovka",carLabel:"Automobil",suvVanLabel:"SUV/KAMION",smallDeliveryTruckLabel:"Mali kamion za dostavu",containerWaterTruckLabel:"Kamion za prijevoz kontejnera/vode",
semiTrailerLabel:"Poluprikolica",chemicalThreatLegendLabel:"Kemijska prijetnja",lpgThreatLegendLabel:"LPG prijetnja",smallLPGTank:"Mali LPG spremnik",largeLPGTank:"Veliki LPG spremnik",commercialResidentialLPGTank:"Komercijalni/stambeni LPG spremnik",smallLPGTruck:"Mali LPG kamion",semiTankerLPG:"LPG polucisterna",threatDescriptionColLabel:"Opis prijetnje",addThreatZoneButtonLabel:"Dodaj zonu prijetnje",zoneDescColLabel:"Opis zone",distanceLabel:"Udaljenost (${unitAbbr})",threatTypeHelp:"\x3cp\x3eProvjerite jesu li sljede\u0107i zahtjevi zadovoljeni za vrstu prijetnje:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eVrsta prijetnje ne mo\u017ee biti prazna te mora biti jedinstvena\x3c/li\x3e\x3cli\x3ePrijetnja mora imati najmanje jednu valjanu zonu\x3c/li\x3e\x3cli\x3eOpis zone mora biti jedinstven za prijetnju\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e",
descriptionLabel:"Opis",newThreatZonePopupLabel:"Nova zona prijetnje",editThreatZonePopupLabel:"Uredi zonu prijetnje",uniqueZoneDescriptionMsg:"Unesite jedinstven opis zone, opis zone s ovim nazivom ve\u0107 postoji.",symbologyColLabel:"Simbologija",zoneDescriptionColLabel:"Opis zone",uniqueZoneRequiredMsg:"Naziv zone mora biti jedinstven za",interactive:"Interaktivno",fromCoord:"Fiksna koordinata",existingFeature:"Iz postoje\u0107ih geoobjekata",defaultInputLocationLabel:"Zadana lokacija unosa",
defaultInputLayer:"Zadani sloj unosa",defaultThreatType:"Zadana vrsta prijetnje",selectLabel:"Odaberi",mandatoryLabel:"Obavezna udaljenost za evakuaciju",safeLabel:"Sigurna udaljenost za evakuaciju",lpgSafeDistanceLable:"Sigurna udaljenost",fireBallDiameterLable:"Promjer vatrene kugle",_localized:{}}});