// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/setting/nls/strings":{transparencyLabel:"Trasparenza",outline:"Bordo",fill:"Riempimento (Il colore si applica solo quando lo stile \u00e8 impostato su tinta unita)",style:"Stile",selectOpLayerLabel:"Selezionare un layer operativo per i risultati",selectDefaultMeasurementLabel:"Selezionare un'unit\u00e0 di misura predefinita",helpIconTooltip:"L'elenco dei layer operativi \u00e8 popolato con i layer della mappa Web corrente che sono di tipo a geometria poligonale.",lineStyles:{esriSLSDash:"Trattino",
esriSLSDashDot:"Trattino punto",esriSLSDashDotDot:"Trattino Punto Punto",esriSLSDot:"Punto",esriSLSLongDash:"Trattino lungo",esriSLSLongDashDot:"Trattino lungo punto",esriSLSNull:"Null",esriSLSShortDash:"Trattino corto",esriSLSShortDashDot:"Trattino corto punto",esriSLSShortDashDotDot:"Trattino corto punto punto",esriSLSShortDot:"Punto corto",esriSLSSolid:"Tinta unita"},fillStyles:{esriSFSBackwardDiagonal:"Indietro",esriSFSCross:"Croce",esriSFSDiagonalCross:"Diagonale",esriSFSForwardDiagonal:"Avanti",
esriSFSHorizontal:"Orizzontale",esriSFSNull:"Null",esriSFSSolid:"Tinta unita",esriSFSVertical:"Verticale"},threatTypeLabel:"Tipo di minaccia",generalLabel:"Generale",addThreatTypesLabel:"Aggiungi tipo di minaccia",actions:"Azioni",newThreatTypePopupLabel:"Nuovo tipo di minaccia",units:"Unit\u00e0",chooseDefaultThreatLabel:"Seleziona tipo di minaccia predefinito",defaultThreatTypePopUpLabel:"Tipi di minaccia predefiniti",editThreatLabel:"Modifica minaccia",defaultThreatTypeIconTooltip:"Elenco dei tipi di minaccia predefiniti",
uniqueThreatTypeMsg:"Immettere un tipo di minaccia univoco; esiste gi\u00e0 un tipo di minaccia con questo nome.",requiredMsg:"Campo obbligatorio",unitMeasureLabel:"Le distanze sono in {0}",chooseDefaultThreatTypeIconLabel:"Scegliere da predefiniti",pipeBombLabel:"Tubo bomba",suicideBombLabel:"Bomba suicida",briefcaseLabel:"Valigetta",carLabel:"Auto",suvVanLabel:"SUV/VAN",smallDeliveryTruckLabel:"Furgone per le consegne",containerWaterTruckLabel:"Container/Cisterna",semiTrailerLabel:"Semirimorchio",
chemicalThreatLegendLabel:"Minaccia chimica",lpgThreatLegendLabel:"Minaccia GPL",smallLPGTank:"Serbatoio GPL piccolo",largeLPGTank:"Serbatoio GPL grande",commercialResidentialLPGTank:"Serbatoio GPL residenziale/commerciale",smallLPGTruck:"Camion GPL piccolo",semiTankerLPG:"Semi-autocisterna GPL",threatDescriptionColLabel:"Descrizione minaccia",addThreatZoneButtonLabel:"Aggiungi zona di minaccia",zoneDescColLabel:"Descrizione zona",distanceLabel:"Distanza (${unitAbbr})",threatTypeHelp:"\x3cp\x3eAssicurarsi che le seguenti condizioni siano rispettate per un tipo di minaccia:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eTipo di minaccia non pu\u00f2 essere vuoto e dovrebbe essere unico\x3c/li\x3e\x3cli\x3eLa minaccia dovrebbe almeno possedere una zona valida\x3c/li\x3e\x3cli\x3eLa descrizione della zona dovrebbe essere unica per una minaccia\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e",
descriptionLabel:"Descrizione",newThreatZonePopupLabel:"Nuova zona di minaccia",editThreatZonePopupLabel:"Modifica zona di minaccia",uniqueZoneDescriptionMsg:"Inserisci una descrizione unica della zona, la descrizione della zona con questo nome esiste gi\u00e0.",symbologyColLabel:"Simbologia",zoneDescriptionColLabel:"Descrizione zona",uniqueZoneRequiredMsg:"Il nome della zona dovrebbe essere unico per",interactive:"Interattivo",fromCoord:"Coordinata fissa",existingFeature:"Da feature esistenti",defaultInputLocationLabel:"La posizione input predefinita",
defaultInputLayer:"Layer input predefinito",defaultThreatType:"Tipo di minaccia predefinito",selectLabel:"Seleziona",mandatoryLabel:"Distanza di evacuazione obbligatoria",safeLabel:"Distanza di evacuazione di sicurezza",lpgSafeDistanceLable:"Distanza di sicurezza",fireBallDiameterLable:"Diametro meteorite",_localized:{}}});