// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/setting/nls/strings":{transparencyLabel:"Transparence",outline:"Contour",fill:"Remplissage (La couleur s\u2019applique uniquement lorsque le style est uni)",style:"Style",selectOpLayerLabel:"S\u00e9lectionner une couche op\u00e9rationnelle pour les r\u00e9sultats",selectDefaultMeasurementLabel:"S\u00e9lectionner une unit\u00e9 de mesure par d\u00e9faut.",helpIconTooltip:"La liste des couches op\u00e9rationnelles est renseign\u00e9e \u00e0 l\u2019aide des couches de la carte web actuelle dont le type de g\u00e9om\u00e9trie est Polygone.",
lineStyles:{esriSLSDash:"Tiret",esriSLSDashDot:"Tiret-point",esriSLSDashDotDot:"Tiret-point-point",esriSLSDot:"Point",esriSLSLongDash:"Tiret long",esriSLSLongDashDot:"Tiret-point long",esriSLSNull:"Nulle",esriSLSShortDash:"Tiret court",esriSLSShortDashDot:"Tiret court-point",esriSLSShortDashDotDot:"Tiret court-point-point",esriSLSShortDot:"Point court",esriSLSSolid:"Solide"},fillStyles:{esriSFSBackwardDiagonal:"Arri\u00e8re",esriSFSCross:"Croiser",esriSFSDiagonalCross:"Diagonal",esriSFSForwardDiagonal:"Avant",
esriSFSHorizontal:"Horizontale",esriSFSNull:"Nulle",esriSFSSolid:"Solide",esriSFSVertical:"Verticale"},threatTypeLabel:"Type de risque",generalLabel:"G\u00e9n\u00e9ralit\u00e9s",addThreatTypesLabel:"Ajouter un type de risque",actions:"Actions",newThreatTypePopupLabel:"Nouveau type de risque",units:"Unit\u00e9s",chooseDefaultThreatLabel:"S\u00e9lectionner le type de risque par d\u00e9faut",defaultThreatTypePopUpLabel:"Type de risque par d\u00e9faut",editThreatLabel:"Mettre \u00e0 jour le risque",defaultThreatTypeIconTooltip:"Liste des types de risque par d\u00e9faut",
uniqueThreatTypeMsg:"Saisissez un type de risque unique. Un type de risque portant ce nom existe d\u00e9j\u00e0.",requiredMsg:"Ce champ est requis",unitMeasureLabel:"Les distances sont en {0}",chooseDefaultThreatTypeIconLabel:"Choisir parmi les valeurs par d\u00e9faut",pipeBombLabel:"Bombe artisanale",suicideBombLabel:"Attentat-suicide",briefcaseLabel:"Colis pi\u00e9g\u00e9",carLabel:"Voiture",suvVanLabel:"SUV/VAN",smallDeliveryTruckLabel:"Camionnette de livraison",containerWaterTruckLabel:"Camion-citerne/remorque",
semiTrailerLabel:"Semi-remorque",chemicalThreatLegendLabel:"Risque chimique",lpgThreatLegendLabel:"Risque li\u00e9 au GPL",smallLPGTank:"Petit r\u00e9servoir GPL",largeLPGTank:"Grand r\u00e9servoir GPL",commercialResidentialLPGTank:"R\u00e9servoir GPL commercial/r\u00e9sidentiel",smallLPGTruck:"Petit camion GPL",semiTankerLPG:"Camion-citerne GPL",threatDescriptionColLabel:"Description du risque",addThreatZoneButtonLabel:"Ajouter une zone de risque",zoneDescColLabel:"Description de la zone",distanceLabel:"Distance (${unitAbbr})",
threatTypeHelp:"\x3cp\x3eAssurez-vous que les conditions suivantes sont respect\u00e9es pour un type de risque\u00a0:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eLe type de risque doit \u00eatre renseign\u00e9 et unique\x3c/li\x3e\x3cli\x3eLe risque doit avoir au moins une zone valide\x3c/li\x3e\x3cli\x3eLa description de la zone doit correspondre \u00e0 un seul risque\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e",descriptionLabel:"Description",newThreatZonePopupLabel:"Nouvelle zone de risque",editThreatZonePopupLabel:"Mettre \u00e0 jour la zone de risque",
uniqueZoneDescriptionMsg:"Saisissez une description unique pour la zone. Une description de zone portant ce nom existe d\u00e9j\u00e0.",symbologyColLabel:"Symbologie",zoneDescriptionColLabel:"Description de la zone",uniqueZoneRequiredMsg:"Le nom de la zone doit \u00eatre unique pour",interactive:"Interactive",fromCoord:"Coordonn\u00e9e fixe",existingFeature:"\u00c0 partir d\u2019entit\u00e9s existantes",defaultInputLocationLabel:"Localisation en entr\u00e9e par d\u00e9faut",defaultInputLayer:"Couche en entr\u00e9e par d\u00e9faut",
defaultThreatType:"Type de risque par d\u00e9faut",selectLabel:"S\u00e9lectionner",mandatoryLabel:"Distance d\u2019\u00e9vacuation obligatoire",safeLabel:"Distance d\u2019\u00e9vacuation de s\u00e9curit\u00e9",lpgSafeDistanceLable:"Distance de s\u00e9curit\u00e9",fireBallDiameterLable:"Diam\u00e8tre de boule de feu",_localized:{}}});