// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/setting/nls/strings":{transparencyLabel:"Transparens",outline:"Kontur",fill:"Fyllningsf\u00e4rg (F\u00e4rgen till\u00e4mpas enbart n\u00e4r stilen anges till solid)",style:"Format",selectOpLayerLabel:"V\u00e4lj ett funktionslager f\u00f6r resultat",selectDefaultMeasurementLabel:"Ange en standardm\u00e5ttenhet",helpIconTooltip:"Listan med funktionslager inneh\u00e5ller lager fr\u00e5n den aktuella webbkartan som \u00e4r av typen polygongeometri.",lineStyles:{esriSLSDash:"Streck",
esriSLSDashDot:"Streck punkt",esriSLSDashDotDot:"Streck punkt punkt",esriSLSDot:"Punkt",esriSLSLongDash:"L\u00e5ngt streck",esriSLSLongDashDot:"L\u00e5ng streck-punkt",esriSLSNull:"Null",esriSLSShortDash:"Kort streck",esriSLSShortDashDot:"Kort streck-punkt",esriSLSShortDashDotDot:"Kort streck-punkt-punkt",esriSLSShortDot:"Kort punkt",esriSLSSolid:"Solid"},fillStyles:{esriSFSBackwardDiagonal:"Bak\u00e5t",esriSFSCross:"Kors",esriSFSDiagonalCross:"Diagonal",esriSFSForwardDiagonal:"Fram\u00e5t",esriSFSHorizontal:"Horisontell",
esriSFSNull:"Null",esriSFSSolid:"Solid",esriSFSVertical:"Vertikal"},threatTypeLabel:"Typ av hot",generalLabel:"Allm\u00e4nt",addThreatTypesLabel:"L\u00e4gg till typ av hot",actions:"\u00c5tg\u00e4rder",newThreatTypePopupLabel:"Ny typ av hot",units:"Enheter",chooseDefaultThreatLabel:"V\u00e4lj standardtyp f\u00f6r hot",defaultThreatTypePopUpLabel:"Standardtyper f\u00f6r hot",editThreatLabel:"Redigera hot",defaultThreatTypeIconTooltip:"Lista med standardtyper f\u00f6r hot",uniqueThreatTypeMsg:"Ange en unik typ av hot, det finns redan en typ av hot med det h\u00e4r namnet.",
requiredMsg:"Det h\u00e4r f\u00e4ltet \u00e4r obligatoriskt.",unitMeasureLabel:"Avst\u00e5nd anges i {0}",chooseDefaultThreatTypeIconLabel:"V\u00e4lj fr\u00e5n standard",pipeBombLabel:"R\u00f6rbomb",suicideBombLabel:"Sj\u00e4lvmordsbomb",briefcaseLabel:"Portf\u00f6lj",carLabel:"Bil",suvVanLabel:"SUV/sk\u00e5pbil",smallDeliveryTruckLabel:"Liten fraktlastbil",containerWaterTruckLabel:"Containerlastbil/vattenlastbil",semiTrailerLabel:"P\u00e5h\u00e4ngsvagn",chemicalThreatLegendLabel:"Kemiskt hot",lpgThreatLegendLabel:"Gasolhot",
smallLPGTank:"Liten gasoltank",largeLPGTank:"Stor gasoltank",commercialResidentialLPGTank:"Gasoltank f\u00f6r kommersiellt bruk eller hemmabruk",smallLPGTruck:"Liten lastbil med gasol",semiTankerLPG:"P\u00e5h\u00e4ngsvagn med gasol",threatDescriptionColLabel:"Hotbeskrivning",addThreatZoneButtonLabel:"L\u00e4gg till hotzon",zoneDescColLabel:"Zonbeskrivning",distanceLabel:"Avst\u00e5nd (${unitAbbr})",threatTypeHelp:"\x3cp\x3eKontrollera att f\u00f6ljande villkor \u00e4r uppfyllda f\u00f6r en typ av hot:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eTyp av hot kan inte vara tomt och det ska vara unikt\x3c/li\x3e\x3cli\x3eHot ska ha minst en giltig zon\x3c/li\x3e\x3cli\x3eZonbeskrivning ska vara unik f\u00f6r ett hot\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e",
descriptionLabel:"Beskrivning",newThreatZonePopupLabel:"Ny hotzon",editThreatZonePopupLabel:"Redigera hotzon",uniqueZoneDescriptionMsg:"Ange en unik hotbeskrivning, det finns redan en hotbeskrivning med det h\u00e4r namnet.",symbologyColLabel:"Symbologi",zoneDescriptionColLabel:"Zonbeskrivning",uniqueZoneRequiredMsg:"Zonnamnet ska vara unikt f\u00f6r",interactive:"Interaktiv",fromCoord:"Fast koordinat",existingFeature:"Fr\u00e5n befintliga geoobjekt",defaultInputLocationLabel:"Standardindataplats",
defaultInputLayer:"Standardindatalager",defaultThreatType:"Standardtyp f\u00f6r hot",selectLabel:"V\u00e4lj",mandatoryLabel:"Obligatorisk evakueringsdistans",safeLabel:"S\u00e4ker evakueringsdistans",lpgSafeDistanceLable:"S\u00e4kert avst\u00e5nd",fireBallDiameterLable:"Eldklotsdiameter",_localized:{}}});