// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/setting/nls/strings":{transparencyLabel:"Przezroczysto\u015b\u0107",outline:"Obrys",fill:"Wype\u0142nienie (kolor zostanie zastosowany tylko wtedy, gdy wybranym stylem jest styl pe\u0142ny)",style:"Styl",selectOpLayerLabel:"Wybierz warstw\u0119 operacyjn\u0105 dla wynik\u00f3w",selectDefaultMeasurementLabel:"Wybierz domy\u015bln\u0105 jednostk\u0119 miary",helpIconTooltip:"Lista warstw operacyjnych jest zape\u0142niana warstwami z bie\u017c\u0105cej mapy internetowej o typie geometrii poligonowej.",
lineStyles:{esriSLSDash:"Kreska",esriSLSDashDot:"Kreska-kropka",esriSLSDashDotDot:"Kreska-kropka-kropka",esriSLSDot:"Kropka",esriSLSLongDash:"D\u0142uga kreska",esriSLSLongDashDot:"D\u0142uga kreska-kropka",esriSLSNull:"Pusta warto\u015b\u0107",esriSLSShortDash:"Kr\u00f3tka kreska",esriSLSShortDashDot:"Kr\u00f3tka kreska-kropka",esriSLSShortDashDotDot:"Kr\u00f3tka kreska-kropka-kropka",esriSLSShortDot:"Kr\u00f3tka kropka",esriSLSSolid:"Sta\u0142y"},fillStyles:{esriSFSBackwardDiagonal:"Cofnij",esriSFSCross:"Krzy\u017c",
esriSFSDiagonalCross:"Po przek\u0105tnej",esriSFSForwardDiagonal:"Dalej",esriSFSHorizontal:"Poziomo",esriSFSNull:"Pusta warto\u015b\u0107",esriSFSSolid:"Sta\u0142y",esriSFSVertical:"Pionowo"},threatTypeLabel:"Typ zagro\u017cenia",generalLabel:"Og\u00f3lne",addThreatTypesLabel:"Dodaj typ zagro\u017cenia",actions:"Akcje",newThreatTypePopupLabel:"Nowy typ zagro\u017cenia",units:"Jednostki",chooseDefaultThreatLabel:"Wybierz domy\u015blny typ zagro\u017cenia",defaultThreatTypePopUpLabel:"Domy\u015blne typy zagro\u017ce\u0144",
editThreatLabel:"Edytuj zagro\u017cenie",defaultThreatTypeIconTooltip:"Lista domy\u015blnych typ\u00f3w zagro\u017ce\u0144",uniqueThreatTypeMsg:"Wprowad\u017a unikalny typ zagro\u017cenia. Typ zagro\u017cenia o tej nazwie ju\u017c istnieje.",requiredMsg:"To pole jest wymagane",unitMeasureLabel:"Odleg\u0142o\u015bci s\u0105 podawane w {0}",chooseDefaultThreatTypeIconLabel:"Wybierz spo\u015br\u00f3d domy\u015blnych",pipeBombLabel:"Bomba rurowa",suicideBombLabel:"Bomba samob\u00f3jcza",briefcaseLabel:"Teczka",
carLabel:"Samoch\u00f3d",suvVanLabel:"SUV/VAN",smallDeliveryTruckLabel:"Ma\u0142y samoch\u00f3d dostawczy",containerWaterTruckLabel:"Pojazd kontenerowy/cysterna",semiTrailerLabel:"Naczepa",chemicalThreatLegendLabel:"Zagro\u017cenie chemiczne",lpgThreatLegendLabel:"Zagro\u017cenie LPG",smallLPGTank:"Ma\u0142y zbiornik LPG",largeLPGTank:"Du\u017cy zbiornik LPG",commercialResidentialLPGTank:"Komercyjny/przydomowy zbiornik LPG",smallLPGTruck:"Ma\u0142a cysterna LPG",semiTankerLPG:"Naczepa z cystern\u0105 LPG",
threatDescriptionColLabel:"Opis zagro\u017cenia",addThreatZoneButtonLabel:"Dodaj stref\u0119 zagro\u017cenia",zoneDescColLabel:"Opis strefy",distanceLabel:"Odleg\u0142o\u015b\u0107 (${unitAbbr})",threatTypeHelp:"\x3cp\x3eUpewnij si\u0119, \u017ce typ zagro\u017cenia spe\u0142nia nast\u0119puj\u0105ce wymagania:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eTyp zagro\u017cenia nie mo\u017ce by\u0107 pusty i powinien by\u0107 unikalny\x3c/li\x3e\x3cli\x3eZagro\u017cenie powinno mie\u0107 co najmniej jedn\u0105 prawid\u0142ow\u0105 stref\u0119\x3c/li\x3e\x3cli\x3eOpis strefy powinien by\u0107 unikalny dla zagro\u017cenia\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e",
descriptionLabel:"Opis",newThreatZonePopupLabel:"Nowa strefa zagro\u017cenia",editThreatZonePopupLabel:"Edytuj stref\u0119 zagro\u017cenia",uniqueZoneDescriptionMsg:"Wprowad\u017a unikalny opis strefy. Opis strefy o tej nazwie ju\u017c istnieje.",symbologyColLabel:"Symbolizacja",zoneDescriptionColLabel:"Opis strefy",uniqueZoneRequiredMsg:"Nazwa strefy powinna by\u0107 unikalna dla",interactive:"Interaktywnie",fromCoord:"Sta\u0142e wsp\u00f3\u0142rz\u0119dne",existingFeature:"Od istniej\u0105cych obiekt\u00f3w",
defaultInputLocationLabel:"Domy\u015blna lokalizacja wej\u015bciowa",defaultInputLayer:"Domy\u015blna warstwa wej\u015bciowa",defaultThreatType:"Domy\u015blny typ zagro\u017cenia",selectLabel:"Wybierz",mandatoryLabel:"Obowi\u0105zkowa odleg\u0142o\u015b\u0107 ewakuacji",safeLabel:"Bezpieczna odleg\u0142o\u015b\u0107 ewakuacji",lpgSafeDistanceLable:"Bezpieczna odleg\u0142o\u015b\u0107",fireBallDiameterLable:"\u015arednica kuli ognistej",_localized:{}}});