// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/setting/nls/strings":{transparencyLabel:"Transparen\u021b\u0103",outline:"Contur",fill:"Umplere (culoarea se aplic\u0103 doar c\u00e2nd stilul este setat la continuu)",style:"Stil",selectOpLayerLabel:"Selecta\u021bi un strat tematic opera\u021bional pentru rezultate",selectDefaultMeasurementLabel:"Selecta\u021bi o unitate de m\u0103sur\u0103 implicit\u0103",helpIconTooltip:"Lista cu straturi tematice opera\u021bionale este populat\u0103 cu straturi tematice din harta web actual\u0103, care au o geometrie de tip poligon.",
lineStyles:{esriSLSDash:"Linie",esriSLSDashDot:"Linie punct",esriSLSDashDotDot:"Linie punct punct",esriSLSDot:"Punct",esriSLSLongDash:"Linie lung\u0103",esriSLSLongDashDot:"Linie lung\u0103 punct",esriSLSNull:"Nul",esriSLSShortDash:"Linie scurt\u0103",esriSLSShortDashDot:"Linie scurt\u0103 punct",esriSLSShortDashDotDot:"Linie scurt\u0103 punct punct",esriSLSShortDot:"Punct scurt",esriSLSSolid:"Continuu"},fillStyles:{esriSFSBackwardDiagonal:"\u00cenapoi",esriSFSCross:"Cruce",esriSFSDiagonalCross:"Diagonal\u0103",
esriSFSForwardDiagonal:"\u00cenainte",esriSFSHorizontal:"Orizontal\u0103",esriSFSNull:"Nul",esriSFSSolid:"Continuu",esriSFSVertical:"Vertical\u0103"},threatTypeLabel:"Tip de amenin\u021bare",generalLabel:"General",addThreatTypesLabel:"Ad\u0103ugare tip de amenin\u021bare",actions:"Ac\u021biuni",newThreatTypePopupLabel:"Tip de amenin\u021bare nou",units:"Unit\u0103\u021bi",chooseDefaultThreatLabel:"Selecta\u021bi tipul de amenin\u021bare implicit",defaultThreatTypePopUpLabel:"Tipuri de amenin\u021bare Implicite",
editThreatLabel:"Editare amenin\u021bare",defaultThreatTypeIconTooltip:"List\u0103 cu tipuri de amenin\u021bare implicite",uniqueThreatTypeMsg:"Introduce\u021bi un tip de amenin\u021bare unic, exist\u0103 deja un tip de amenin\u021bare cu acest nume.",requiredMsg:"Acest c\u00e2mp este obligatoriu",unitMeasureLabel:"Distan\u021bele sunt \u00een {0}",chooseDefaultThreatTypeIconLabel:"Alege\u021bi din valorile implicite",pipeBombLabel:"Bomb\u0103 artizanal\u0103",suicideBombLabel:"Sinuciga\u0219 cu bomb\u0103",
briefcaseLabel:"Serviet\u0103",carLabel:"Autoturism",suvVanLabel:"SUV/camionet\u0103",smallDeliveryTruckLabel:"Camion de livrare de mici dimensiuni",containerWaterTruckLabel:"Container/cistern\u0103",semiTrailerLabel:"Semiremorc\u0103",chemicalThreatLegendLabel:"Amenin\u021bare chimic\u0103",lpgThreatLegendLabel:"Amenin\u021bare GPL",smallLPGTank:"Rezervor de GPL mic",largeLPGTank:"Rezervor de GPL mare",commercialResidentialLPGTank:"Rezervor de GPL comercial/reziden\u021bial",smallLPGTruck:"Camion de GPL mic",
semiTankerLPG:"Autocistern\u0103 de GPL",threatDescriptionColLabel:"Descrierea amenin\u021b\u0103rii",addThreatZoneButtonLabel:"Ad\u0103ugare tip de amenin\u021bare",zoneDescColLabel:"Descrierea zonei",distanceLabel:"Distan\u021b\u0103 (${unitAbbr})",threatTypeHelp:"\x3cp\x3eAsigura\u021bi-v\u0103 de respectarea condi\u021biilor urm\u0103toare pentru un tip de amenin\u021bare:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eTipul de amenin\u021bare nu poate fi gol \u0219i trebuie s\u0103 fie unic\x3c/li\x3e\x3cli\x3eAmenin\u021barea trebuie s\u0103 aib\u0103 cel pu\u021bin o zon\u0103 valabil\u0103\x3c/li\x3e\x3cli\x3eDescrierea zonei trebuie s\u0103 fie unic\u0103 pentru o amenin\u021bare\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e",
descriptionLabel:"Descriere",newThreatZonePopupLabel:"Zon\u0103 de amenin\u021bare nou\u0103",editThreatZonePopupLabel:"Edita\u021bi zona de amenin\u021bare",uniqueZoneDescriptionMsg:"Introduce\u021bi o descriere unic\u0103 a zonei, exist\u0103 deja o descriere a zonei cu acest nume.",symbologyColLabel:"Simbologie",zoneDescriptionColLabel:"Descrierea zonei",uniqueZoneRequiredMsg:"Numele zonei trebuie s\u0103 fie unic pentru",interactive:"Interactiv",fromCoord:"Coordonat\u0103 fix\u0103",existingFeature:"Din obiecte spa\u021biale existente",
defaultInputLocationLabel:"Loc de intrare implicit",defaultInputLayer:"Strat tematic de intrare implicit",defaultThreatType:"Tip de amenin\u021bare implicit",selectLabel:"Selectare",mandatoryLabel:"Distan\u021b\u0103 obligatorie de evacuare",safeLabel:"Distan\u021b\u0103 sigur\u0103 de evacuare",lpgSafeDistanceLable:"Distan\u021b\u0103 sigur\u0103",fireBallDiameterLable:"Diametrul mingii de foc",_localized:{}}});