// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/setting/nls/strings":{transparencyLabel:"Transparency",outline:"Outline",fill:"Fill (Color only applies when style set to solid)",style:"Style",selectOpLayerLabel:"Select an operational layer for results",selectDefaultMeasurementLabel:"Select a default unit of measure",helpIconTooltip:"The operational layer list is populated with layers from the current web map that are polygon geometry type.",lineStyles:{esriSLSDash:"Dash",esriSLSDashDot:"Dash Dot",esriSLSDashDotDot:"Dash Dot Dot",
esriSLSDot:"Dot",esriSLSLongDash:"Long Dash",esriSLSLongDashDot:"Long Dash Dot",esriSLSNull:"Null",esriSLSShortDash:"Short Dash",esriSLSShortDashDot:"Short Dash Dot",esriSLSShortDashDotDot:"Short Dash Dot Dot",esriSLSShortDot:"Short Dot",esriSLSSolid:"Solid"},fillStyles:{esriSFSBackwardDiagonal:"Backward",esriSFSCross:"Cross",esriSFSDiagonalCross:"Diagonal",esriSFSForwardDiagonal:"Forward",esriSFSHorizontal:"Horizontal",esriSFSNull:"Null",esriSFSSolid:"Solid",esriSFSVertical:"Vertical"},threatTypeLabel:"Threat Type",
generalLabel:"General",addThreatTypesLabel:"Add threat type",actions:"Actions",newThreatTypePopupLabel:"New threat type",units:"Units",chooseDefaultThreatLabel:"Select default threat type",defaultThreatTypePopUpLabel:"Default Threat Types",editThreatLabel:"Edit Threat",defaultThreatTypeIconTooltip:"Default Threat Type List",uniqueThreatTypeMsg:"Enter unique threat type, threat type with this name already exist.",requiredMsg:"This field is required",unitMeasureLabel:"Distances are in {0}",chooseDefaultThreatTypeIconLabel:"Choose from default",
pipeBombLabel:"Pipe Bomb",suicideBombLabel:"Suicide Bomb",briefcaseLabel:"Briefcase",carLabel:"Car",suvVanLabel:"SUV/VAN",smallDeliveryTruckLabel:"Small Delivery Truck",containerWaterTruckLabel:"Container/Water Truck",semiTrailerLabel:"Semi-Trailer",chemicalThreatLegendLabel:"Chemical Threat",lpgThreatLegendLabel:"LPG Threat",smallLPGTank:"Small LPG Tank",largeLPGTank:"Large LPG Tank",commercialResidentialLPGTank:"Commercial/Residential LPG Tank",smallLPGTruck:"Small LPG Truck",semiTankerLPG:"Semi-Tanker LPG",
threatDescriptionColLabel:"Threat Description",addThreatZoneButtonLabel:"Add threat zone",zoneDescColLabel:"Zone description",distanceLabel:"Distance (${unitAbbr})",threatTypeHelp:"\x3cp\x3eMake sure the following conditions are met for a threat type:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eThreat type cannot be blank and it should be unique\x3c/li\x3e\x3cli\x3eThreat should have at least one valid zone\x3c/li\x3e\x3cli\x3eZone description should be unique for a threat\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e",descriptionLabel:"Description",
newThreatZonePopupLabel:"New threat zone",editThreatZonePopupLabel:"Edit threat zone",uniqueZoneDescriptionMsg:"Enter unique zone description, zone description with this name already exist.",symbologyColLabel:"Symbology",zoneDescriptionColLabel:"Zone description",uniqueZoneRequiredMsg:"Zone name should be unique for the",interactive:"Interactive",fromCoord:"Fixed Coordinate",existingFeature:"From Existing Features",defaultInputLocationLabel:"Default input location",defaultInputLayer:"Default input layer",
defaultThreatType:"Default threat type",selectLabel:"Select",mandatoryLabel:"Mandatory Evacuation Distance",safeLabel:"Safe Evacuation Distance",lpgSafeDistanceLable:"Safe Distance",fireBallDiameterLable:"Fireball Diameter",_localized:{}}});