// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/setting/nls/strings":{transparencyLabel:"Prosojnost",outline:"Obroba",fill:"Polnilo (barva se uporablja le, \u010de je slog nastavljen na enobarvno polnilo)",style:"Slog",selectOpLayerLabel:"Izberi operativni sloj za rezultate",selectDefaultMeasurementLabel:"Izberi privzeto mersko enoto",helpIconTooltip:"Seznam operativnega sloja je poseljen s sloji iz trenutne spletne karte, ki so poligonske geometrijske vrste.",lineStyles:{esriSLSDash:"\u010crtica",esriSLSDashDot:"\u010crtica pika",
esriSLSDashDotDot:"\u010crtica pika pika",esriSLSDot:"Pika",esriSLSLongDash:"Dolga \u010drtica",esriSLSLongDashDot:"Dolga \u010drtica pika",esriSLSNull:"Brez vrednosti",esriSLSShortDash:"Kratka \u010drtica",esriSLSShortDashDot:"Kratka \u010drtica pika",esriSLSShortDashDotDot:"Kratka \u010drtica pika pika",esriSLSShortDot:"Kratka pika",esriSLSSolid:"Enobarvno"},fillStyles:{esriSFSBackwardDiagonal:"Nazaj",esriSFSCross:"Kri\u017e",esriSFSDiagonalCross:"Diagonalno",esriSFSForwardDiagonal:"Naprej",esriSFSHorizontal:"Horizontalno",
esriSFSNull:"Brez vrednosti",esriSFSSolid:"Enobarvno",esriSFSVertical:"Vertikalno"},threatTypeLabel:"Vrsta nevarnosti",generalLabel:"Splo\u0161no",addThreatTypesLabel:"Dodajte vrsto nevarnosti",actions:"Dejanja",newThreatTypePopupLabel:"Nova vrsta nevarnosti",units:"Enote",chooseDefaultThreatLabel:"Izberite privzeto vrsto nevarnosti",defaultThreatTypePopUpLabel:"Privzete vrste nevarnosti",editThreatLabel:"Uredite nevarnost",defaultThreatTypeIconTooltip:"Seznam privzetih vrst nevarnosti",uniqueThreatTypeMsg:"Vnesite enoli\u010dno vrsto nevarnosti, vrsta nevarnosti s tem imenom \u017ee obstaja.",
requiredMsg:"To polje ni obvezno",unitMeasureLabel:"Razdalje so v {0}",chooseDefaultThreatTypeIconLabel:"Izberite izmed privzetega",pipeBombLabel:"Cevna bomba",suicideBombLabel:"Samomorilska bomba",briefcaseLabel:"Aktovka",carLabel:"Avto",suvVanLabel:"SUV/VAN",smallDeliveryTruckLabel:"Majhno dostavno vozilo",containerWaterTruckLabel:"Zabojnik/tovornjak za preva\u017eanje vode",semiTrailerLabel:"Polpriklopnik",chemicalThreatLegendLabel:"Kemi\u010dna nevarnost",lpgThreatLegendLabel:"Nevarnost UNP",
smallLPGTank:"Majhen rezervoar z UNP",largeLPGTank:"Velik rezervoar z UNP",commercialResidentialLPGTank:"Komercialni/stanovanjski rezervoar z UNP",smallLPGTruck:"Majhno tovorno vozilo z UNP",semiTankerLPG:"Polpriklopnik s cisterno UNP",threatDescriptionColLabel:"Opis nevarnosti",addThreatZoneButtonLabel:"Dodajte cono nevarnosti",zoneDescColLabel:"Opis cone",distanceLabel:"Razdalja (${unitAbbr})",threatTypeHelp:"\x3cp\x3ePrepri\u010dajte se, da so izpolnjeni naslednji pogoji za vrsto nevarnosti:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eVrsta nevarnosti ne more biti nedolo\u010dena in mora biti enoli\u010dna\x3c/li\x3e\x3cli\x3eNevarnost mora imeti vsaj eno veljavno cono\x3c/li\x3e\x3cli\x3eOpis cone mora biti enoli\u010den za nevarnost\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e",
descriptionLabel:"Opis",newThreatZonePopupLabel:"Nova cona nevarnosti",editThreatZonePopupLabel:"Uredite cono nevarnosti",uniqueZoneDescriptionMsg:"Vnesite enoli\u010den opis cone, opis cone s tem imenom \u017ee obstaja.",symbologyColLabel:"Simbologija",zoneDescriptionColLabel:"Opis cone",uniqueZoneRequiredMsg:"Ime cone mora biti enoli\u010dno za",interactive:"Interaktivno",fromCoord:"Fiksne koordinate",existingFeature:"Iz obstoje\u010dih geoobjektov",defaultInputLocationLabel:"Privzeta vhodna lokacija",
defaultInputLayer:"Privzeti vhodni sloj",defaultThreatType:"Privzeta vrsta nevarnosti",selectLabel:"Izberi",mandatoryLabel:"Obvezna razdalja za evakuacijo",safeLabel:"Varna razdalja za evakuacijo",lpgSafeDistanceLable:"Varna razdalja",fireBallDiameterLable:"Premer ognjene krogle",_localized:{}}});