// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/setting/nls/strings":{transparencyLabel:"Transpar\u00eancia",outline:"Contorno",fill:"Preenchimento (Apenas \u00e9 aplicada cor quando o estilo \u00e9 definido como s\u00f3lido)",style:"Estilo",selectOpLayerLabel:"Selecionar uma nova camada operacional para os resultados",selectDefaultMeasurementLabel:"Selecionar a unidade de medida predefinida",helpIconTooltip:"A lista de camadas operacionais \u00e9 preenchida com camadas do mapa web atual do tipo de geometria de pol\u00edgono.",
lineStyles:{esriSLSDash:"Tra\u00e7o",esriSLSDashDot:"Tra\u00e7o e Ponto",esriSLSDashDotDot:"Tra\u00e7o, Ponto e Ponto",esriSLSDot:"Ponto",esriSLSLongDash:"Tra\u00e7o Longo",esriSLSLongDashDot:"Tra\u00e7o Longo e Ponto",esriSLSNull:"Nulo",esriSLSShortDash:"Tra\u00e7o Curto",esriSLSShortDashDot:"Tra\u00e7o Curto e Ponto",esriSLSShortDashDotDot:"Tra\u00e7o Curto, Ponto e Ponto",esriSLSShortDot:"Tra\u00e7o Curto",esriSLSSolid:"S\u00f3lido"},fillStyles:{esriSFSBackwardDiagonal:"Ao Contr\u00e1rio",esriSFSCross:"Cruz",
esriSFSDiagonalCross:"Diagonal",esriSFSForwardDiagonal:"Para a frente",esriSFSHorizontal:"Horizontal",esriSFSNull:"Nulo",esriSFSSolid:"S\u00f3lido",esriSFSVertical:"Vertical"},threatTypeLabel:"Tipo de amea\u00e7a",generalLabel:"Geral",addThreatTypesLabel:"Adicionar tipo de amea\u00e7a",actions:"A\u00e7\u00f5es",newThreatTypePopupLabel:"Novo tipo de amea\u00e7a",units:"Unidades",chooseDefaultThreatLabel:"Selecionar tipo de amea\u00e7a predefinido",defaultThreatTypePopUpLabel:"Tipos de Amea\u00e7a Predefinidos",
editThreatLabel:"Editar Amea\u00e7a",defaultThreatTypeIconTooltip:"Lista de Tipos de Amea\u00e7a Predefinidos",uniqueThreatTypeMsg:"Introduza um tipo de amea\u00e7a \u00fanico; j\u00e1 existe um tipo de amea\u00e7a com este nome.",requiredMsg:"Este campo \u00e9 obrigat\u00f3rio",unitMeasureLabel:"As dist\u00e2ncias est\u00e3o em {0}",chooseDefaultThreatTypeIconLabel:"Escolher de predefini\u00e7\u00e3o",pipeBombLabel:"Bomba de Tubo",suicideBombLabel:"Bomba Suicida",briefcaseLabel:"Pasta",carLabel:"Carro",
suvVanLabel:"SUV/CARRINHA",smallDeliveryTruckLabel:"Carrinha de Entregas Pequena",containerWaterTruckLabel:"Cami\u00e3o Cisterna/de \u00c1gua",semiTrailerLabel:"Semirreboque",chemicalThreatLegendLabel:"Amea\u00e7a Qu\u00edmica",lpgThreatLegendLabel:"Amea\u00e7a GPL",smallLPGTank:"Tanque Pequeno GPL",largeLPGTank:"Tanque Grande GPL",commercialResidentialLPGTank:"Tanque GPL Comercial/Residencial",smallLPGTruck:"Cami\u00e3o Pequeno GPL",semiTankerLPG:"Semirreboque GPL",threatDescriptionColLabel:"Descri\u00e7\u00e3o de Amea\u00e7a",
addThreatZoneButtonLabel:"Adicionar zona de amea\u00e7a",zoneDescColLabel:"Descri\u00e7\u00e3o de zona",distanceLabel:"Dist\u00e2ncia (${unitAbbr})",threatTypeHelp:"\x3cp\x3eCertifique-se de que as seguintes condi\u00e7\u00f5es s\u00e3o cumpridas para um tipo de amea\u00e7a:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eO tipo de amea\u00e7a n\u00e3o pode ficar em branco e deve ser exclusivo\x3c/li\x3e\x3cli\x3eA amea\u00e7a deve ter pelo menos uma zona v\u00e1lida\x3c/li\x3e\x3cli\x3eA descri\u00e7\u00e3o de zona deve ser exclusiva para uma amea\u00e7a\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e",
descriptionLabel:"Descri\u00e7\u00e3o",newThreatZonePopupLabel:"Nova zona de amea\u00e7a",editThreatZonePopupLabel:"Editar zona de amea\u00e7a",uniqueZoneDescriptionMsg:"Introduza uma descri\u00e7\u00e3o de zona exclusiva, pois a descri\u00e7\u00e3o de zona com este nome j\u00e1 existe.",symbologyColLabel:"Simbologia",zoneDescriptionColLabel:"Descri\u00e7\u00e3o de zona",uniqueZoneRequiredMsg:"O nome da zona deve ser exclusivo para o(a)",interactive:"Interativo",fromCoord:"Coordenadas fixas",existingFeature:"A partir de elementos existentes",
defaultInputLocationLabel:"Localiza\u00e7\u00e3o de entrada predefinida",defaultInputLayer:"Camada de entrada predefinida",defaultThreatType:"Tipo de amea\u00e7a predefinido",selectLabel:"Selecionar",mandatoryLabel:"Dist\u00e2ncia de evacua\u00e7\u00e3o obrigat\u00f3ria",safeLabel:"Dist\u00e2ncia de evacua\u00e7\u00e3o segura",lpgSafeDistanceLable:"Dist\u00e2ncia Segura",fireBallDiameterLable:"Di\u00e2metro de Bola de Fogo",_localized:{}}});