// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/setting/nls/strings":{transparencyLabel:"L\u00e4pin\u00e4kyvyys",outline:"\u00c4\u00e4riviiva",fill:"T\u00e4ytt\u00f6 (v\u00e4ri\u00e4 k\u00e4ytet\u00e4\u00e4n vain, kun tyyliksi on m\u00e4\u00e4ritetty yhten\u00e4inen)",style:"Tyyli",selectOpLayerLabel:"Valitse toiminnallinen karttataso tuloksia varten",selectDefaultMeasurementLabel:"Valitse oletusmittayksikk\u00f6",helpIconTooltip:"Toiminnallisten karttatasojen luettelo t\u00e4ytet\u00e4\u00e4n nykyisen web-karttan karttatasoilla, jotka ovat tyypilt\u00e4\u00e4n aluekohdegeometrioita.",
lineStyles:{esriSLSDash:"Viiva",esriSLSDashDot:"Viiva-piste",esriSLSDashDotDot:"Viiva-piste-piste",esriSLSDot:"Piste",esriSLSLongDash:"Pitk\u00e4 viiva",esriSLSLongDashDot:"Pitk\u00e4 viiva-piste",esriSLSNull:"Null",esriSLSShortDash:"Lyhyt viiva",esriSLSShortDashDot:"Lyhyt viiva-piste",esriSLSShortDashDotDot:"Lyhyt viiva-piste-piste",esriSLSShortDot:"Lyhyt piste",esriSLSSolid:"Yhten\u00e4inen"},fillStyles:{esriSFSBackwardDiagonal:"Taaksep\u00e4in",esriSFSCross:"Risti",esriSFSDiagonalCross:"L\u00e4vist\u00e4j\u00e4n suunnassa",
esriSFSForwardDiagonal:"Eteenp\u00e4in",esriSFSHorizontal:"Vaaka",esriSFSNull:"Null",esriSFSSolid:"Yhten\u00e4inen",esriSFSVertical:"Pysty"},threatTypeLabel:"Uhkan laji",generalLabel:"Yleinen",addThreatTypesLabel:"Lis\u00e4\u00e4 uhkan laji",actions:"Toiminnot",newThreatTypePopupLabel:"Uusi uhkan laji",units:"Yksik\u00f6t",chooseDefaultThreatLabel:"Valitse oletusarvoinen uhkan laji",defaultThreatTypePopUpLabel:"Uhkan lajin oletusarvot",editThreatLabel:"Muokkaa uhkaa",defaultThreatTypeIconTooltip:"Uhkan lajin oletusarvoluettelo",
uniqueThreatTypeMsg:"Anna yksil\u00f6llinen uhkan laji. Samanniminen uhkan laji on jo olemassa.",requiredMsg:"T\u00e4m\u00e4 on pakollinen kentt\u00e4",unitMeasureLabel:"Et\u00e4isyydet ovat yksik\u00f6ss\u00e4 {0}",chooseDefaultThreatTypeIconLabel:"Valitse oletusarvoista",pipeBombLabel:"Putkipommi",suicideBombLabel:"Itsemurhapommi",briefcaseLabel:"Salkku",carLabel:"Auto",suvVanLabel:"Kaupunkimaasturi/pakettiauto",smallDeliveryTruckLabel:"Pieni jakeluauto",containerWaterTruckLabel:"S\u00e4ili\u00f6-/vesis\u00e4ili\u00f6auto",
semiTrailerLabel:"Puoliper\u00e4vaunu",chemicalThreatLegendLabel:"Kemiallinen uhka",lpgThreatLegendLabel:"Nestekaasun aiheuttama uhka",smallLPGTank:"Pieni nestekaasus\u00e4ili\u00f6",largeLPGTank:"Suuri nestekaasus\u00e4ili\u00f6",commercialResidentialLPGTank:"Kaupallinen tai kotitalousk\u00e4ytt\u00f6\u00f6n tarkoitettu nestekaasus\u00e4ili\u00f6",smallLPGTruck:"Pieni nestekaasus\u00e4ili\u00f6auto",semiTankerLPG:"Keskikokoinen nestekaasus\u00e4ili\u00f6auto",threatDescriptionColLabel:"Uhkan kuvaus",
addThreatZoneButtonLabel:"Lis\u00e4\u00e4 uhkavy\u00f6hyke",zoneDescColLabel:"Vy\u00f6hykkeen kuvaus",distanceLabel:"Et\u00e4isyys (${unitAbbr})",threatTypeHelp:"\x3cp\x3eVarmista, ett\u00e4 seuraavat uhkan lajia koskevat ehdot t\u00e4yttyv\u00e4t:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eUhkan laji ei voi olla tyhj\u00e4, ja arvon on oltava yksil\u00f6llinen\x3c/li\x3e\x3cli\x3eUhkalla on oltava v\u00e4hint\u00e4\u00e4n yksi kelvollinen vy\u00f6hyke\x3c/li\x3e\x3cli\x3eUhkavy\u00f6hykkeen kuvauksen on oltava yksil\u00f6llinen\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e",
descriptionLabel:"Kuvaus",newThreatZonePopupLabel:"Uusi uhkavy\u00f6hyke",editThreatZonePopupLabel:"Muokkaa uhkavy\u00f6hykett\u00e4",uniqueZoneDescriptionMsg:"Kirjoita yksil\u00f6llinen vy\u00f6hykkeen kuvaus. T\u00e4m\u00e4nniminen kuvaus on jo olemassa.",symbologyColLabel:"Symbolit",zoneDescriptionColLabel:"Vy\u00f6hykkeen kuvaus",uniqueZoneRequiredMsg:"Vy\u00f6hykkeen nimen on oltava yksil\u00f6llinen kohteelle",interactive:"Vuorovaikutteinen",fromCoord:"Kiinte\u00e4 koordinaatti",existingFeature:"Aiemmin m\u00e4\u00e4ritetyist\u00e4 kohteista",
defaultInputLocationLabel:"Oletusarvoinen l\u00e4ht\u00f6aineiston sijainti",defaultInputLayer:"Oletusarvoinen l\u00e4ht\u00f6aineiston karttataso",defaultThreatType:"Oletusarvoinen uhkan laji",selectLabel:"Valitse",mandatoryLabel:"Pakollinen evakuointiet\u00e4isyys",safeLabel:"Turvallinen evakuointiet\u00e4isyys",lpgSafeDistanceLable:"Turvaet\u00e4isyys",fireBallDiameterLable:"Tulipallon l\u00e4pimitta",_localized:{}}});