// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/setting/nls/strings":{transparencyLabel:"Transpar\u00eancia",outline:"Contorno",fill:"Preencher (a cor somente se aplica quando o estilo \u00e9 definido para s\u00f3lido)",style:"Estilo",selectOpLayerLabel:"Selecione uma camada operacional para resultados",selectDefaultMeasurementLabel:"Selecione uma unidade de medi\u00e7\u00e3o padr\u00e3o.",helpIconTooltip:"A lista de camada operacional \u00e9 preenchida com camadas a partir do mapa da web atual que s\u00e3o do tipo de geometria de pol\u00edgono.",
lineStyles:{esriSLSDash:"Tra\u00e7o",esriSLSDashDot:"Tra\u00e7o Ponto",esriSLSDashDotDot:"Tra\u00e7o Ponto Ponto",esriSLSDot:"Ponto",esriSLSLongDash:"Tra\u00e7o Longo",esriSLSLongDashDot:"Tra\u00e7o Longo Ponto",esriSLSNull:"Nulo",esriSLSShortDash:"Tra\u00e7o Curto",esriSLSShortDashDot:"Ponto Tra\u00e7o Curto",esriSLSShortDashDotDot:"Ponto Ponto Tra\u00e7o Curto",esriSLSShortDot:"Ponto Curto",esriSLSSolid:"S\u00f3lido"},fillStyles:{esriSFSBackwardDiagonal:"Para Tr\u00e1s",esriSFSCross:"Transversal",
esriSFSDiagonalCross:"Diagonal",esriSFSForwardDiagonal:"Para Frente",esriSFSHorizontal:"Horizontal",esriSFSNull:"Nulo",esriSFSSolid:"S\u00f3lido",esriSFSVertical:"Vertical"},threatTypeLabel:"Tipo de Camada",generalLabel:"Geral",addThreatTypesLabel:"Adicionar tipo de camada",actions:"A\u00e7\u00f5es",newThreatTypePopupLabel:"Novo tipo de camada",units:"Unidades",chooseDefaultThreatLabel:"Selecionar tipo de camada padr\u00e3o",defaultThreatTypePopUpLabel:"Tipos de Camada Padr\u00e3o",editThreatLabel:"Editar Camada",
defaultThreatTypeIconTooltip:"Lista do Tipo de Camada Padr\u00e3o",uniqueThreatTypeMsg:"Insira o tipo de camada \u00fanico, o tipo de camada com este nome j\u00e1 existe.",requiredMsg:"Este campo \u00e9 obrigat\u00f3rio",unitMeasureLabel:"As dist\u00e2ncias est\u00e3o em {0}",chooseDefaultThreatTypeIconLabel:"Escolher do padr\u00e3o",pipeBombLabel:"Bomba Caseira",suicideBombLabel:"Ataque Suicida",briefcaseLabel:"Porta-arquivos",carLabel:"Carro",suvVanLabel:"SUV/VAN",smallDeliveryTruckLabel:"Caminh\u00e3o de entrega pequeno",
containerWaterTruckLabel:"Cont\u00eainer/Caminh\u00e3o Pipa",semiTrailerLabel:"Semi-Trailer",chemicalThreatLegendLabel:"Amea\u00e7a Qu\u00edmica",lpgThreatLegendLabel:"Amea\u00e7a de LPG",smallLPGTank:"Tanque LPG Pequeno",largeLPGTank:"Tanque LPG Grande",commercialResidentialLPGTank:"Tanque LPG Comercial/Residencial",smallLPGTruck:"Caminh\u00e3o LPG Pequeno",semiTankerLPG:"Semi-petroleiro LPG",threatDescriptionColLabel:"Este campo \u00e9 exigido",addThreatZoneButtonLabel:"Adicionar zona de amea\u00e7a",
zoneDescColLabel:"Descri\u00e7\u00e3o da zona",distanceLabel:"Dist\u00e2ncia (${unitAbbr})",threatTypeHelp:"\x3cp\x3eCertifique-se que as seguintes condi\u00e7\u00f5es sejam atendidas para um tipo de camada:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eO tipo de camada n\u00e3o pode ficar em branco e deve ser \u00fanico\x3c/li\x3e\x3cli\x3eA camada deve ter pelo menos uma zona v\u00e1lida\x3c/li\x3e\x3cli\x3eA descri\u00e7\u00e3o da zona deve ser \u00fanica para uma camada\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e",descriptionLabel:"Descri\u00e7\u00e3o",
newThreatZonePopupLabel:"Nova zona de amea\u00e7a",editThreatZonePopupLabel:"Editar zona de amea\u00e7a",uniqueZoneDescriptionMsg:"Insira a descri\u00e7\u00e3o de zona \u00fanica, a descri\u00e7\u00e3o da zona com este nome j\u00e1 existe.",symbologyColLabel:"Simbologia",zoneDescriptionColLabel:"Descri\u00e7\u00e3o da zona",uniqueZoneRequiredMsg:"o nome da zona deve ser \u00fanico para",interactive:"Interativo",fromCoord:"Coordenada Fixa",existingFeature:"Das Fei\u00e7\u00f5es Existentes",defaultInputLocationLabel:"Local de entrada padr\u00e3o",
defaultInputLayer:"Camada de entrada padr\u00e3o",defaultThreatType:"Tipo de camada padr\u00e3o",selectLabel:"Selecionar",mandatoryLabel:"Dist\u00e2ncia Obrigat\u00f3ria de Evacua\u00e7\u00e3o",safeLabel:"Dist\u00e2ncia de Evacua\u00e7\u00e3o Segura",lpgSafeDistanceLable:"Dist\u00e2ncia Segura",fireBallDiameterLable:"Di\u00e2metro da Bola de Fogo",_localized:{}}});