// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/setting/nls/strings":{transparencyLabel:"Prozirnost",outline:"Kontura",fill:"Popuna (boja se primenjuje samo kada je stil pode\u0161en da bude neproziran)",style:"Stil",selectOpLayerLabel:"Izaberite operativni sloj za rezultate",selectDefaultMeasurementLabel:"Izaberite podrazumevanu jedinicu mere",helpIconTooltip:"Lista operativnih slojeva se popunjava slojevima iz trenutne veb mape koji su tipa poligonalne geometrije.",lineStyles:{esriSLSDash:"Crta",esriSLSDashDot:"Crta ta\u010dka",
esriSLSDashDotDot:"Crta ta\u010dka ta\u010dka",esriSLSDot:"Ta\u010dka",esriSLSLongDash:"Duga crta",esriSLSLongDashDot:"Duga crta ta\u010dka",esriSLSNull:"Null",esriSLSShortDash:"Kratka crta",esriSLSShortDashDot:"Kratka crta ta\u010dka",esriSLSShortDashDotDot:"Kratka crta ta\u010dka ta\u010dka",esriSLSShortDot:"Kratka ta\u010dka",esriSLSSolid:"Neprozirno"},fillStyles:{esriSFSBackwardDiagonal:"Unazad",esriSFSCross:"Krst",esriSFSDiagonalCross:"Dijagonalno",esriSFSForwardDiagonal:"Unapred",esriSFSHorizontal:"Horizontalno",
esriSFSNull:"Null",esriSFSSolid:"Neprozirno",esriSFSVertical:"Vertikalno"},threatTypeLabel:"Tip pretnje",generalLabel:"Op\u0161te",addThreatTypesLabel:"Dodaj tip pretnje",actions:"Radnje",newThreatTypePopupLabel:"Slede\u0107i tip pretnje",units:"Jedinice",chooseDefaultThreatLabel:"Izaberite podrazumevani tip pretnje",defaultThreatTypePopUpLabel:"Podrazumevani tipovi pretnje",editThreatLabel:"Uredi pretnju",defaultThreatTypeIconTooltip:"Lista podrazumevanih tipova pretnje",uniqueThreatTypeMsg:"Unesite jedinstveni tip pretnje, tip pretnje sa ovim nazivom ve\u0107 postoji.",
requiredMsg:"Ovo polje je obavezno",unitMeasureLabel:"Rastojanja su u {0}",chooseDefaultThreatTypeIconLabel:"Odaberite iz podrazumevanih",pipeBombLabel:"Cevna bomba",suicideBombLabel:"Samoubila\u010dka bomba",briefcaseLabel:"Aktovka",carLabel:"Auto",suvVanLabel:"SUV/KOMBI",smallDeliveryTruckLabel:"Mali dostavni kamion",containerWaterTruckLabel:"Kamion sa cisternom",semiTrailerLabel:"Poluprikolica",chemicalThreatLegendLabel:"Hemijska pretnja",lpgThreatLegendLabel:"LPG pretnja",smallLPGTank:"Mali LPG rezervoar",
largeLPGTank:"Veliki LPG rezervoar",commercialResidentialLPGTank:"Komercijalni/stambeni LPG rezervoar",smallLPGTruck:"Mali LPG kamion",semiTankerLPG:"LPG polu-tanker",threatDescriptionColLabel:"Opis pretnje",addThreatZoneButtonLabel:"Dodaj zonu pretnje",zoneDescColLabel:"Opis zone",distanceLabel:"Rastojanje (${unitAbbr})",threatTypeHelp:"\x3cp\x3eOsigurajte da su slede\u0107i uslovi ispunjeni za tip pretnje:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eTip pretnje ne mo\u017ee da bude prazan i treba da bude jedinstven\x3c/li\x3e\x3cli\x3ePretnja treba da ima bar jednu validnu zonu\x3c/li\x3e\x3cli\x3eOpis zone treba da bude jedinstven za pretnju\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e",
descriptionLabel:"Opis",newThreatZonePopupLabel:"Nova zona pretnje",editThreatZonePopupLabel:"Uredi zonu pretnje",uniqueZoneDescriptionMsg:"Unesite opis zone, opis zone pod ovim nazivom ve\u0107 postoji.",symbologyColLabel:"Simbologija",zoneDescriptionColLabel:"Opis zone",uniqueZoneRequiredMsg:"Naziv zone treba da bude jedinstven za",interactive:"Interaktivno",fromCoord:"Fiksna koordinata",existingFeature:"Iz postoje\u0107ih geoobjekata",defaultInputLocationLabel:"Podrazumevana ulazna lokacija",defaultInputLayer:"Podrazumevani ulazni sloj",
defaultThreatType:"Podrazumevani tip pretnje",selectLabel:"Selektujte",mandatoryLabel:"Obavezna evakuaciona razdaljina",safeLabel:"Bezbedna evakuaciona razdaljina",lpgSafeDistanceLable:"Bezbedno rastojanje",fireBallDiameterLable:"Pre\u010dnik vatrene kugle",_localized:{}}});