// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/setting/nls/strings":{transparencyLabel:"Transparencia",outline:"Lista",fill:"Relleno (el color solo se aplica si el estilo es s\u00f3lido)",style:"Estilo",selectOpLayerLabel:"Seleccionar una capa operativa para los resultados",selectDefaultMeasurementLabel:"Seleccionar una unidad de medida predeterminada",helpIconTooltip:"La lista de capas operativas se rellena con las capas del mapa web actual que corresponden al tipo de geometr\u00eda de pol\u00edgono.",lineStyles:{esriSLSDash:"Guion",
esriSLSDashDot:"Guion Punto",esriSLSDashDotDot:"Guion Punto Punto",esriSLSDot:"Punto",esriSLSLongDash:"Guion largo",esriSLSLongDashDot:"Guion largo, Punto",esriSLSNull:"Nulo",esriSLSShortDash:"Guion corto",esriSLSShortDashDot:"Guion corto Punto",esriSLSShortDashDotDot:"Guion corto Punto Punto",esriSLSShortDot:"Corto Punto",esriSLSSolid:"S\u00f3lido"},fillStyles:{esriSFSBackwardDiagonal:"Atr\u00e1s",esriSFSCross:"Cruz",esriSFSDiagonalCross:"Diagonal",esriSFSForwardDiagonal:"Hacia delante",esriSFSHorizontal:"Horizontal",
esriSFSNull:"Nulo",esriSFSSolid:"S\u00f3lido",esriSFSVertical:"Vertical"},threatTypeLabel:"Tipo de amenaza",generalLabel:"General",addThreatTypesLabel:"Agregar tipo de amenaza",actions:"Acciones",newThreatTypePopupLabel:"Nuevo tipo de amenaza",units:"Unidades",chooseDefaultThreatLabel:"Seleccionar tipo de amenaza predeterminado",defaultThreatTypePopUpLabel:"Tipos de amenaza predeterminados",editThreatLabel:"Editar amenaza",defaultThreatTypeIconTooltip:"Lista de tipos de amenaza predeterminados",uniqueThreatTypeMsg:"Introduzca un tipo de amenaza \u00fanico; ya existe un tipo de amenaza con este nombre.",
requiredMsg:"Este campo es obligatorio",unitMeasureLabel:"Las distancias est\u00e1n en {0}",chooseDefaultThreatTypeIconLabel:"Elegir de entre los valores predeterminados",pipeBombLabel:"Bomba casera",suicideBombLabel:"Bomba suicida",briefcaseLabel:"Malet\u00edn",carLabel:"Autom\u00f3vil",suvVanLabel:"Todoterreno/furgoneta",smallDeliveryTruckLabel:"Cami\u00f3n de reparto peque\u00f1o",containerWaterTruckLabel:"Contenedor/cami\u00f3n cisterna",semiTrailerLabel:"Semirremolque",chemicalThreatLegendLabel:"Amenaza qu\u00edmica",
lpgThreatLegendLabel:"Amenaza de GLP",smallLPGTank:"Dep\u00f3sito de GLP peque\u00f1o",largeLPGTank:"Dep\u00f3sito de GLP grande",commercialResidentialLPGTank:"Dep\u00f3sito de GLP comercial/residencial",smallLPGTruck:"Cami\u00f3n cisterna de GLP peque\u00f1o",semiTankerLPG:"Semirremolque cisterna de GLP",threatDescriptionColLabel:"Descripci\u00f3n de la amenaza",addThreatZoneButtonLabel:"Agregar zona de amenaza",zoneDescColLabel:"Descripci\u00f3n de la zona",distanceLabel:"Distancia (${unitAbbr})",
threatTypeHelp:"\x3cp\x3eAseg\u00farese de que se cumplan las siguientes condiciones para un tipo de amenaza:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eEl tipo de amenaza no puede estar en blanco y debe ser \u00fanico\x3c/li\x3e\x3cli\x3eLa amenaza debe tener al menos una zona v\u00e1lida\x3c/li\x3e\x3cli\x3eLa descripci\u00f3n de la zona debe ser \u00fanica para una amenaza\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e",descriptionLabel:"Descripci\u00f3n",newThreatZonePopupLabel:"Nueva zona de amenaza",editThreatZonePopupLabel:"Editar zona de amenaza",
uniqueZoneDescriptionMsg:"Introduzca una descripci\u00f3n de zona \u00fanica; ya existe una descripci\u00f3n de zona con este nombre.",symbologyColLabel:"Simbolog\u00eda",zoneDescriptionColLabel:"Descripci\u00f3n de la zona",uniqueZoneRequiredMsg:"El nombre de zona debe ser \u00fanico para",interactive:"Interactiva",fromCoord:"Coordenada fija",existingFeature:"De entidades existentes",defaultInputLocationLabel:"Ubicaci\u00f3n de entrada predeterminada",defaultInputLayer:"Capa de entrada predeterminada",
defaultThreatType:"Lista de amenazas predeterminadas",selectLabel:"Seleccionar",mandatoryLabel:"Distancia de evacuaci\u00f3n obligatoria",safeLabel:"Distancia de evacuaci\u00f3n segura",lpgSafeDistanceLable:"Distancia segura",fireBallDiameterLable:"Di\u00e1metro de bola de fuego",_localized:{}}});