// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/setting/nls/strings":{transparencyLabel:"Transparenz",outline:"Umrisslinie",fill:"F\u00fcllung (Farbe wird nur angewendet, wenn der Style auf Vollfarbe festgelegt ist)",style:"Style",selectOpLayerLabel:"Operationalen Layer f\u00fcr die Ergebnisse ausw\u00e4hlen",selectDefaultMeasurementLabel:"Standardmesseinheit ausw\u00e4hlen",helpIconTooltip:"Die Liste der operationalen Layer wird mit Layern der aktuellen Webkarte, die einen Polygon-Geometrietyp aufweisen, gef\u00fcllt.",
lineStyles:{esriSLSDash:"Strich",esriSLSDashDot:"Strich-Punkt",esriSLSDashDotDot:"Strich-Punkt-Punkt",esriSLSDot:"Punkt",esriSLSLongDash:"Langer Strich",esriSLSLongDashDot:"Langer Strich-Punkt",esriSLSNull:"NULL",esriSLSShortDash:"Kurzer Strich",esriSLSShortDashDot:"Kurzer Strich-Punkt",esriSLSShortDashDotDot:"Kurzer Strich-Punkt-Punkt",esriSLSShortDot:"Kurzer Punkt",esriSLSSolid:"Durchgezogen"},fillStyles:{esriSFSBackwardDiagonal:"R\u00fcckw\u00e4rts",esriSFSCross:"Kreuzf\u00f6rmig",esriSFSDiagonalCross:"Diagonal",
esriSFSForwardDiagonal:"Vorw\u00e4rts",esriSFSHorizontal:"Horizontal",esriSFSNull:"NULL",esriSFSSolid:"Vollfarbe",esriSFSVertical:"Vertikal"},threatTypeLabel:"Bedrohungstyp",generalLabel:"Allgemein",addThreatTypesLabel:"Bedrohungstyp hinzuf\u00fcgen",actions:"Aktionen",newThreatTypePopupLabel:"Neuer Bedrohungstyp",units:"Einheiten",chooseDefaultThreatLabel:"Standardm\u00e4\u00dfigen Bedrohungstyp ausw\u00e4hlen",defaultThreatTypePopUpLabel:"Standardm\u00e4\u00dfige Bedrohungstypen",editThreatLabel:"Bedrohung bearbeiten",
defaultThreatTypeIconTooltip:"Liste der standardm\u00e4\u00dfigen Bedrohungstypen",uniqueThreatTypeMsg:"Geben Sie einen eindeutigen Bedrohungstyp an. Ein Bedrohungstyp mit diesem Namen ist bereits vorhanden.",requiredMsg:"Dies ist ein Pflichtfeld",unitMeasureLabel:"Entfernungen sind in {0} angegeben",chooseDefaultThreatTypeIconLabel:"Aus Standard ausw\u00e4hlen",pipeBombLabel:"Rohrbombe",suicideBombLabel:"Selbstmordattentat",briefcaseLabel:"Aktenkoffer",carLabel:"Auto",suvVanLabel:"SUV/Van",smallDeliveryTruckLabel:"Kleiner Lieferwagen",
containerWaterTruckLabel:"Container-Lkw/Wassertankwagen",semiTrailerLabel:"Sattelschlepper",chemicalThreatLegendLabel:"Chemische Bedrohung",lpgThreatLegendLabel:"Bedrohung durch Fl\u00fcssiggas",smallLPGTank:"Kleiner Fl\u00fcssiggastank",largeLPGTank:"Gro\u00dfer Fl\u00fcssiggastank",commercialResidentialLPGTank:"Gewerblicher/privater Fl\u00fcssiggastank",smallLPGTruck:"Kleiner Fl\u00fcssiggas-Lkw",semiTankerLPG:"Fl\u00fcssiggas-Tankauflieger",threatDescriptionColLabel:"Bedrohungsbeschreibung",addThreatZoneButtonLabel:"Gefahrenzone hinzuf\u00fcgen",
zoneDescColLabel:"Zonenbeschreibung",distanceLabel:"Entfernung (${unitAbbr})",threatTypeHelp:"\x3cp\x3eStellen Sie sicher, dass die folgenden Bedingungen f\u00fcr einen Bedrohungstyp erf\u00fcllt sind:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eDer Bedrohungstyp darf nicht leer sein, und er muss eindeutig sein.\x3c/li\x3e\x3cli\x3eDie Bedrohung muss mindestens eine g\u00fcltige Zone aufweisen.\x3c/li\x3e\x3cli\x3eDie Zonenbeschreibung muss f\u00fcr eine Bedrohung eindeutig sein.\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e",
descriptionLabel:"Beschreibung",newThreatZonePopupLabel:"Neue Gefahrenzone",editThreatZonePopupLabel:"Gefahrenzone bearbeiten",uniqueZoneDescriptionMsg:"Geben Sie eine eindeutige Zonenbeschreibung an. Eine Zonenbeschreibung mit diesem Namen ist bereits vorhanden.",symbologyColLabel:"Symbolisierung",zoneDescriptionColLabel:"Zonenbeschreibung",uniqueZoneRequiredMsg:"Der Zonenname muss eindeutig sein f\u00fcr",interactive:"Interaktiv",fromCoord:"Feste Koordinate",existingFeature:"Aus vorhandenen Features",
defaultInputLocationLabel:"Standardm\u00e4\u00dfige Eingabeposition",defaultInputLayer:"Standardm\u00e4\u00dfiger Eingabe-Layer",defaultThreatType:"Standardm\u00e4\u00dfiger Bedrohungstyp",selectLabel:"Ausw\u00e4hlen",mandatoryLabel:"Entfernung f\u00fcr obligatorische Evakuierung",safeLabel:"Entfernung f\u00fcr sichere Evakuierung",lpgSafeDistanceLable:"Sichere Entfernung",fireBallDiameterLable:"Feuerball-Durchmesser",_localized:{}}});