// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/setting/nls/strings":{transparencyLabel:"Gjennomsiktighet",outline:"Omriss",fill:"Fyll (farge brukes bare n\u00e5r heldekkende er valgt som stil)",style:"Stil",selectOpLayerLabel:"Velg et operativt lag til resultater",selectDefaultMeasurementLabel:"Velg en standard m\u00e5leenhet",helpIconTooltip:"Listen med operative lag fylles med lagene fra gjeldende webkart som er av geometritypen polygon.",lineStyles:{esriSLSDash:"Strek",esriSLSDashDot:"Strek prikk",esriSLSDashDotDot:"Strek prikk prikk",
esriSLSDot:"Prikk",esriSLSLongDash:"Lang strek",esriSLSLongDashDot:"Lang strek-prikk",esriSLSNull:"Null",esriSLSShortDash:"Kort strek",esriSLSShortDashDot:"Kort strek-prikk",esriSLSShortDashDotDot:"Kort strek-prikk-prikk",esriSLSShortDot:"Kort prikk",esriSLSSolid:"Heltrukken"},fillStyles:{esriSFSBackwardDiagonal:"Bakover",esriSFSCross:"Kryss",esriSFSDiagonalCross:"Diagonal",esriSFSForwardDiagonal:"Fremover",esriSFSHorizontal:"Vannrett",esriSFSNull:"Null",esriSFSSolid:"Heltrukken",esriSFSVertical:"Loddrett"},
threatTypeLabel:"Trusseltype",generalLabel:"Generelt",addThreatTypesLabel:"Legg til trusseltype",actions:"Handlinger",newThreatTypePopupLabel:"Ny trusseltype",units:"Enheter",chooseDefaultThreatLabel:"Velg standard trusseltype",defaultThreatTypePopUpLabel:"Standard trusseltyper",editThreatLabel:"Rediger trussel",defaultThreatTypeIconTooltip:"Standard trusseltypeliste",uniqueThreatTypeMsg:"Oppgi en unik trusseltype. Det finnes allerede en trusseltype med dette navnet.",requiredMsg:"Dette feltet er obligatorisk.",
unitMeasureLabel:"Avstander er i {0}",chooseDefaultThreatTypeIconLabel:"Velg fra standard",pipeBombLabel:"R\u00f8rbombe",suicideBombLabel:"Selvmordsbombe",briefcaseLabel:"Mappe",carLabel:"Bil",suvVanLabel:"SUV/VAREBIL",smallDeliveryTruckLabel:"Liten varebil",containerWaterTruckLabel:"Container/tankbil",semiTrailerLabel:"Semitrailer",chemicalThreatLegendLabel:"Kjemisk trussel",lpgThreatLegendLabel:"LPG-trussel",smallLPGTank:"Liten LPG-tank",largeLPGTank:"Stor LPG-tank",commercialResidentialLPGTank:"LGP-tank til n\u00e6rings-/husholdningsbruk",
smallLPGTruck:"Liten LPG-lastebil",semiTankerLPG:"Semitanker-LPG",threatDescriptionColLabel:"Trusselbeskrivelse",addThreatZoneButtonLabel:"Legg til trusselsone",zoneDescColLabel:"Sonebeskrivelse",distanceLabel:"Avstand (${unitAbbr})",threatTypeHelp:"\x3cp\x3eKontroller at f\u00f8lgende betingelser oppfylles for en trusseltype:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eTrusseltype m\u00e5 oppgis, og den m\u00e5 v\u00e6re unik.\x3c/li\x3e\x3cli\x3eTrusselen m\u00e5 ha minst \u00e9n gyldig sone.\x3c/li\x3e\x3cli\x3eSonebeskrivelsen m\u00e5 v\u00e6re unik for en trussel.\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e",
descriptionLabel:"Beskrivelse",newThreatZonePopupLabel:"Ny trusselsone",editThreatZonePopupLabel:"Rediger trusselsone",uniqueZoneDescriptionMsg:"Angi en unik sonebeskrivelse. Det finnes allerede en sonebeskrivelse med dette navnet.",symbologyColLabel:"Symboler",zoneDescriptionColLabel:"Sonebeskrivelse",uniqueZoneRequiredMsg:"Sonenavnet m\u00e5 v\u00e6re unikt for",interactive:"Interaktiv",fromCoord:"Fast koordinat",existingFeature:"Fra eksisterende geoobjekter",defaultInputLocationLabel:"Standard inndatalokasjon",
defaultInputLayer:"Standard inndatalag",defaultThreatType:"Standard trusseltype",selectLabel:"Velg",mandatoryLabel:"Obligatorisk evakueringsavstand",safeLabel:"Sikker evakueringsavstand",lpgSafeDistanceLable:"Trygg avstand",fireBallDiameterLable:"Ildkulediameter",_localized:{}}});