// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/setting/nls/strings":{transparencyLabel:"L\u00e4bipaistvus",outline:"\u00c4\u00e4rejoon",fill:"T\u00e4ida (v\u00e4rv rakendatakse ainult juhul, kui valitud on pidev laad)",style:"Laad",selectOpLayerLabel:"Vali tulemuste t\u00f6\u00f6kiht",selectDefaultMeasurementLabel:"Vali vaikimisi m\u00f5\u00f5t\u00fchik",helpIconTooltip:"T\u00f6\u00f6kihtide nimekiri sisaldab kihte praeguselt veebikaardilt, mis on pol\u00fcgooni t\u00fc\u00fcpi.",lineStyles:{esriSLSDash:"Katkendlik",
esriSLSDashDot:"Katkendlik punktiga",esriSLSDashDotDot:"Katkendlik kahe punktiga",esriSLSDot:"Punktiir",esriSLSLongDash:"Pikk katkendlik kriips",esriSLSLongDashDot:"Pikk katkendlik kriips punktiga",esriSLSNull:"Null",esriSLSShortDash:"L\u00fchike katkendlik kriips",esriSLSShortDashDot:"L\u00fchike katkendlik kriips punktiga",esriSLSShortDashDotDot:"L\u00fchike katkendlik kriips kahe punktiga",esriSLSShortDot:"L\u00fchike punktiir",esriSLSSolid:"Pidev"},fillStyles:{esriSFSBackwardDiagonal:"Tagasi",
esriSFSCross:"Rist",esriSFSDiagonalCross:"Diagonaal",esriSFSForwardDiagonal:"Edasi",esriSFSHorizontal:"Horisontaalne",esriSFSNull:"Null",esriSFSSolid:"Pidev",esriSFSVertical:"Vertikaalne"},threatTypeLabel:"Ohu t\u00fc\u00fcp",generalLabel:"\u00dcldine",addThreatTypesLabel:"Lisa ohu t\u00fc\u00fcp",actions:"Toimingud",newThreatTypePopupLabel:"Uus ohu t\u00fc\u00fcp",units:"\u00dchikud",chooseDefaultThreatLabel:"Vali ohu vaiket\u00fc\u00fcp",defaultThreatTypePopUpLabel:"Ohu vaiket\u00fc\u00fcbid",editThreatLabel:"Muuda ohtu",
defaultThreatTypeIconTooltip:"Ohu vaiket\u00fc\u00fcpide loend",uniqueThreatTypeMsg:"Sisestage unikaalne ohu t\u00fc\u00fcp; selle nimega ohu t\u00fc\u00fcp on juba olemas.",requiredMsg:"See v\u00e4li on n\u00f5utav",unitMeasureLabel:"Kauguste m\u00f5\u00f5t\u00fchik on {0}",chooseDefaultThreatTypeIconLabel:"Vali vaikev\u00e4\u00e4rtusest",pipeBombLabel:"Torupomm",suicideBombLabel:"Enesetapupomm",briefcaseLabel:"Portfell",carLabel:"Auto",suvVanLabel:"SUV/VAN",smallDeliveryTruckLabel:"V\u00e4ike kaubaauto",
containerWaterTruckLabel:"Konteinerveok/Veepaagiga veok",semiTrailerLabel:"Poolhaagis",chemicalThreatLegendLabel:"Keemiline oht",lpgThreatLegendLabel:"LPG oht",smallLPGTank:"V\u00e4ike LPG paak",largeLPGTank:"Suur LPG paak",commercialResidentialLPGTank:"\u00c4riline/elamu LPG paak",smallLPGTruck:"V\u00e4ike LPG veok",semiTankerLPG:"Poolhaagisega LPG tsisternveok",threatDescriptionColLabel:"Ohu kirjeldus",addThreatZoneButtonLabel:"Lisa ohutsoon",zoneDescColLabel:"Tsooni kirjeldus",distanceLabel:"Kaugus (${unitAbbr})",
threatTypeHelp:"\x3cp\x3eVeenduge, et ohut\u00fc\u00fcp vastab j\u00e4rgmistele tingimustele:\x3cbr/\x3e\x3cul\x3e\x3cli\x3eohut\u00fc\u00fcbi v\u00e4li ei tohi olla t\u00fchi ja see peab olema kordumatu\x3c/li\x3e\x3cli\x3eohul peab olema v\u00e4hemalt \u00fcks kehtiv tsoon\x3c/li\x3e\x3cli\x3etsooni kirjeldus peab ohu jaoks olema kordumatu\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e",descriptionLabel:"Kirjeldus",newThreatZonePopupLabel:"Uus ohutsoon",editThreatZonePopupLabel:"Muuda ohutsooni",uniqueZoneDescriptionMsg:"Sisestage kordumatu ohukirjeldus. Selle nimega ohukirjeldus on juba olemas.",
symbologyColLabel:"S\u00fcmboloogia",zoneDescriptionColLabel:"Tsooni kirjeldus",uniqueZoneRequiredMsg:"Tsooni nimi peab olema kordumatu:",interactive:"Interaktiivne",fromCoord:"Fikseeritud koordinaat",existingFeature:"Olemasolevatest objektidest",defaultInputLocationLabel:"Sisendi vaikeasukoht",defaultInputLayer:"Sisendi vaikekiht",defaultThreatType:"Ohu vaiket\u00fc\u00fcp",selectLabel:"Vali",mandatoryLabel:"Kohustuslik evakueerimise kaugus",safeLabel:"Ohutu evakueerimise kaugus",lpgSafeDistanceLable:"Ohutu vahemaa",
fireBallDiameterLable:"Tulekera l\u00e4bim\u00f5\u00f5t",_localized:{}}});