// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/string dojo/Evented jimu/BaseWidget esri/request dojo/Deferred dojo/promise/all esri/geometry/projection esri/SpatialReference".split(" "),function(n,e,p,q,r,t,k,u,v,l,w){return n([t,r],{baseClass:"jimu-widget-screening-create-replica",_extractDataTaskGPService:null,errMessageString:"",responseArray:[],layerDetailsObj:{},constructor:function(b){this._extractDataTaskGPService=null;this.errMessageString="";this.responseArray=[];this.layerDetailsObj=
{};e.mixin(this,b)},startup:function(){this.responseArray=[];this.layerDetailsObj={};this._loadProjection()},_init:function(){var b,a,d;p.forEach(this.config.downloadSettings.layers,e.hitch(this,function(c){var f;if(this.downloadFeatureDetailsObj[c.id]&&0<this.downloadFeatureDetailsObj[c.id].length&&-1<c.downloadingFileOption.indexOf(this.fileFormat)&&c.allowDownload){b=c.url.split("/");a=parseInt(b.pop(),10);b=b.join("/");var h=!1;for(f in this.layerDetailsObj)f.toLowerCase()===b.toLowerCase()&&
(h=!0,b=f);h||(this.layerDetailsObj[b]={layerInstance:c,layerIndexes:[],layerDetails:{},layerNames:[],wkid:this.filterLayerObj[c.id].spatialReference.wkid});this.layerDetailsObj[b].layerIndexes.push(a);this.layerDetailsObj[b].layerNames.push(c.layerName);this.layerDetailsObj[b].layerDetails[a]={queryOption:"useFilter",useGeometry:!0,where:this.filterLayerObj[c.id].getDefinitionExpression()||""}}}));this.errMessageString="";for(d in this.layerDetailsObj)this.responseArray.push(this._exportFileUsingCreateReplica(d,
this.layerDetailsObj[d]));v(this.responseArray).then(e.hitch(this,function(){this.errMessageString?(this.errMessageString=q.substitute(this.nls.reportsTab.createReplicaFailedMessage,{layerNames:this.errMessageString}),this.emit("createReplicaComplete",this.errMessageString)):this.emit("createReplicaComplete")}))},_exportFileUsingCreateReplica:function(b,a){var d=this._removeDuplicateLayerIds(a.layerIndexes);var c=new u;if("shapefile"===this.fileFormat){var f=new w({wkid:a.wkid});f=l.project(this.aoi.geometry,
f)}else f=this.aoi.geometry;d={f:"json",replicaName:a.layerInstance.layerName,layers:d.join(),layerQueries:JSON.stringify(a.layerDetails),inSR:JSON.stringify(this.aoi.geometry.spatialReference),geometry:JSON.stringify(f),geometryType:"esriGeometryPolygon",transportType:"esriTransportTypeUrl",returnAttachments:!1,returnAttachmentsDataByUrl:!1,async:!0,syncModel:"none",dataFormat:this.fileFormat};k({url:b+"/createReplica",content:d,handleAs:"json",callbackParamName:"callback"},{usePost:!0}).then(e.hitch(this,
function(h){var x=h.statusUrl,m=setInterval(e.hitch(this,function(){k({url:x,content:{f:"json"},handleAs:"json",callbackParamName:"callback"},{usePost:!0}).then(e.hitch(this,function(g){if("Completed"===g.status)clearInterval(m),this.onRequestSucceeded(c,g);else if("CompletedWithErrors"===g.status||"Failed ImportChanges"===g.status)clearInterval(m),this.errMessageString&&(this.errMessageString+=", "),this.errMessageString+=a.layerNames.join(", "),this.onRequestFailed(c,g)}),e.hitch(this,function(g){this.errMessageString&&
(this.errMessageString+=", ");this.errMessageString+=a.layerNames.join(", ");this.onRequestFailed(c,g)}))}),1E3)}),e.hitch(this,function(h){this.errMessageString&&(this.errMessageString+=", ");this.errMessageString+=a.layerNames.join(", ");this.onRequestFailed(c,h)}));return c.promise},_removeDuplicateLayerIds:function(b){return b.filter(function(a,d,c){return d===c.indexOf(a)})},onRequestSucceeded:function(b,a){b.resolve();if(a.responseUrl)var d=a.responseUrl;else a.URL?d=a.URL:a.resultUrl&&(d=a.resultUrl);
d&&this.emit("onRequestSucceeded",d)},onRequestFailed:function(b,a){b.resolve();this.emit("onRequestFailed",a)},_loadProjection:function(){"shapefile"===this.fileFormat?l.load().then(e.hitch(this,function(){this._init()}),e.hitch(this,function(){this.loadingIndicator.hide();this.emit("showMessage",this.nls.reportsTab.errorInLoadingProjectionModule)})):this._init()}})});