// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/Color dojo/_base/array dojo/DeferredList dojo/Deferred dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/on dojo/keys jimu/utils esri/geometry/geometryEngine esri/graphic esri/Color esri/layers/FeatureLayer esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/Font esri/symbols/TextSymbol esri/tasks/query ./analysisUtils".split(" "),function(S,p,O,M,P,G,A,D,Y,T,E,F,H,K,N,U,L,Q,R,V,W,X,w){return S("ClosestInfo",
null,{featureCount:0,mapServiceLayer:!1,loading:!1,queryOnLoad:!1,incidentCount:0,constructor:function(a,c,d){this.tab=a;this.container=c;this.parent=d;this.graphicsLayer=this.incident=null;this.map=d.map;this.specialFields={};this.typeIdField="";this.types=[];this.dateFields={};this.config=d.config;this.parentNode=d.domNode;this.baseLabel=""!==a.label?a.label:a.layerTitle?a.layerTitle:a.layers},queryTabCount:function(a,c,d,e){var q=new G;this.incidentCount=a.length;var v=this.parent.config.distanceSettings[this.parent.config.distanceUnits],
h=this.parent.config.maxDistance;c=[];for(var m=0;m<a.length;m++){var g=a[m].geometry;"4326"===g.spatialReference.wkid||g.spatialReference.isWebMercator()?c.push(K.geodesicBuffer(g,h,v)):c.push(K.buffer(g,h,v))}var f=[this.tab.tabLayers[0]];this.mapServiceLayer&&1<this.tab.tabLayers.length&&(f=[this.tab.tabLayers[1]]);if(0<this.tab.tabLayers.length&&this.tab.tabLayers[0].url&&-1<this.tab.tabLayers[0].url.indexOf("MapServer"))if(this.mapServiceLayer=!0,"undefined"!==typeof this.tab.tabLayers[0].infoTemplate)if(this.summaryLayer=
this.tab.tabLayers[0],this.summaryLayer.hasOwnProperty("loaded")&&this.summaryLayer.loaded)this.summaryFields=this._getFields(this.summaryLayer),this._performQuery(a,c,d,e,f).then(function(k){q.resolve(k)});else{var b=new L(this.summaryLayer.url);b.infoTemplate=this.tab.tabLayers[0].infoTemplate;f=[b];this.tab.tabLayers=f;E(b,"load",p.hitch(this,function(){this.summaryLayer=b;this.summaryFields=this._getFields(this.summaryLayer);this._performQuery(a,c,d,e,f).then(function(k){q.resolve(k)})}))}else this.loading||
(b=new L(this.tab.tabLayers[0].url),this.loading=!0,E(b,"load",p.hitch(this,function(){this.summaryLayer=b;this.summaryFields=this._getFields(this.summaryLayer);for(var k=this.tab.tabLayers[0].url.split("MapServer/")[1],n=this.parent.map.itemInfo.itemData.operationalLayers,t=0;t<n.length;t++){var l=n[t];if(-1<this.tab.tabLayers[0].url.indexOf(l.url)&&"undefined"!==typeof l.layerObject&&l.layerObject.infoTemplates&&(l=l.layerObject.infoTemplates[k])){b.infoTemplate=l.infoTemplate;break}}f=[b];this.tab.tabLayers=
f;this.loading=!1;this._performQuery(a,c,d,e,f).then(function(r){q.resolve(r)})})));this.mapServiceLayer||this._performQuery(a,c,d,e,f).then(function(k){q.resolve(k)});return q},_performQuery:function(a,c,d,e,q){var v=new G,h=[];this.summaryGeoms=c;if(0<c.length)for(a=0;a<c.length;a++){h=c[a];var m=w.createDefArray(q,h,this.parent.opLayers,this.tab);var g=0===a?h=m:h=g.concat(m)}(new P(h)).then(p.hitch(this,function(f){for(var b=0,k=0;k<f.length;k++){var n=f[k][1];isNaN(n)?n&&n.features?0<n.features.length&&
(b+=1):n&&"undefined"!==typeof n.length&&0<n.length&&(b+=1):0<n&&(b+=1)}this.updateTabCount(b,d,e);v.resolve(b)}));return v},updateTabCount:function(a,c,d){this.featureCount=0===parseInt(a,10)?0:a;w.updateTabCount(this.featureCount,c,d,this.baseLabel,this.incidentCount)},updateForIncident:function(a,c,d,e,q,v){this.incidentCount=a.length;this.allFields="undefined"!==typeof q&&"undefined"!==typeof v?q?!0:v:!1;var h="undefined"!==typeof e,m;M.forEach(this.tab.tabLayers,p.hitch(this,function(g){h&&(m=
new G);if(g.url){var f=new L(g.url,{mode:L.MODE_ONDEMAND,infoTemplate:g.infoTemplate});E(f,"load",p.hitch(this,function(){this.tab.tabLayers=[f];h?this.processIncident(a,c,d,e).then(p.hitch(this,function(b){m.resolve(b)}),p.hitch(this,function(b){console.error(b);m.reject(b)})):this.processIncident(a,c,d,e)}))}else h?this.processIncident(a,c,d,e).then(p.hitch(this,function(b){m.resolve(b)}),p.hitch(this,function(b){console.error(b);m.reject(b)})):this.processIncident(a,c,d,e)}));if(h)return m},processIncident:function(a,
c,d,e){this.incidents=a;var q="undefined"!==typeof e;if(q)var v=new G;else this.container.innerHTML="",A.add(this.container,"loading");var h=[];e=this.parent.config.distanceSettings[this.parent.config.distanceUnits];for(var m=[],g=0;g<a.length;g++){var f=a[g].geometry;var b="4326"===f.spatialReference.wkid||f.spatialReference.isWebMercator()?K.geodesicBuffer(f,c,e):K.buffer(f,c,e);m.push({geometry:f,buffer:b})}(this.graphicsLayer=d)&&this.graphicsLayer.clear();a=[];c=this.tab.tabLayers[0];d=-1===
[null,void 0,""].indexOf(c.id)?c.id:this.tab.layers;d=w.getFilter(d,this.parent.opLayers);var k=this._getFields(c),n=w.getPopupConfiguredFields(c);for(e=0;e<m.length;e++)g=new X,g.returnGeometry=!0,g.outSpatialReference=this.parent.map.spatialReference,g.geometry=m[e].buffer,g.where=d,g.outFields=["*"],"undefined"!==typeof c.queryFeatures&&a.push(c.queryFeatures(g));(new P(a)).then(p.hitch(this,function(t){for(var l=0;l<t.length;l++)if(t[l][0]){var r=t[l][1].features,x=[],I=m[l].geometry;if(r&&0<
r.length){for(var B=0;B<r.length;B++){var y=new N(r[B].toJson()),u=w.getDistance(I,y.geometry,this.parent.config.distanceUnits),z={DISTANCE:u};M.forEach(k,p.hitch(this,function(C){z[C]=y.attributes[C]}));this.config.hasOwnProperty("exportFieldsOptionForCSV")&&"allFields"===this.config.exportFieldsOptionForCSV||this.config.hasOwnProperty("csvAllFields")&&(!0===this.config.csvAllFields||"true"===this.config.csvAllFields)?y.attributes.DISTANCE=u:(this.config.hasOwnProperty("exportFieldsOptionForCSV")&&
"popUpFields"===this.config.exportFieldsOptionForCSV&&!this.allFields&&(z={DISTANCE:u},M.forEach(n,p.hitch(this,function(C){z[C]=y.attributes[C]}))),y.attributes=z);x.push(y)}x.sort(w.compareDistance);h.push(x[0])}}else t[l][1]&&t[l][1].message&&console.log(t[l][1].message);h.sort(w.compareDistance);q?this._processResults(h,!0).then(p.hitch(this,function(C){v.resolve(C)})):this._processResults(h)}),p.hitch(this,function(t){console.error(t);v.reject(t)}));if(q)return v},_processResults:function(a,
c){var d=a&&0<a.length;if(d&&"point"!==a[0].geometry.type)for(var e=a.length-1;0<=e;e--)"undefined"===typeof a[e].geometry.getExtent()&&a.splice(e,1);if(c)var q=new G;else if(this.container.innerHTML="",A.remove(this.container,"loading"),d){var v=D.create("div",{"class":"SAT_tabPanelContent"},this.container);e=D.create("div",{},v);A.add(e,"SATcolExport");A.add(e,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder");var h=D.create("div",{title:this.parent.nls.downloadCSV,tabindex:"0",role:"button",
"aria-label":this.parent.nls.downloadCSV,"class":"closestDownLoadCSVButton"},e);H.initFirstFocusNode(this.parentNode,h);A.add(h,"btnExport");A.add(h,this.parent.lightTheme?"lightThemeBackground":"darkThemeBackground");E(h,"click",p.hitch(this,this._exportToCSV,a));E(h,"keydown",p.hitch(this,function(J){if(!J.shiftKey||J.keyCode!==F.TAB)if(J.keyCode===F.ENTER||J.keyCode===F.SPACE)this._exportToCSV(a,J),setTimeout(function(){h.focus()},500)}));h.focus()}e=this.parent.nls[this.parent.config.distanceUnits];
var m=[];if(d)for(var g=0;g<a.length;g++){var f=g+1,b=a[g],k=b.geometry,n=k;"point"!==k.type&&(n=k.getExtent().getCenter());k=b.attributes;var t;"point"===this.incidents[0].geometry.type&&(t=Math.round(100*k.DISTANCE)/100+" "+e+" ("+this.parent.nls.approximate+")");var l="",r=0,x=[];if("undefined"!==typeof this.displayFields)for(var I=0;I<this.displayFields.length;I++){var B=this.displayFields[I],y;a:for(y in k)if("DISTANCE"!==y&&3>r&&B.expression===y){var u=w.getFieldValue(y,k[y],this.specialFields,
this.dateFields,"longMonthDayYear",this.typeIdField,this.types,this.layerObject&&this.layerObject.renderer?this.layerObject:this.layerDefinition,k,B);u="undefined"!==typeof u&&null!==u?H.stripHTML(u.toString()):"";var z="undefined"!==typeof B.label&&""!==B.label?B.label:void 0,C=b._layer&&b._layer.fields?b._layer.fields:this.tab.tabLayers&&this.tab.tabLayers[0]?this.tab.tabLayers[0].fields:void 0;C&&"undefined"===typeof z&&(C=w.getField(C,y))&&(z=C.alias);if("undefined"===typeof z||z in[""," ",null,
void 0])z=y;w.isURL(u)?u='\x3ca href\x3d"'+u+'" target\x3d"_blank" style\x3d"color: inherit;"\x3e'+z+"\x3c/a\x3e":w.isEmail(u)&&(u='\x3ca href\x3d"mailto:'+u+'" style\x3d"color: inherit;"\x3e'+z+"\x3c/a\x3e");l+=B.validLabel?("undefined"!==typeof B.label&&""!==B.label?z+" ":"")+u+"\x3cbr/\x3e":u+"\x3cbr/\x3e";r+=1;x.push({value:u,label:z});break a}}m.push(x);c||(b=D.create("div",{},v),A.add(b,"SATcolRec"),A.add(b,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder"),r=D.create("div",{},b),
A.add(r,"SATcolRecBar"),x=D.create("div",{innerHTML:f,tabindex:"0",role:"button","aria-label":this.parent.nls.zoomToFeature+" "+f},r),A.add(x,"SATcolRecNum"),T.set(x,"backgroundColor",this.parent.config.activeColor),E(x,"click",p.hitch(this,this._zoomToLocation,n,null)),E(x,"keydown",p.hitch(this,this._zoomToLocation,n,!0)),H.initLastFocusNode(this.parentNode,x),t&&(x=D.create("div",{innerHTML:t},r),A.add(x,"SATcolDistance")),this.parent.config.enableRouting&&(r=D.create("div",{"class":"directionsButton",
title:this.parent.nls.get_directions,tabindex:"0","aria-label":this.parent.nls.get_directions,role:"button"},r),A.add(r,"SATcolDir"),E(r,"click",p.hitch(this,this._routeToIncident,n,null)),E(r,"keydown",p.hitch(this,this._routeToIncident,n,!0)),H.initLastFocusNode(this.parentNode,r)),l=D.create("div",{"class":"SATcolWrap",innerHTML:l},b),A.add(l,"SATcolInfo"),l=new R(R.STYLE_SOLID,new O.fromRgb(this.parent.config.activeMapGraphicColor),1),l=new Q(Q.STYLE_CIRCLE,24,l,new O.fromRgb(this.parent.config.activeMapGraphicColor)),
b=new V,b.family="Arial",b.size="12px",f=new W(f,b,new U(this.parent.config.fontColor)),f.setOffset(0,-4),this.graphicsLayer.add(new N(n,l,k)),this.graphicsLayer.add(new N(n,f,k)))}if(c&&d)return q.resolve({graphics:a,analysisResults:m,context:this}),q},_exportToCSV:function(a,c,d,e){if(this.parent.config.hasOwnProperty("exportFieldsOptionForCSV"))var q=this.parent.config.exportFieldsOptionForCSV;else this.parent.config.hasOwnProperty("csvAllFields")&&(q=this.parent.config.csvAllFields);a=w.exportToCSV(a,
c,d,e,{type:"closest",baseLabel:this.baseLabel,csvAllFields:q,layer:this.tab.tabLayers[0],opLayers:this.parent.opLayers,nlsValue:this.parent.nls.closest,nlsCount:this.parent.nls.count});this.summaryLayer=a.summaryLayer;return a.details},_getFields:function(a){this.layerDefinition=H.getFeatureLayerDefinition(a);this.layerObject=a;a=w.getFields(a,this.tab,this.allFields,this.parent);this.dateFields=a.dateFields;this.specialFields=a.specialFields;this.typeIdField=a.typeIdField;this.types=a.types;this.displayFields=
w.getDisplayFields(this.tab);return a.fields},_zoomToLocation:function(a,c,d){d.shiftKey&&d.keyCode===F.TAB?(d.stopPropagation(),d.cancelBubble=!0):c&&d.keyCode!==F.ENTER&&d.keyCode!==F.SPACE||this.parent.zoomToLocation(a)},_routeToIncident:function(a,c,d){c&&d.keyCode!==F.ENTER&&d.keyCode!==F.SPACE||this.parent.routeToIncident(a)}})});