// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/Color dojo/_base/array dojo/DeferredList dojo/Deferred dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/on dojo/query dojo/keys esri/graphic esri/Color esri/layers/FeatureLayer esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/Font esri/symbols/TextSymbol esri/tasks/query esri/geometry/geometryEngine jimu/utils ./analysisUtils".split(" "),function(V,k,Q,K,R,N,z,H,ca,W,I,da,J,S,X,P,T,U,Y,Z,aa,M,O,
t){return V("ProximityInfo",null,{featureCount:0,mapServiceLayer:!1,loading:!1,queryOnLoad:!1,incidentCount:0,constructor:function(a,e,d){this.tab=a;this.container=e;this.parent=d;this.graphicsLayer=this.incident=null;this.specialFields={};this.typeIdField="";this.types=[];this.dateFields={};this.config=d.config;this.parentNode=d.domNode;this.baseLabel=""!==a.label?a.label:a.layerTitle?a.layerTitle:a.layers},queryTabCount:function(a,e,d,h){var n=new N;this.incidentCount=a.length;var f=[this.tab.tabLayers[0]];
this.mapServiceLayer&&1<this.tab.tabLayers.length&&(f=[this.tab.tabLayers[1]]);if(0<this.tab.tabLayers.length&&this.tab.tabLayers[0].url&&-1<this.tab.tabLayers[0].url.indexOf("MapServer"))if(this.mapServiceLayer=!0,"undefined"!==typeof this.tab.tabLayers[0].infoTemplate)if(this.summaryLayer=this.tab.tabLayers[0],this.summaryLayer.hasOwnProperty("loaded")&&this.summaryLayer.loaded)this.summaryFields=this._getFields(this.summaryLayer),this._performQuery(a,e,d,h,f).then(function(b){n.resolve(b)});else{var c=
new P(this.summaryLayer.url);c.infoTemplate=this.tab.tabLayers[0].infoTemplate;f=[c];this.tab.tabLayers=f;I(c,"load",k.hitch(this,function(){this.summaryLayer=c;this.summaryFields=this._getFields(this.summaryLayer);this._performQuery(a,e,d,h,f).then(function(b){n.resolve(b)})}))}else this.loading||(c=new P(this.tab.tabLayers[0].url),this.loading=!0,I(c,"load",k.hitch(this,function(){this.summaryLayer=c;this.summaryFields=this._getFields(this.summaryLayer);for(var b=this.tab.tabLayers[0].url.split("MapServer/")[1],
l=this.parent.map.itemInfo.itemData.operationalLayers,p=0;p<l.length;p++){var g=l[p];if(-1<this.tab.tabLayers[0].url.indexOf(g.url)&&"undefined"!==typeof g.layerObject&&g.layerObject.infoTemplates&&(g=g.layerObject.infoTemplates[b])){c.infoTemplate=g.infoTemplate;break}}this.tab.tabLayers=[c];this.loading=!1;this._performQuery(a,e,d,h,this.tab.tabLayers).then(function(q){n.resolve(q)})})));this.mapServiceLayer||this._performQuery(a,e,d,h,f).then(function(b){n.resolve(b)});return n},_performQuery:function(a,
e,d,h,n){var f=new N,c=[],b;0<e.length?b=t.getGeoms(e):0<a.length&&(b=t.getGeoms(a));this.summaryGeoms=b;if(0<b.length)for(a=0;a<b.length;a++){c=b[a];e=t.createDefArray(n,c,this.parent.opLayers,this.tab);var l=0===a?c=e:c=l.concat(e)}(new R(c)).then(k.hitch(this,function(p){for(var g=0,q=0;q<p.length;q++){var m=p[q][1];isNaN(m)?m&&m.features?g+=m.features.length:m&&"undefined"!==typeof m.length&&(g+=m.length):g+=m}this.updateTabCount(g,d,h);f.resolve(g)}));return f},updateTabCount:function(a,e,d){this.featureCount=
a;t.updateTabCount(this.featureCount,e,d,this.baseLabel,this.incidentCount)},updateForIncident:function(a,e,d,h,n,f){this.incidentCount=a.length;this.allFields="undefined"!==typeof n&&"undefined"!==typeof f?n?!0:f:!1;var c="undefined"!==typeof h,b;K.forEach(this.tab.tabLayers,k.hitch(this,function(l){c&&(b=new N);if(l.url){var p=new P(l.url,{mode:P.MODE_ONDEMAND,infoTemplate:l.infoTemplate});I(p,"load",k.hitch(this,function(){this.tab.tabLayers=[p];c?this.processIncident(a,e,d,h,n).then(k.hitch(this,
function(g){b.resolve(g)}),k.hitch(this,function(g){console.error(g);b.reject(g)})):this.processIncident(a,e,d,h,n)}))}else c?this.processIncident(a,e,d,h,n).then(k.hitch(this,function(g){b.resolve(g)}),k.hitch(this,function(g){console.error(g);b.reject(g)})):this.processIncident(a,e,d,h,n)}));if(c)return b},processIncident:function(a,e,d,h,n){this.incidents=a;var f=[];if(0===e.length)for(var c=0;c<a.length;c++){var b=a[c];b=b.geometry?b.geometry:b;"polygon"===b.type?(e.push(b),f.push({geometry:b,
buffer:b})):f.push({geometry:void 0,buffer:void 0})}else for(c=0;c<a.length;c++){b=a[c];var l=e[c].geometry?e[c].geometry:e[c];b=b.geometry?b.geometry:b;f.push({geometry:b,buffer:l})}if(0!==e.length){for(a=0;a<f.length;a++)if(e=f[a].buffer,"undefined"!==typeof e)for(b=0;b<f.length;b++)if(b!==a&&(c=f[b].buffer,"undefined"!==typeof c&&M.overlaps(e,c))){f[a].buffer=M.difference(e,c);f[b].buffer=M.difference(c,e);c=M.union(c,e);c=M.difference(c,f[a].buffer);c=M.difference(c,f[b].buffer);if(Array.isArray(f[a].geometry)){if(Array.isArray(f[b].geometry))for(l=
0;l<f[b].geometry.length;l++)f[a].geometry.push(f[b].geometry[l]);else f[a].geometry.push(f[b].geometry);l=f[a].geometry}else if(l=[],l.push(f[a].geometry),Array.isArray(f[b].geometry))for(var p=0;p<f[b].geometry.length;p++)l.push(f[b].geometry[p]);else l.push(f[b].geometry);f.push({geometry:l,buffer:c})}var g="undefined"!==typeof h;if(g)var q=new N;else this.container.innerHTML="",z.add(this.container,"loading");var m=[];this.graphicsLayer=d;d=this.tab.tabLayers[0];var x=this._getFields(d),E=t.getPopupConfiguredFields(d);
h=-1===[null,void 0,""].indexOf(d.id)?d.id:this.tab.layers;h=t.getFilter(h,this.parent.opLayers);a=[];for(e=0;e<f.length;e++)b=new aa,b.returnGeometry=!0,b.outSpatialReference=this.parent.map.spatialReference,b.geometry=f[e].buffer,b.where=h,b.outFields=["*"],"undefined"!==typeof d.queryFeatures&&a.push(d.queryFeatures(b));(new R(a)).then(k.hitch(this,function(A){for(var y=0;y<A.length;y++){var F=A[y][1];if(F&&F.features){F=F.features;for(var B=f[y].geometry,D=0;D<F.length;D++){var r=F[D],u=r.geometry;
if(Array.isArray(B)){for(var G,v=0;v<B.length;v++){var C=t.getDistance(B[v],u,this.parent.config.distanceUnits);if("undefined"===typeof G||C<G)G=C}u=G;var w={DISTANCE:G}}else u=t.getDistance(B,u,this.parent.config.distanceUnits),w={DISTANCE:u};K.forEach(x,k.hitch(this,function(L){w[L]=r.attributes[L]}));this.config.hasOwnProperty("exportFieldsOptionForCSV")&&"allFields"===this.config.exportFieldsOptionForCSV||this.config.hasOwnProperty("csvAllFields")&&(!0===this.config.csvAllFields||"true"===this.config.csvAllFields)?
r.attributes.DISTANCE=u:(this.config.hasOwnProperty("exportFieldsOptionForCSV")&&"popUpFields"===this.config.exportFieldsOptionForCSV&&!n&&(w={DISTANCE:u},K.forEach(E,k.hitch(this,function(L){w[L]=r.attributes[L]}))),r.attributes=w);m.push(r)}}}m.sort(t.compareDistance);if(g){var ba={graphics:m,analysisResults:m.length,context:this};this._processResults(m,!0).then(k.hitch(this,function(L){q.resolve(k.mixin(ba,L))}))}else this._processResults(m)}),k.hitch(this,function(A){console.error(A);q.reject(A)}));
if(g)return q}},_processResults:function(a,e){var d=a&&0<a.length;if(d&&"point"!==a[0].geometry.type)for(var h=a.length-1;0<=h;h--)"undefined"===typeof a[h].geometry.getExtent()&&a.splice(h,1);if(e)var n=new N;else if(this.container.innerHTML="",z.remove(this.container,"loading"),this.graphicsLayer.clear(),d){var f=H.create("div",{"class":"SAT_tabPanelContent"},this.container);h=H.create("div",{},f);z.add(h,"SATcolExport");z.add(h,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder");var c=
H.create("div",{title:this.parent.nls.downloadCSV,tabindex:"0",role:"button","aria-label":this.parent.nls.downloadCSV,"class":"proximityDownLoadCSVButton"},h);z.add(c,"btnExport");z.add(c,this.parent.lightTheme?"lightThemeBackground":"darkThemeBackground");c.focus();O.initFirstFocusNode(this.parentNode,c);I(c,"click",k.hitch(this,this._exportToCSV,a));I(c,"keydown",k.hitch(this,function(v){if(!v.shiftKey||v.keyCode!==J.TAB)if(v.keyCode===J.ENTER||v.keyCode===J.SPACE)this._exportToCSV(a,v),setTimeout(function(){c.focus()},
500)}))}h=this.parent.nls[this.parent.config.distanceUnits];if("undefined"!==typeof this.tab.advStat&&"undefined"!==typeof this.tab.advStat.stats&&"undefined"!==typeof this.tab.advStat.stats.outFields)var b=this.tab.advStat.stats.outFields;else b=[],0<this.tab.tabLayers.length&&K.forEach(this.tab.tabLayers,k.hitch(this,function(v){"undefined"!==typeof v.popupInfo?K.forEach(v.popupInfo.fieldInfos,k.hitch(this,function(C){if(C.visible){var w={value:0};w.expression=C.fieldName;w.label=C.label;b.push(w)}})):
v.infoTemplate?K.forEach(v.infoTemplate.info.fieldInfos,k.hitch(this,function(C){if(C.visible){var w={value:0};w.expression=C.fieldName;w.label=C.label;b.push(w)}})):K.forEach((v.layerObject?v.layerObject:v).fields,k.hitch(this,function(C){var w={value:0};w.expression=C.name;w.label=C.alias;b.push(w)}))}));var l=[];if(d)for(d=0;d<a.length;d++){var p=d+1,g=a[d],q=g.geometry,m=q;"point"!==q.type&&(m=q.getExtent().getCenter());q=g.attributes;var x=t.getDistanceLabel(q.DISTANCE,h,this.parent.nls.approximate),
E="",A=0,y=[];if("undefined"!==typeof b){for(var F=0;F<b.length;F++){var B=b[F],D;for(D in q)if("DISTANCE"!==D&&3>A&&B.expression===D){var r=t.getFieldValue(D,q[D],this.specialFields,this.dateFields,"longMonthDayYear",this.typeIdField,this.types,this.layerObject&&this.layerObject.renderer?this.layerObject:this.layerDefinition,q,B);r="undefined"!==typeof r&&null!==r?O.stripHTML(r.toString()):"";var u="undefined"!==typeof B.label&&""!==B.label?B.label:void 0,G=g._layer&&g._layer.fields?g._layer.fields:
this.tab.tabLayers&&this.tab.tabLayers[0]?this.tab.tabLayers[0].fields:void 0;G&&"undefined"===typeof u&&(G=t.getField(G,D))&&(u=G.alias);if("undefined"===typeof u||u in[""," ",null,void 0])u=D;t.isURL(r)?r='\x3ca href\x3d"'+r+'" target\x3d"_blank" style\x3d"color: inherit;"\x3e'+u+"\x3c/a\x3e":t.isEmail(r)&&(r='\x3ca href\x3d"mailto:'+r+'" style\x3d"color: inherit;"\x3e'+u+"\x3c/a\x3e");E+=B.validLabel?("undefined"!==typeof B.label&&""!==B.label?u+" ":"")+r+"\x3cbr/\x3e":r+"\x3cbr/\x3e";A+=1;y.push({label:u,
value:r})}}y.push({label:this.parent.nls.distance,value:x});0<y.length&&l.push(y)}e||(g=H.create("div",{},f),z.add(g,"SATcolRec"),z.add(g,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder"),A=H.create("div",{},g),z.add(A,"SATcolRecBar"),y=H.create("div",{innerHTML:p,tabindex:"0",role:"button","aria-label":this.parent.nls.zoomToFeature+" "+p,isLastElement:a.length-1===d},A),z.add(y,"SATcolRecNum"),a.length-1===d&&O.initLastFocusNode(this.parentNode,y),W.set(y,"backgroundColor",this.parent.config.activeColor),
I(y,"click",k.hitch(this,this._zoomToLocation,m,null)),I(y,"keydown",k.hitch(this,this._zoomToLocation,m,!0)),"point"===this.incidents[0].geometry.type&&(x=H.create("div",{innerHTML:x},A),z.add(x,"SATcolDistance")),this.parent.config.enableRouting&&(x=H.create("div",{"class":"directionsButton",title:this.parent.nls.get_directions,tabindex:"0","aria-label":this.parent.nls.get_directions,role:"button"},A),z.add(x,"SATcolDir"),I(x,"click",k.hitch(this,this._routeToIncident,m,null)),I(x,"keydown",k.hitch(this,
this._routeToIncident,m,!0)),O.initLastFocusNode(this.parentNode,x)),E=H.create("div",{"class":"SATcolWrap",innerHTML:E},g),z.add(E,"SATcolInfo"),E=new U(U.STYLE_SOLID,new Q.fromString(this.parent.config.activeMapGraphicColor),1),E=new T(T.STYLE_CIRCLE,24,E,new Q.fromString(this.parent.config.activeMapGraphicColor)),x=new Y,x.family="Arial",x.size="12px",p=new Z(p,x,new X(this.parent.lightTheme?"#111111":this.parent.config.fontColor)),p.setOffset(0,-4),this.graphicsLayer.add(new S(m,E,q)),this.graphicsLayer.add(new S(m,
p,q)))}if(e)return n.resolve({reportResults:l}),n},_exportToCSV:function(a,e,d,h){if(this.parent.config.hasOwnProperty("exportFieldsOptionForCSV"))var n=this.parent.config.exportFieldsOptionForCSV;else this.parent.config.hasOwnProperty("csvAllFields")&&(n=this.parent.config.csvAllFields);a=t.exportToCSV(a,e,d,h,{type:"proximity",baseLabel:this.baseLabel,csvAllFields:n,layer:this.tab.tabLayers[0],opLayers:this.parent.opLayers,nlsValue:this.parent.nls.proximity,nlsCount:this.parent.nls.count,unit:this.parent.nls[this.parent.config.distanceUnits],
approximateLabel:this.parent.nls.approximate});this.summaryLayer=a.summaryLayer;return a.details},_getFields:function(a){this.layerDefinition=O.getFeatureLayerDefinition(a);this.layerObject=a;a=t.getFields(a,this.tab,this.allFields,this.parent);this.dateFields=a.dateFields;this.specialFields=a.specialFields;this.typeIdField=a.typeIdField;this.types=a.types;this.displayFields=t.getDisplayFields(this.tab);return a.fields},_zoomToLocation:function(a,e,d){d.shiftKey&&d.keyCode===J.TAB||e&&d.keyCode!==
J.ENTER&&d.keyCode!==J.SPACE||this.parent.zoomToLocation(a)},_routeToIncident:function(a,e,d){e&&d.keyCode!==J.ENTER&&d.keyCode!==J.SPACE||this.parent.routeToIncident(a)}})});