// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Grassetto",copy:"Copia",cut:"Taglia","delete":"Elimina",indent:"Rientro",insertHorizontalRule:"Righello orizzontale",insertOrderedList:"Elenco numerato",insertUnorderedList:"Elenco puntato",italic:"Corsivo",justifyCenter:"Allinea al centro",justifyFull:"Giustifica",justifyLeft:"Allinea a sinistra",justifyRight:"Allinea a destra",outdent:"Annulla rientro",paste:"Incolla",redo:"Ripristina",removeFormat:"Rimuovi formato",selectAll:"Seleziona tutto",strikethrough:"Barrato",
subscript:"Pedice",superscript:"Apice",underline:"Sottolinea",undo:"Annulla",unlink:"Rimuovi collegamento",createLink:"Crea collegamento",toggleDir:"Attiva/Disattiva direzione",insertImage:"Inserisci immagine",insertTable:"Inserisci/Modifica tabella",toggleTableBorder:"Attiva/Disattiva bordo tabella",deleteTable:"Elimina tabella",tableProp:"Propriet\u00e0 tabella",htmlToggle:"Origine HTML",foreColor:"Colore primo piano",hiliteColor:"Colore sfondo",plainFormatBlock:"Stile paragrafo",formatBlock:"Stile paragrafo",
fontSize:"Dimensione carattere",fontName:"Nome carattere",tabIndent:"Rientro tabulazione",fullScreen:"Attiva/Disattiva schermo intero",viewSource:"Visualizza origine HTML",print:"Stampa",newPage:"Nuova pagina",systemShortcut:'La azione "${0}" \u00e8 disponibile solo nel browser tramite un tasto di scelta rapida. Utilizzare ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Dimensione",fontName:"Carattere",formatBlock:"Formato",serif:"serif","sans-serif":"sans-serif",
monospace:"spaziatura fissa",cursive:"corsivo",fantasy:"fantasy",noFormat:"Nessuna",p:"Paragrafo",h1:"Intestazione",h2:"Sottointestazione",h3:"Sottointestazione secondaria",pre:"Preformattato",1:"piccolissimo",2:"molto piccolo",3:"piccolo",4:"medio",5:"grande",6:"molto grande",7:"grandissimo",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Anteprima",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Trova:",findTooltip:"Immettere il testo da ricercare",replaceLabel:"Sostituisci con:",
replaceTooltip:"Immettere il testo con cui sostituire",findReplace:"Trova e sostituisci",matchCase:"Corrispondenza maiuscolo/minuscolo",matchCaseTooltip:"Corrispondenza maiuscolo/minuscolo",backwards:"Indietro",backwardsTooltip:"Ricercare il testo all'indietro",replaceAllButton:"Sostituisci tutti",replaceAllButtonTooltip:"Sostituisci tutto il testo",findButton:"Trova",findButtonTooltip:"Trova il testo",replaceButton:"Sostituisci",replaceButtonTooltip:"Sostituisci il testo",replaceDialogText:"Sostituite ${0} ricorrenze.",
eofDialogText:"Ultime ${0} ricorrenze",eofDialogTextFind:"trovato",eofDialogTextReplace:"sostituito",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Incolla da Word",instructions:"Incollare i contenuti da Word nella seguente casella di testo. Quando si \u00e8 deciso quali contenuti inserire, fare clic sul pulsante incolla. Per interrompere l'inserimento del testo premere il pulsante annulla.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Inserisci ancoraggio",
title:"Propriet\u00e0 ancoraggio",anchor:"Nome:",text:"Descrizione:",set:"Imposta",cancel:"Annulla",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/BatchAttributeEditor/setting/nls/strings":{page1:{selectToolHeader:"Scegliere un metodo per selezionare record per la modalit\u00e0 di aggiornamento batch.",selectToolDesc:"Il widget supporta 3 metodi per generare un insieme selezionato di record da aggiornare. Si pu\u00f2 scegliere solo uno dei metodi. Se hai bisogno di pi\u00f9 di uno di questi metodi, crea una nuova istanza del widget.",
selectByShape:"Seleziona per area",shapeTypeSelector:"Scegli quali strumenti permettere di selezionare le feature sulla mappa",shapeType:{point:"Puntuale",line:"Linea",polyline:"Polilineare",freehandPolyline:"Polilinea a mano libera",extent:"Estensione",polygon:"Poligonale",freehandPolygon:"Poligono a mano libera"},freehandPolygon:"Poligono a mano libera",selectBySpatQuery:"Seleziona per feature",selectByAttQuery:"Selezionare per feature e valori di attributi condivisi",selectByQuery:"Seleziona per interrogazione",
toolNotSelected:"Scegli un metodo di selezione",noDrawToolSelected:"Scegli almeno uno strumento di disegno"},page2:{layersToolHeader:"Selezionare i layer da aggiornare e le opzioni degli strumenti di selezione, se disponibili.",layersToolDesc:"Il tipo di selezione che hai scelto dalla scheda precedente sar\u00e0 usato per selezionare e aggiornare le caratteristiche da un insieme di layer elencati di seguito. Se selezioni pi\u00f9 di un layer da aggiornare, solo i campi modificabili comuni saranno disponibili per l'aggiornamento. A seconda del tipo di selezione, saranno richieste opzioni aggiuntive.",
layerTable:{colUpdate:"Aggiorna",colLabel:"Layer",colSelectByLayer:"Seleziona per layer",colSelectByField:"Campo interrogazione",colhighlightSymbol:"Evidenzia simbolo",queryFieldDefaultOption:"- Seleziona -"},toggleLayers:"Attiva/disattiva la visibilit\u00e0 dei layer all'apertura e alla chiusura",noEditableLayers:"Nessun layer modificabile",noLayersSelected:"Selezionare uno o pi\u00f9 layer prima di continuare."},page3:{commonFieldsHeader:"Selezionare i campi per la modalit\u00e0 di aggiornamento batch.",
commonFieldsDesc:"Solo i campi comuni modificabili saranno mostrati qui sotto. Seleziona i campi che vuoi aggiornare. Se i campi che condividono lo stesso nome di campo si trovano in diversi layer, ma hanno domini diversi, solo un dominio pu\u00f2 essere usato.",noCommonFields:"Nessun campo in comune",fieldTable:{colEdit:"Modificabile",colName:"Nome",colAlias:"Alias",colAction:"Azioni"}},tabs:{selection:"Definire tipo di selezione",layers:"Definire layer da aggiornare",fields:"Definire campi da aggiornare"},
errorOnOk:"Compila tutti i parametri prima di salvare la configurazione",next:"Seguente",back:"Indietro",save:"Salva simbolo",cancel:"Annulla",ok:"OK",symbolPopup:"Selezione simbolo",editHeaderText:"Testo da visualizzare nella parte superiore del widget",widgetIntroSelectByArea:"Utilizzare uno degli strumenti sottostanti per creare un insieme selezionato di feature da aggiornare. Se la riga \u00e8 \x3cfont class\x3d'maxRecordInIntro'\x3eevidenziata\x3c/font\x3e, \u00e8 stato superato il numero massimo di record.",
widgetIntroSelectByFeature:"Utilizzare lo strumento sottostante per selezionare una feature dal layer \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e. Questa feature verr\u00e0 utilizzata per selezionare e aggiornare tutte le feature che intersecano. Se la riga \u00e8 \x3cfont class\x3d'maxRecordInIntro'\x3eevidenziata\x3c/font\x3e, \u00e8 stato superato il numero massimo di record.",widgetIntroSelectByFeatureQuery:"Utilizzare lo strumento sottostante per selezionare una feature da \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e. Questo attributo \x3cfont class\x3d'layerInIntro'\x3e${1}\x3c/font\x3e della feature verr\u00e0 utilizzato per interrogare i layer sottostanti e aggiornare le feature risultanti. Se la riga \u00e8 \x3cfont class\x3d'maxRecordInIntro'\x3eevidenziata\x3c/font\x3e, \u00e8 stato superato il numero massimo di record.",
widgetIntroSelectByQuery:"Immettere un valore per creare un set di selezione. Se la riga \u00e8 \x3cfont class\x3d'maxRecordInIntro'\x3eevidenziata\x3c/font\x3e, \u00e8 stato superato il numero massimo di record.",_localized:{}}});