// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Podebljaj",copy:"Kopiraj",cut:"Izre\u017ei","delete":"Izbri\u0161i",indent:"Uvuci",insertHorizontalRule:"Vodoravno ravnalo",insertOrderedList:"Numerirani popis",insertUnorderedList:"Popis s grafi\u010dkim oznakama",italic:"Kurziv",justifyCenter:"Centriraj",justifyFull:"Poravnaj",justifyLeft:"Poravnaj lijevo",justifyRight:"Poravnaj desno",outdent:"Izvuci",paste:"Zalijepi",redo:"Ponovno napravi",removeFormat:"Ukloni oblikovanje",selectAll:"Izaberi sve",strikethrough:"Precrtaj",
subscript:"Indeks",superscript:"Superskript",underline:"Podcrtaj",undo:"Poni\u0161ti",unlink:"Ukloni vezu",createLink:"Kreiraj vezu",toggleDir:"Prebaci smjer",insertImage:"Umetni sliku",insertTable:"Umetni/Uredi tablicu",toggleTableBorder:"Prebaci rub tablice",deleteTable:"Izbri\u0161i tablicu",tableProp:"Svojstvo tablice",htmlToggle:"HTML izvor",foreColor:"Boja prednjeg plana",hiliteColor:"Boja pozadine",plainFormatBlock:"Stil odlomka",formatBlock:"Stil odlomka",fontSize:"Veli\u010dina fonta",fontName:"Ime fonta",
tabIndent:"Tabulator uvla\u010denja",fullScreen:"Prebaci na potpun ekran",viewSource:"Pogledaj HTML izvor",print:"Ispis",newPage:"Nova stranica",systemShortcut:'"${0}" akcija je dostupna jedino u va\u0161em pregledniku upotrebom pre\u010dice tipkovnice. Koristite ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Veli\u010dina",fontName:"Font",formatBlock:"Oblikovanje",serif:"serif","sans-serif":"sans-serif",monospace:"jednaki razmak",cursive:"rukopisni",
fantasy:"fantastika",noFormat:"Nijedan",p:"Odlomak",h1:"Naslov",h2:"Podnaslov",h3:"Pod-podnaslov",pre:"Prethodno formatirano",1:"vrlo vrlo malo",2:"vrlo malo",3:"malo",4:"srednje",5:"veliko",6:"vrlo veliko",7:"vrlo vrlo veliko",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Pregled",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Tra\u017ei:",findTooltip:"Unesi tekst pretrage",replaceLabel:"Zamijeni s:",replaceTooltip:"Unesi tekst za zamjenu",findReplace:"Tra\u017ei i zamijeni",
matchCase:"Usporedi velika/mala slova",matchCaseTooltip:"Usporedi velika/mala slova",backwards:"Natrag",backwardsTooltip:"Pretra\u017ei tekst u prethodnim koracima",replaceAllButton:"Zamijeni sve",replaceAllButtonTooltip:"Zamijeni cijeli tekst",findButton:"Tra\u017ei",findButtonTooltip:"Tra\u017ei tekst",replaceButton:"Zamijeni",replaceButtonTooltip:"Zamijeni tekst",replaceDialogText:"Zamijenjeno ${0} pojavljivanja.",eofDialogText:"Zadnje pojavljivanje ${0}",eofDialogTextFind:"na\u0111eno",eofDialogTextReplace:"zamijenjeno",
_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Zalijepi iz Worda",instructions:"Zalijepite sadr\u017eaj iz Worda u donji tekstni okvir. Kad ste zadovoljni sa sadr\u017eajem za umetanje, pritisnite tipku Zalijepi.  Za prekid umetanja teksta, pritisnite tipku Opoziv.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Umetni sidro",title:"Svojstva sidra",anchor:"Naziv:",text:"Opis:",set:"Postavi",cancel:"Opoziv",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Dugi citat",
_localized:{}},"widgets/BatchAttributeEditor/setting/nls/strings":{page1:{selectToolHeader:"Izaberite metodu odabira zapisa za skupno a\u017euriranje.",selectToolDesc:"Widget podr\u017eava 3 metode za generiranje odabranog skupa zapisa za a\u017euriranje. Mo\u017eete odabrati jednu metodu. Ako trebate vi\u0161e od jedne metode, stvorite novu instancu widgeta.",selectByShape:"Odaberi prema podru\u010dju",shapeTypeSelector:"Odaberite koje alate \u0107ete omogu\u0107iti za odabir geoobjekata na karti",
shapeType:{point:"To\u010dka",line:"Linija",polyline:"Polilinija",freehandPolyline:"Prostoru\u010dna polilinija",extent:"Obuhvat",polygon:"Poligon",freehandPolygon:"Prostoru\u010dni poligon"},freehandPolygon:"Prostoru\u010dni poligon",selectBySpatQuery:"Odaberi prema geoobjektu",selectByAttQuery:"Odabir prema vrijednostima geoobjekta i dijeljenih atributa",selectByQuery:"Odaberi prema upitu",toolNotSelected:"Odaberite metodu za odabir",noDrawToolSelected:"Odaberite bar jedan alat za crtanje"},page2:{layersToolHeader:"Odaberite slojeve za a\u017euriranje i opcije alata za odabir ako ih ima.",
layersToolDesc:"Vrsta odabira koju ste odabrali na prethodnoj kartici bit \u0107e kori\u0161tena za odabir i a\u017euriranje geoobjekata iz skupa slojeva navedenih ispod. Ako ozna\u010dite vi\u0161e od jednog sloja za a\u017euriranje, samo zajedni\u010dka polja koja se mogu urediti \u0107e biti dostupna za a\u017euriranje. Ovisno o vrsti odabira, dodatne opcije \u0107e biti potrebne.",layerTable:{colUpdate:"A\u017euriraj",colLabel:"Sloj",colSelectByLayer:"Odaberi prema sloju",colSelectByField:"Polje za upit",
colhighlightSymbol:"Istakni simbol",queryFieldDefaultOption:"-- Odaberite --"},toggleLayers:"Prebacujte vidljivost slojeva izme\u0111u otvoreno i zatvoreno",noEditableLayers:"Nema slojeva koji se mogu ure\u0111ivati",noLayersSelected:"Odaberite jedan ili vi\u0161e slojeva prije nastavka."},page3:{commonFieldsHeader:"Odaberite polja za skupno a\u017euriranje.",commonFieldsDesc:"Samo zajedni\u010dka polja koja se mogu urediti \u0107e biti prikazana ispod. Odaberite polja koja \u017eelite a\u017eurirati. Ako polja koja dijele isti naziv polja postoje na vi\u0161e slojeva, ali imaju druge domene, samo se jedna domena mo\u017ee koristiti.",
noCommonFields:"Nema zajedni\u010dkih polja",fieldTable:{colEdit:"Mo\u017ee se ure\u0111ivati",colName:"Naziv",colAlias:"Alias",colAction:"Radnje"}},tabs:{selection:"Definiraj vrstu odabira",layers:"Definiraj sloj(eve) za a\u017euriranje",fields:"Definiraj polje/a za a\u017euriranje"},errorOnOk:"Ispunite sve parametre prije spremanja konfiguracije",next:"Sljede\u0107e",back:"Natrag",save:"Spremi simbol",cancel:"Odustani",ok:"U redu",symbolPopup:"Bira\u010d simbola",editHeaderText:"Tekst koji \u0107e se prikazati na vrhu widgeta",
widgetIntroSelectByArea:"Upotrijebite jedan od alata u nastavku da biste stvorili odabrani skup geoobjekata za a\u017euriranje.  Ako je redak \x3cfont class\x3d'maxRecordInIntro'\x3eistaknut\x3c/font\x3e, prema\u0161en je maksimalni broj zapisa.",widgetIntroSelectByFeature:"Upotrijebite alat u nastavku za odabir geoobjekta sa \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e sloja. Ovaj geoobjekt upotrebljavat \u0107e se za odabir i a\u017euriranje svih geoobjekata koji se presijecaju. Ako je redak \x3cfont class\x3d'maxRecordInIntro'\x3eistaknut\x3c/font\x3e, prema\u0161en je maksimalni broj zapisa.",
widgetIntroSelectByFeatureQuery:"Upotrijebite alat u nastavku za odabir geoobjekta sa sloja \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e .  Atribut \x3cfont class\x3d'layerInIntro'\x3e${1}\x3c/font\x3e ovog geoobjekta upotrebljavat \u0107e se za ispitivanje slojeva u nastavku i a\u017euriranje dobivenih geoobjekata.  Ako je redak \x3cfont class\x3d'maxRecordInIntro'\x3eistaknut\x3c/font\x3e, prema\u0161en je maksimalni broj zapisa.",widgetIntroSelectByQuery:"Unesite vrijednost da biste stvorili skup odabira.  Ako je redak \x3cfont class\x3d'maxRecordInIntro'\x3eistaknut\x3c/font\x3e, prema\u0161en je maksimalni broj zapisa.",
_localized:{}}});