// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Vet",copy:"Kopi\u00ebren",cut:"Knippen","delete":"Wissen",indent:"Inspringen",insertHorizontalRule:"Horizontale liniaal",insertOrderedList:"Genummerde lijst",insertUnorderedList:"Lijst met opsommingstekens",italic:"Cursief",justifyCenter:"Centreren",justifyFull:"Uitvullen",justifyLeft:"Links uitlijnen",justifyRight:"Rechts uitlijnen",outdent:"Uitspringen",paste:"Plakken",redo:"Opnieuw",removeFormat:"Opmaak verwijderen",selectAll:"Alles selecteren",strikethrough:"Doorhalen",
subscript:"Subscript",superscript:"Superscript",underline:"Onderstrepen",undo:"Ongedaan maken",unlink:"Link verwijderen",createLink:"Link maken",toggleDir:"Schrijfrichting wijzigen",insertImage:"Afbeelding invoegen",insertTable:"Tabel invoegen/bewerken",toggleTableBorder:"Tabelkader wijzigen",deleteTable:"Tabel wissen",tableProp:"Tabeleigenschap",htmlToggle:"HTML-bron",foreColor:"Voorgrondkleur",hiliteColor:"Achtergrondkleur",plainFormatBlock:"Alineastijl",formatBlock:"Alineastijl",fontSize:"Lettergrootte",
fontName:"Lettertype",tabIndent:"Inspringen",fullScreen:"Volledig scherm in-/uitschakelen",viewSource:"HTML-bron bekijken",print:"Afdrukken",newPage:"Nieuwe pagina",systemShortcut:'De actie "${0}" is alleen beschikbaar in uw browser via een sneltoetscombinatie. Gebruik ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Grootte",fontName:"Lettertype",formatBlock:"Opmaak",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursief",
fantasy:"fantasy",noFormat:"Geen",p:"Alinea",h1:"Kop",h2:"Subkop",h3:"Sub-subkop",pre:"Vooraf opgemaakt",1:"xx-klein",2:"x-klein",3:"klein",4:"gemiddeld",5:"groot",6:"x-groot",7:"xx-groot",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Preview",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Zoeken:",findTooltip:"Geef de zoektekst op",replaceLabel:"Vervangen door:",replaceTooltip:"Geef de vervangende tekst op",findReplace:"Zoeken en vervangen",matchCase:"Hoofdlettergevoelig",
matchCaseTooltip:"Hoofdlettergevoelig",backwards:"Terug",backwardsTooltip:"Terugwaarts naar tekst zoeken",replaceAllButton:"Alle vervangen",replaceAllButtonTooltip:"Gehele tekst vervangen",findButton:"Zoeken:",findButtonTooltip:"Tekst zoeken",replaceButton:"Vervangen",replaceButtonTooltip:"Tekst vervangen",replaceDialogText:"${0} vervangingen.",eofDialogText:"Laatste positie ${0}",eofDialogTextFind:"gevonden",eofDialogTextReplace:"vervangen",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Plakken vanuit Word",
instructions:"Plak de content vanuit Word in het tekstvak hieronder. Klik als u klaar bent op de knop Plakken. Kies Annuleren als u de invoeging van tekst wilt afbreken.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Anker invoegen",title:"Ankereigenschappen",anchor:"Naam:",text:"Beschrijving:",set:"Instellen",cancel:"Annuleren",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/BatchAttributeEditor/setting/nls/strings":{page1:{selectToolHeader:"Kies een methode om records te selecteren voor batchupdate.",
selectToolDesc:"De widget ondersteunt 3 methoden om een geselecteerde reeks gegevens te genereren die moeten worden bijgewerkt. U kunt maar \u00e9\u00e9n van de methoden selecteren. Als u meer dan \u00e9\u00e9n van deze methoden nodig hebt, maak dan een nieuw exemplaar van de widget.",selectByShape:"Selecteren op oppervlakte",shapeTypeSelector:"Kies met welke tools u de objecten wilt selecteren op de kaart",shapeType:{point:"Punt",line:"Lijn",polyline:"Polylijn",freehandPolyline:"Polylijn in vrije stijl",
extent:"Extent",polygon:"Vlak",freehandPolygon:"Vlak in vrije stijl"},freehandPolygon:"Veelhoek in vrije stijl",selectBySpatQuery:"Selecteren op object",selectByAttQuery:"Selecteren op basis van feature en gedeelde attribuutwaarden",selectByQuery:"Selecteren op query",toolNotSelected:"Selecteer een selectiemethode",noDrawToolSelected:"Kies ten minste \u00e9\u00e9n tekentool"},page2:{layersToolHeader:"Selecteer de te actualiseren lagen en de selectiehulpmiddelenopties, indien van toepassing.",layersToolDesc:"Het Selectietype dat u hebt gekozen van het vorige tabblad wordt gebruikt om de objecten te selecteren en bij te werken uit een set lagen dat hieronder wordt weergegeven. Indien u meer dan \u00e9\u00e9n laag aanvinkt om bij te werken, zullen alleen de gemeenschappelijke bewerkbare velden beschikbaar zijn voor actualisering. Afhankelijk van het Selectietype zijn er extra opties vereist.",
layerTable:{colUpdate:"Actualiseren",colLabel:"Kaartlaag",colSelectByLayer:"Selecteren volgens laag",colSelectByField:"Queryveld",colhighlightSymbol:"Symbool markeren",queryFieldDefaultOption:"- Selecteren -"},toggleLayers:"Zichtbaarheid lagen wisselen bij openen en sluiten",noEditableLayers:"Geen bewerkbare lagen",noLayersSelected:"Selecteer \u00e9\u00e9n of meer lagen alvorens door te gaan."},page3:{commonFieldsHeader:"Selecteer de velden voor batchupdate.",commonFieldsDesc:"Alleen de algemeen bewerkbare velden worden hieronder weergegeven. Selecteer de velden die u wilt bijwerken. Als velden die dezelfde veldnaam delen op verschillende lagen voorkomen maar met verschillende domeinen, dan kan er maar \u00e9\u00e9n domein gebruikt worden.",
noCommonFields:"Geen gemeenschappelijke velden",fieldTable:{colEdit:"Bewerkbaar",colName:"Naam",colAlias:"Alias",colAction:"Acties"}},tabs:{selection:"Selectietype bepalen",layers:"La(a)g(en) bepalen voor actualisering",fields:"Veld(en) bepalen voor actualisering"},errorOnOk:"Vul alle parameters in alvorens de configuratie op te slaan",next:"Volgende",back:"Vorige",save:"Symbool opslaan",cancel:"Annuleren",ok:"OK",symbolPopup:"Symbolenkiezer",editHeaderText:"Tekst om weer te geven aan de bovenkant van de widget",
widgetIntroSelectByArea:"Gebruik een van de tools hieronder om een selectie van objecten te maken om bij te werken. Als de rij is \x3cfont class\x3d'maxRecordInIntro'\x3egemarkeerd\x3c/font\x3e, dan is het maximum aantal gegevens overschreden.",widgetIntroSelectByFeature:"Gebruik de tool hieronder om een object te kiezen uit kaartlaag \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e. Dit object wordt gebruikt om alle overeenkomende objecten te selecteren en bij te werken. Als de rij is \x3cfont class\x3d'maxRecordInIntro'\x3egemarkeerd\x3c/font\x3e, dan is het maximum aantal gegevens overschreden.",
widgetIntroSelectByFeatureQuery:"Gebruik de tool hieronder om een object te kiezen uit \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e. Het \x3cfont class\x3d'layerInIntro'\x3e${1}\x3c/font\x3e-attribuut van dit object wordt gebruikt om de lagen eronder te queryen en de resulterende objecten te updaten. Als de rij is \x3cfont class\x3d'maxRecordInIntro'\x3egemarkeerd\x3c/font\x3e, dan is het maximum aantal gegevens overschreden.",widgetIntroSelectByQuery:"Voer een waarde in om een geselecteerde set te cre\u00ebren. Als de rij is \x3cfont class\x3d'maxRecordInIntro'\x3egemarkeerd\x3c/font\x3e, dan is het maximum aantal gegevens overschreden.",
_localized:{}}});