// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Negrito",copy:"Copiar",cut:"Recortar","delete":"Excluir",indent:"Recuar",insertHorizontalRule:"R\u00e9gua Horizontal",insertOrderedList:"Lista Numerada",insertUnorderedList:"Lista com Marcadores",italic:"It\u00e1lico",justifyCenter:"Alinhar pelo Centro",justifyFull:"Justificar",justifyLeft:"Alinhar pela Esquerda",justifyRight:"Alinhar pela Direita",outdent:"N\u00e3o-chanfrado",paste:"Colar",redo:"Refazer",removeFormat:"Remover Formato",selectAll:"Selecionar Todos",
strikethrough:"Tachado",subscript:"Subscrito",superscript:"Sobrescrito",underline:"Sublinhado",undo:"Desfazer",unlink:"Remover Link",createLink:"Criar Link",toggleDir:"Comutar Dire\u00e7\u00e3o",insertImage:"Inserir Imagem",insertTable:"Inserir/Editar Tabela",toggleTableBorder:"Alternar Moldura da Tabela",deleteTable:"Excluir Tabela",tableProp:"Propriedade da Tabela",htmlToggle:"Origem HTML",foreColor:"Cor do Primeiro Plano",hiliteColor:"Cor de segundo plano",plainFormatBlock:"Estilo de Par\u00e1grafo",
formatBlock:"Estilo de Par\u00e1grafo",fontSize:"Tamanho da Fonte",fontName:"Nome da Fonte",tabIndent:"Recuo de Guia",fullScreen:"Comutar Tela Cheia",viewSource:"Visualizar Origem HTML",print:"Impress\u00e3o",newPage:"Nova P\u00e1gina",systemShortcut:'A a\u00e7\u00e3o "${0}" est\u00e1 dispon\u00edvel em seu navegador apenas usando um atalho do teclado. Use ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dojo/cldr/nls/islamic":{"months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),
"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),
"days-format-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"days-format-narrow":"SMTWTFS".split(""),"days-format-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"days-format-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"days-standAlone-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"days-standAlone-narrow":"SMTWTFS".split(""),"days-standAlone-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"days-standAlone-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"quarters-format-abbr":["Q1","Q2","Q3","Q4"],
"quarters-format-narrow":["1","2","3","4"],"quarters-format-wide":["Q1","Q2","Q3","Q4"],"quarters-standAlone-abbr":["Q1","Q2","Q3","Q4"],"quarters-standAlone-narrow":["1","2","3","4"],"quarters-standAlone-wide":["Q1","Q2","Q3","Q4"],"dayPeriods-format-abbr-am":"AM","dayPeriods-format-abbr-pm":"PM","dayPeriods-format-narrow-am":"AM","dayPeriods-format-narrow-pm":"PM","dayPeriods-format-wide-am":"AM","dayPeriods-format-wide-pm":"PM","dayPeriods-standAlone-abbr-am":"AM","dayPeriods-standAlone-abbr-pm":"PM",
"dayPeriods-standAlone-narrow-am":"AM","dayPeriods-standAlone-narrow-pm":"PM","dayPeriods-standAlone-wide-am":"AM","dayPeriods-standAlone-wide-pm":"PM",eraNames:["AH"],eraAbbr:["AH"],eraNarrow:["AH"],"dateFormat-full":"G y MMMM d, EEEE","dateFormat-long":"G y MMMM d","dateFormat-medium":"G y MMM d","dateFormat-short":"GGGGG y-MM-dd","timeFormat-full":"HH:mm:ss zzzz","timeFormat-long":"HH:mm:ss z","timeFormat-medium":"HH:mm:ss","timeFormat-short":"HH:mm","dateTimeFormat-full":"{1} {0}","dateTimeFormat-long":"{1} {0}",
"dateTimeFormat-medium":"{1} {0}","dateTimeFormat-short":"{1} {0}","dateFormatItem-Bh":"h B","dateFormatItem-Bhm":"h:mm B","dateFormatItem-Bhms":"h:mm:ss B","dateFormatItem-d":"d","dateFormatItem-E":"ccc","dateFormatItem-EBhm":"E h:mm B","dateFormatItem-EBhms":"E h:mm:ss B","dateFormatItem-Ed":"d, E","dateFormatItem-Ehm":"E h:mm a","dateFormatItem-EHm":"E HH:mm","dateFormatItem-Ehms":"E h:mm:ss a","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Gy":"G y","dateFormatItem-GyMMM":"G y MMM","dateFormatItem-GyMMMd":"G y MMM d",
"dateFormatItem-GyMMMEd":"G y MMM d, E","dateFormatItem-h":"h a","dateFormatItem-H":"HH","dateFormatItem-hm":"h:mm a","dateFormatItem-Hm":"HH:mm","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-M":"L","dateFormatItem-Md":"MM-dd","dateFormatItem-MEd":"MM-dd, E","dateFormatItem-MMM":"LLL","dateFormatItem-MMMd":"MMM d","dateFormatItem-MMMEd":"MMM d, E","dateFormatItem-MMMMd":"MMMM d","dateFormatItem-ms":"mm:ss","dateFormatItem-y":"G y","dateFormatItem-yyyy":"G y","dateFormatItem-yyyyM":"GGGGG y-MM",
"dateFormatItem-yyyyMd":"GGGGG y-MM-dd","dateFormatItem-yyyyMEd":"GGGGG y-MM-dd, E","dateFormatItem-yyyyMMM":"G y MMM","dateFormatItem-yyyyMMMd":"G y MMM d","dateFormatItem-yyyyMMMEd":"G y MMM d, E","dateFormatItem-yyyyMMMM":"G y MMMM","dateFormatItem-yyyyQQQ":"G y QQQ","dateFormatItem-yyyyQQQQ":"G y QQQQ","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateTimeFormats-appendItem-Era":"{1} {0}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})",
"dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","dateTimeFormats-appendItem-Year":"{1} {0}","field-era":"Era","field-era-short":"Era","field-era-narrow":"Era","field-year":"Year","field-year-relative+-1":"last year","field-year-relative+0":"this year",
"field-year-relative+1":"next year","field-year-short":"Year","field-year-short-relative+-1":"last year","field-year-short-relative+0":"this year","field-year-short-relative+1":"next year","field-year-narrow":"Year","field-year-narrow-relative+-1":"last year","field-year-narrow-relative+0":"this year","field-year-narrow-relative+1":"next year","field-quarter":"Quarter","field-quarter-relative+-1":"last quarter","field-quarter-relative+0":"this quarter","field-quarter-relative+1":"next quarter","field-quarter-short":"Quarter",
"field-quarter-short-relative+-1":"last quarter","field-quarter-short-relative+0":"this quarter","field-quarter-short-relative+1":"next quarter","field-quarter-narrow":"Quarter","field-quarter-narrow-relative+-1":"last quarter","field-quarter-narrow-relative+0":"this quarter","field-quarter-narrow-relative+1":"next quarter","field-month":"Month","field-month-relative+-1":"last month","field-month-relative+0":"this month","field-month-relative+1":"next month","field-month-short":"Month","field-month-short-relative+-1":"last month",
"field-month-short-relative+0":"this month","field-month-short-relative+1":"next month","field-month-narrow":"Month","field-month-narrow-relative+-1":"last month","field-month-narrow-relative+0":"this month","field-month-narrow-relative+1":"next month","field-week":"Week","field-week-relative+-1":"last week","field-week-relative+0":"this week","field-week-relative+1":"next week","field-week-short":"Week","field-week-short-relative+-1":"last week","field-week-short-relative+0":"this week","field-week-short-relative+1":"next week",
"field-week-narrow":"Week","field-week-narrow-relative+-1":"last week","field-week-narrow-relative+0":"this week","field-week-narrow-relative+1":"next week","field-weekOfMonth":"Week Of Month","field-weekOfMonth-short":"Week Of Month","field-weekOfMonth-narrow":"Week Of Month","field-day":"Day","field-day-relative+-1":"yesterday","field-day-relative+0":"today","field-day-relative+1":"tomorrow","field-day-short":"Day","field-day-short-relative+-1":"yesterday","field-day-short-relative+0":"today","field-day-short-relative+1":"tomorrow",
"field-day-narrow":"Day","field-day-narrow-relative+-1":"yesterday","field-day-narrow-relative+0":"today","field-day-narrow-relative+1":"tomorrow","field-dayOfYear":"Day Of Year","field-dayOfYear-short":"Day Of Year","field-dayOfYear-narrow":"Day Of Year","field-weekday":"Day of the Week","field-weekday-short":"Day of the Week","field-weekday-narrow":"Day of the Week","field-weekdayOfMonth":"Weekday Of Month","field-weekdayOfMonth-short":"Weekday Of Month","field-weekdayOfMonth-narrow":"Weekday Of Month",
"field-sun-relative+-1":"last Sunday","field-sun-relative+0":"this Sunday","field-sun-relative+1":"next Sunday","field-sun-short-relative+-1":"last Sunday","field-sun-short-relative+0":"this Sunday","field-sun-short-relative+1":"next Sunday","field-sun-narrow-relative+-1":"last Sunday","field-sun-narrow-relative+0":"this Sunday","field-sun-narrow-relative+1":"next Sunday","field-mon-relative+-1":"last Monday","field-mon-relative+0":"this Monday","field-mon-relative+1":"next Monday","field-mon-short-relative+-1":"last Monday",
"field-mon-short-relative+0":"this Monday","field-mon-short-relative+1":"next Monday","field-mon-narrow-relative+-1":"last Monday","field-mon-narrow-relative+0":"this Monday","field-mon-narrow-relative+1":"next Monday","field-tue-relative+-1":"last Tuesday","field-tue-relative+0":"this Tuesday","field-tue-relative+1":"next Tuesday","field-tue-short-relative+-1":"last Tuesday","field-tue-short-relative+0":"this Tuesday","field-tue-short-relative+1":"next Tuesday","field-tue-narrow-relative+-1":"last Tuesday",
"field-tue-narrow-relative+0":"this Tuesday","field-tue-narrow-relative+1":"next Tuesday","field-wed-relative+-1":"last Wednesday","field-wed-relative+0":"this Wednesday","field-wed-relative+1":"next Wednesday","field-wed-short-relative+-1":"last Wednesday","field-wed-short-relative+0":"this Wednesday","field-wed-short-relative+1":"next Wednesday","field-wed-narrow-relative+-1":"last Wednesday","field-wed-narrow-relative+0":"this Wednesday","field-wed-narrow-relative+1":"next Wednesday","field-thu-relative+-1":"last Thursday",
"field-thu-relative+0":"this Thursday","field-thu-relative+1":"next Thursday","field-thu-short-relative+-1":"last Thursday","field-thu-short-relative+0":"this Thursday","field-thu-short-relative+1":"next Thursday","field-thu-narrow-relative+-1":"last Thursday","field-thu-narrow-relative+0":"this Thursday","field-thu-narrow-relative+1":"next Thursday","field-fri-relative+-1":"last Friday","field-fri-relative+0":"this Friday","field-fri-relative+1":"next Friday","field-fri-short-relative+-1":"last Friday",
"field-fri-short-relative+0":"this Friday","field-fri-short-relative+1":"next Friday","field-fri-narrow-relative+-1":"last Friday","field-fri-narrow-relative+0":"this Friday","field-fri-narrow-relative+1":"next Friday","field-sat-relative+-1":"last Saturday","field-sat-relative+0":"this Saturday","field-sat-relative+1":"next Saturday","field-sat-short-relative+-1":"last Saturday","field-sat-short-relative+0":"this Saturday","field-sat-short-relative+1":"next Saturday","field-sat-narrow-relative+-1":"last Saturday",
"field-sat-narrow-relative+0":"this Saturday","field-sat-narrow-relative+1":"next Saturday","field-dayperiod-short":"Dayperiod","field-dayperiod":"Dayperiod","field-dayperiod-narrow":"Dayperiod","field-hour":"Hour","field-hour-relative+0":"this hour","field-hour-short":"Hour","field-hour-short-relative+0":"this hour","field-hour-narrow":"Hour","field-hour-narrow-relative+0":"this hour","field-minute":"Minute","field-minute-relative+0":"this minute","field-minute-short":"Minute","field-minute-short-relative+0":"this minute",
"field-minute-narrow":"Minute","field-minute-narrow-relative+0":"this minute","field-second":"Second","field-second-relative+0":"now","field-second-short":"Second","field-second-short-relative+0":"now","field-second-narrow":"Second","field-second-narrow-relative+0":"now","field-zone":"Zone","field-zone-short":"Zone","field-zone-narrow":"Zone",_localized:{}},"widgets/Edit/nls/strings":{_widgetLabel:"Editar",_featureAction_Edit:"Editar",title:"Selecione um modelo para criar fei\u00e7\u00f5es",pressStr:"Pressionar ",
ctrlStr:" CTRL ",snapStr:" para habilitar o ajuste",close:"Fechar",featureLayers:"Camadas de fei\u00e7\u00e3o",searchTemplates:"Pesquisar modelos",noAvailableTempaltes:"Nenhum modelo dispon\u00edvel",noCanCreateLayerAreCurrentlyVisible:"Nenhuma camada edit\u00e1vel est\u00e1 atualmente vis\u00edvel.",layersAreInvisibleOrOutOfScaleRange:"As camadas est\u00e3o invis\u00edveis ou fora da faixa de escala.",relatedTables:"Tabelas relacionadas:",relatedRecords:"Registros relacionados:",noRelatedRecotds:"Nenhum registro relacionado foi encontrado.",
startToDraw:"Clique para come\u00e7ar a desenhar",startToAddPoint:"Clique para adicionar um ponto",editRelatedFeature:"Editando fei\u00e7\u00e3o relacionada",duplicateValueWarning:" N\u00e3o \u00e9 poss\u00edvel inserir valor duplicado em ${fieldName} de ${tableName}. O valor duplicado \u00e9: ${value}",_localized:{}}});