// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/GriddedReferenceGraphic/templates/ColorPickerEditor.html":'\x3cdiv class\x3d"colorPickerEditor"\x3e\r\n  \x3cdiv class\x3d"colorPicker" data-dojo-attach-point\x3d"colorPicker"\x3e\x3c/div\x3e\r\n  \x3cspan class\x3d"trans"\x3e${nls.transparency}\x3c/span\x3e\r\n  \x3cdiv class\x3d"sliderbar" data-dojo-attach-point\x3d"sliderBar"\x3e\x3c/div\x3e\r\n  \x3cinput type\x3d"text" data-dojo-type\x3d"dijit/form/NumberSpinner" value\x3d"0"\r\n         data-dojo-attach-point\x3d"spinner" data-dojo-props\x3d"smallDelta:10,intermediateChanges:true,constraints: {min:0,max:100}"\x3e\r\n  \x3cspan class\x3d"percent-display"\x3e%\x3c/span\x3e\r\n\x3c/div\x3e\r\n\r\n'}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/Color dojo/dom-attr dojo/on dojo/query dojo/_base/html dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!../templates/ColorPickerEditor.html dijit/form/HorizontalSlider jimu/dijit/ColorPickerPopup dijit/form/NumberSpinner".split(" "),function(n,g,p,d,h,q,r,t,u,v,w,x,y){return n([t,u,v],{_defaultColor:"#485566",templateString:w,nls:null,postCreate:function(){this.colorPicker=new y({color:this._defaultColor,width:this._defaultWidth,
tabindex:"0",role:"button"},this.colorPicker);this.colorPicker.startup();this.slider=new x({name:"slider",value:100,minimum:0,maximum:100,discreteValues:101,intermediateChanges:!0,showButtons:!1,style:"width:140px;display: inline-block;"},this.sliderBar);this.slider.startup();this.inherited(arguments)},startup:function(){this._setAriaLabelForEditorNodes();this.own(h(this.slider,"change",g.hitch(this,function(a){!1===this._isSameVal()&&this.spinner.setValue(a)})));this.own(h(this.spinner,"change",
g.hitch(this,function(a){!1===this._isSameVal()&&100>=a&&this.slider.setValue(a)})));this._stylePolyfill();this.inherited(arguments)},_setAriaLabelForEditorNodes:function(){var a="",b="";this.nls.gridSettings&&(a="Fill"===this.typeOfColorPicker?this.nls.gridSettings.cellFill:this.nls.gridSettings.cellOutline,b=this.nls.gridSettings.colorPicker);d.set(this.colorPicker.domNode,"aria-label",a+" "+b);d.set(this.slider,"aria-label",a+" "+this.nls.transparency);d.set(this.spinner,"aria-label",a+" "+this.nls.transparency)},
_isSameVal:function(){return this.slider.getValue()===this.spinner.getValue()},getValues:function(){var a=null,b=null;(b=this.colorPicker.getColor())&&b.toHex&&(a=b.toHex());b=this.spinner.getValue()/100;return{color:a,transparency:b}},setValues:function(a){if("object"===typeof a||"string"===typeof a)this.colorPicker.setColor(new p(a.color)),a.transparency="undefined"===typeof a.transparency?0:100*a.transparency,this.slider.setValue(a.transparency),this.spinner.setValue(a.transparency)},validateSpinner:function(){var a=
!0;this.spinner.isValid()||(this._shake(this.spinner.domNode,16),this.spinner.focus(),a=!1);return a},_stylePolyfill:function(){var a=q(".dijitSliderLeftBumper",this.domNode)[0];a&&a.parentNode&&r.setStyle(a.parentNode,"background-color","#24b5cc")},_shake:function(a,b){function k(){if(15>e){a.style.transform="translate(0px, 0px)";b-=z;var c=l(-b,b),f=l(-b,b);a.style.transform="translate("+c+"px, "+f+"px)";e+=1;requestAnimationFrame(k)}15<=e&&(a.style.transform="translate(0, 0)",m._shakingElements.splice(m._shakingElements.indexOf(a),
1))}var e=1,z=b/15,l=function(c,f){return Math.floor(Math.random()*(f-c+1))+c};this._shakingElements||(this._shakingElements=[]);if(-1===this._shakingElements.indexOf(a)){this._shakingElements.push(a);var m=this;k()}}})});