// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dijit/_WidgetBase dojo/Evented dojo/_base/lang dojo/_base/array esri/dijit/Search esri/tasks/locator esri/layers/FeatureLayer esri/dijit/PopupTemplate jimu/utils dojo/dom-construct jimu/LayerInfos/LayerInfos ./searchSourceUtils dojo/when dojo/Deferred dojo/promise/all dojo/on dojo/keys".split(" "),function(u,v,w,d,m,x,y,z,A,h,r,B,p,C,t,D,q,E){return u([v,w],{config:null,map:null,searchOptions:null,layerInfosObj:null,_urlParams:{},constructor:function(b){d.mixin(this,b)},
postCreate:function(){this._urlParams={}},startup:function(){this.inherited(arguments);B.getInstance(this.map,this.map.itemInfo).then(d.hitch(this,function(b){this.layerInfosObj=b;this.own(this.layerInfosObj.on("layerInfosFilterChanged",d.hitch(this,this.onLayerInfosFilterChanged)));p.setMap(this.map);p.setLayerInfosObj(this.layerInfosObj);p.setAppConfig(this.appConfig);C(p.getConfigInfo(this.config.searchSourceSettings)).then(d.hitch(this,function(a){this.config.searchSourceSettings||(this.config.searchSourceSettings=
a);return D(this._convertConfig(a)).then(function(c){return m.filter(c,function(e){return e})})})).then(d.hitch(this,function(a){this.domNode&&this._init(a)}))}))},_convertConfig:function(b){return m.map(b.sources,d.hitch(this,function(a){var c=new t;if(a&&a.url&&"locator"===a.type){var e={locator:new y(a.url||""),outFields:["*"],singleLineFieldName:a.singleLineFieldName||"",name:h.stripHTML(a.name||""),placeholder:h.stripHTML(a.placeholder||""),countryCode:a.countryCode||"",maxSuggestions:a.maxSuggestions,
maxResults:a.maxResults||6,zoomScale:a.zoomScale||5E4,useMapExtent:!!a.searchInCurrentMapExtent};a.enableLocalSearch&&(e.localSearchOptions={minScale:a.localSearchMinScale,distance:a.localSearchDistance});c.resolve(e)}else a&&a.url&&"query"===a.type?(e=new z(a.url||null,{outFields:["*"]}),this.own(q(e,"load",d.hitch(this,function(f){var k=f.layer;var l=null;a.searchFields&&0<a.searchFields.length?l=a.searchFields:(l=[],m.forEach(k.fields,function(n){"esriFieldTypeOID"!==n.type&&n.name!==k.objectIdField&&
"esriFieldTypeGeometry"!==n.type&&l.push(n.name)}));var g={featureLayer:k,outFields:["*"],searchFields:l,displayField:a.displayField||"",exactMatch:!!a.exactMatch,name:h.stripHTML(a.name||""),placeholder:h.stripHTML(a.placeholder||""),maxSuggestions:a.maxSuggestions||6,maxResults:a.maxResults||6,zoomScale:a.zoomScale||5E4,infoTemplate:void 0,useMapExtent:!!a.searchInCurrentMapExtent,_featureLayerId:a.layerId};this._getInfoTemplate(k,a).then(d.hitch(this,function(n){g.infoTemplate=n;c.resolve(g)}),
d.hitch(this,function(){c.resolve(g)}));g._featureLayerId&&(f=this.layerInfosObj.getLayerInfoById(g._featureLayerId),k.setDefinitionExpression(f.getFilter()));c.resolve(g)}))),this.own(q(e,"error",function(){c.resolve(null)}))):c.resolve(null);return c}))},_getInfoTemplate:function(b,a){var c=new t,e=this.layerInfosObj.getLayerInfoById(a.layerId),f;if(e)c=e.loadInfoTemplate();else{var k=[];m.filter(b.fields,function(l){var g=l.name.toLowerCase();0>g.indexOf("shape")&&0>g.indexOf("objectid")&&0>g.indexOf("globalid")&&
0>g.indexOf("perimeter")&&k.push(l.name)});(b=h.getDefaultPopupInfo(b,a.name+": {"+a.displayField+"}",k))&&(f=new A(b));c.resolve(f)}return c},_init:function(b){var a=1===b.length?0:"all";b={map:this.map,addLayersFromMap:!1,autoNavigate:!1,autoComplete:!0,minCharacters:0,searchDelay:100,enableInfoWindow:!0,enableHighlight:this.config.searchSourceSettings.showInfoWindowOnSelect,showInfoWindowOnSelect:this.config.searchSourceSettings.showInfoWindowOnSelect,allPlaceholder:h.stripHTML(this.config.searchSourceSettings.allPlaceholder),
sources:b,activeSourceIndex:a};d.mixin(b,this.searchOptions);this._urlParams=this._getUrlParams();this.search=new x(b,r.create("div",{"class":"searchControl"}));r.place(this.search.domNode,this.domNode);this.own(this.search.on("load",d.hitch(this,this._load)));this.own(this.search.on("select-result",d.hitch(this,this._selectResult)));this.own(this.search.on("clear-search",d.hitch(this,this._clear)));this.own(this.search.on("search-results",d.hitch(this,this._results)));this.own(this.search.on("suggest-results",
d.hitch(this,this._results)));this.own(q(this.search.inputNode,"keyup",d.hitch(this,function(c){c.keyCode===E.ENTER&&this.emit("init-attribute-search")})));this.own(q(this.search.submitNode,"click",d.hitch(this,function(){this.emit("init-attribute-search")})));this.search.startup()},_getUrlParams:function(){var b=h.urlToObject(document.location.href);b.query=b.query||{};return b.query},setSearchText:function(b){this.search.set("value",b)},getSearchText:function(){return this.search.get("value")},
getActiveSource:function(){return this.search.activeSource},clearSearchText:function(){this.search&&this.search.clear()},_setSearchString:function(){this._urlParams.find&&(this.search.set("value",this._urlParams.find),setTimeout(d.hitch(this,function(){this.search.search()}),1E3))},onLayerInfosFilterChanged:function(b){m.some(b,d.hitch(this,function(a){this.search&&this.search.sources&&0<this.search.sources.length&&m.forEach(this.search.sources,function(c){c._featureLayerId===a.id&&c.featureLayer.setDefinitionExpression(a.getFilter())})}))},
_load:function(b){this.emit("search-loaded",b);this._setSearchString()},_results:function(b){this.emit("search-results",b)},_clear:function(b){this.emit("clear-search",b)},_showPopupByFeatures:function(b,a,c){b=null;this.config.showInfoWindowOnSelect?(this.map.infoWindow.setFeatures(a),b="point"===a[0].geometry.type?a[0].geometry:(b=a[0].geometry&&a[0].geometry.getExtent())&&b.getCenter(),b&&this.map.infoWindow.show(b,{closetFirst:!0})):(this.map.infoWindow.setFeatures(a),this.map.infoWindow.updateHighlight(this.map,
a[0]),this.map.infoWindow.showHighlight());c.source._panToScale?h.featureAction.panTo(this.map,a):c.source._zoomScaleOfConfigSource?this._zoomToScale(c.source.zoomScale,a):(a=h.toFeatureSet(a),h.zoomToFeatureSet(this.map,a))},_loadInfoTemplateAndShowPopup:function(b,a,c){if(b){var e=this.map.getLayer(b.id);b.isPopupEnabled()&&e&&this._showPopupByFeatures(b,[a],c)}},_selectResult:function(b){var a=b.result.feature,c=function(f,k){return m.filter(f.graphics,function(l){return l.attributes[f.objectIdField]===
k})},e=this.layerInfosObj.getLayerInfoById(b.source._featureLayerId);e&&e.getLayerObject().then(d.hitch(this,function(f){(f=c(f,a.attributes[f.objectIdField]))&&0<f.length&&this._loadInfoTemplateAndShowPopup(e,f[0],b)}));this.search.blur();this.emit("select-result",b)}})});