// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Negreta",copy:"Copia",cut:"Retalla","delete":"Suprimeix",indent:"Sagnat",insertHorizontalRule:"Regla horitzontal",insertOrderedList:"Llista numerada",insertUnorderedList:"Llista de vinyetes",italic:"Cursiva",justifyCenter:"Alineaci\u00f3 centrada",justifyFull:"Justifica",justifyLeft:"Alineaci\u00f3 a l'esquerra",justifyRight:"Alineaci\u00f3 a la dreta",outdent:"Sagnat a l'esquerra",paste:"Enganxa",redo:"Ref\u00e9s",removeFormat:"Elimina el format",selectAll:"Selecciona-ho tot",
strikethrough:"Ratllat",subscript:"Sub\u00edndex",superscript:"Super\u00edndex",underline:"Subratllat",undo:"Desf\u00e9s",unlink:"Elimina l'enlla\u00e7",createLink:"Crea un enlla\u00e7",toggleDir:"Inverteix la direcci\u00f3",insertImage:"Insereix imatge",insertTable:"Insereix/edita la taula",toggleTableBorder:"Inverteix els contorns de taula",deleteTable:"Suprimeix la taula",tableProp:"Propietat de taula",htmlToggle:"Font HTML",foreColor:"Color de primer pla",hiliteColor:"Color de fons",plainFormatBlock:"Estil de par\u00e0graf",
formatBlock:"Estil de par\u00e0graf",fontSize:"Mida del tipus de lletra",fontName:"Nom del tipus de lletra",tabIndent:"Sagnat",fullScreen:"Commuta pantalla completa",viewSource:"Visualitza font HTML",print:"Imprimeix",newPage:"P\u00e0gina nova",systemShortcut:"L'acci\u00f3 \"${0}\" \u00e9s l'\u00fanica disponible al navegador utilitzant una drecera del teclat. Utilitzeu ${1}.",ctrlKey:"control+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Mida",fontName:"Tipus de lletra",
formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",monospace:"monoespai",cursive:"Cursiva",fantasy:"Fantasia",noFormat:"Cap",p:"Par\u00e0graf",h1:"T\u00edtol",h2:"Subt\u00edtol",h3:"Subsubt\u00edtol",pre:"Format previ",1:"xx-petit",2:"x-petit",3:"petit",4:"mitj\u00e0",5:"gran",6:"x-gran",7:"xx-gran",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Visualitzaci\u00f3 pr\u00e8via",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Cerca:",findTooltip:"Especifiqueu el text que voleu trobar",
replaceLabel:"Substitueix per:",replaceTooltip:"Especifiqueu el text amb qu\u00e8 el voleu substituir",findReplace:"Cerca i substitueix",matchCase:"Coincid\u00e8ncia de maj\u00fascules i min\u00fascules",matchCaseTooltip:"Coincid\u00e8ncia de maj\u00fascules i min\u00fascules",backwards:"Cap enrere",backwardsTooltip:"Cerca text cap enrere",replaceAllButton:"Substitueix tot",replaceAllButtonTooltip:"Substitueix tot el text",findButton:"Cerca",findButtonTooltip:"Troba el text",replaceButton:"Substitueix",
replaceButtonTooltip:"Substitueix el text",replaceDialogText:"S'han substitu\u00eft ${0} aparicions.",eofDialogText:"Darrera aparici\u00f3 ${0}",eofDialogTextFind:"trobat",eofDialogTextReplace:"substitu\u00eft",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Enganxa des de Word",instructions:"Enganxa el contingut de Word al quadre de text seg\u00fcent. Un cop esteu satisfets amb el contingut que voleu inserir, feu clic al bot\u00f3 Enganxa. Per cancel\u00b7lar la inserci\u00f3 de text, feu clic al bot\u00f3 Cancel\u00b7la.",
_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Insereix una \u00e0ncora",title:"Propietats de l'\u00e0ncora",anchor:"Nom:",text:"Descripci\u00f3:",set:"Defineix",cancel:"Cancel\u00b7la",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/GroupFilter/setting/nls/strings":{configText:"Definiu els vostres grups de filtres a continuaci\u00f3",labels:{groupName:"Nom del grup:",groupNameTip:"Proporcioneu un nom per a aquest grup de filtres. Es mostrar\u00e0 al men\u00fa desplegable de grups de filtres disponibles.",
groupDesc:"Descripci\u00f3:",groupDescTip:"Proporcioneu una descripci\u00f3 per a aquest grup de filtres",groupOperator:"Operador predefinit:",groupOperatorTip:"Opci\u00f3 per predefinir l'operador del filtre. Si no se selecciona cap operador predefinit, el filtre utilitzar\u00e0 l'operador \u00c9S IGUAL A.",groupDefault:"Valor predefinit:",groupDefaultTip:"Opci\u00f3 per escriure un valor o triar un valor existent d'una capa. Feu clic a la icona Cerca per examinar les capes.",sameLayerAppend:"Si una capa apareix m\u00e9s d'una vegada:",
sameLayerConjunc:"Afegeix mitjan\u00e7ant:",caseSearch:"Feu una cerca que distingeixi entre maj\u00fascules i min\u00fascules: ",headerTextHelp:"Proporcioneu el text que es mostrar\u00e0 sobre la selecci\u00f3 del filtre"},buttons:{addNewGroup:"Afegeix un grup nou",addNewGroupTip:"Afegeix un grup de filtres nou",addLayer:"Afegeix una capa",addLayerTip:"Afegeix una capa al grup de filtres"},inputs:{groupName:"Nom del grup de filtres",groupDesc:"Descripci\u00f3 del grup",groupDefault:"Introdu\u00efu un valor predefinit",
sameLayerAny:"Coincideix amb qualsevol expressi\u00f3",sameLayerAll:"Coincideix amb totes les expressions",simpleMode:"Inicia en visualitzaci\u00f3 simple",simpleModeTip:"Simplifiqueu la interf\u00edcie del widget. Si aquesta opci\u00f3 est\u00e0 activada, s'amaguen la llista desplegable d'operadors i els botons per afegir criteris.",webmapAppendModeAny:"Afegeix qualsevol expressi\u00f3 al filtre de mapa existent",webmapAppendModeAll:"Afegeix totes les expressions al filtre de mapa existent",webmapAppendModeTip:"Opci\u00f3 per afegir grups de filtres als filtres existents del mapa web",
persistOnClose:"Mant\u00e9n els filtres despr\u00e9s de tancar el widget",selectGroup:"Seleccioneu un grup per filtrar",hideDropDown:"Amaga la cap\u00e7alera i el filtre per a un grup",hideDropDownTip:"Amagueu la cap\u00e7alera i el men\u00fa desplegable si nom\u00e9s s'ha configurat un grup de filtres",optionsMode:"Amaga les opcions del widget",optionsModeTip:"Opci\u00f3 per mostrar la configuraci\u00f3 addicional del widget. Si est\u00e0 activada, s'amaguen de la interf\u00edcie l'opci\u00f3 de desament i c\u00e0rrega de filtres predefinits i la de manteniment del filtre despr\u00e9s de tancar el widget.",
optionOR:"OR",optionAND:"AND",optionEQUAL:"EQUALS",optionNOTEQUAL:"NOT EQUAL",optionGREATERTHAN:"GREATER THAN",optionGREATERTHANEQUAL:"GREATER THAN OR EQUAL",optionLESSTHAN:"LESS THAN",optionLESSTHANEQUAL:"LESS THAN OR EQUAL",optionSTART:"BEGINS WITH",optionEND:"ENDS WITH",optionLIKE:"CONTAINS",optionLIKESPECIFIC:"CONT\u00c9 VALORS ESPEC\u00cdFICS",optionNOTLIKESPECIFIC:"NO CONT\u00c9 VALORS ESPEC\u00cdFICS",optionNOTLIKE:"DOES NOT CONTAIN",optionONORBEFORE:"IS ON OR BEFORE",optionONORAFTER:"IS ON OR AFTER",
optionNONE:"NONE"},tables:{layer:"Capes",layerTip:"Nom de la capa tal com est\u00e0 definida al mapa.",field:"Camps",fieldTip:"Camp pel qual es filtrar\u00e0 la capa.",value:"Utilitza el valor",valueTip:"Opci\u00f3 que permet utilitzar els valors de la llista desplegable de la capa. Si cap capa utilitza aquest par\u00e0metre, es presentar\u00e0 un quadre de text sense format a l'usuari.",zoomTo:"Aplica el zoom als resultats",zoomTip:"Opci\u00f3 que permet aplicar el zoom a l'extensi\u00f3 de les entitats un cop aplicat el filtre",
action:"Suprimeix",actionTip:"Elimineu la capa del conjunt de filtres."},popupHeader:{label:"Trieu un valor predefinit"},errors:{noGroups:"Necessiteu almenys un grup.",noGroupName:"Falten un o diversos noms de grups.",noDuplicates:"Un o diversos noms de grups estan duplicats.",noRows:"Necessiteu almenys una fila a la taula.",noLayers:"No hi ha cap capa al mapa."},picker:{description:"Cerqueu el valor predefinit per a aquest grup.",layer:"Seleccioneu una capa",layerTip:"Nom de la capa tal com s'ha definit al mapa web.",
field:"Seleccioneu un camp",fieldTip:"Camp des del qual es definir\u00e0 el valor predefinit.",value:"Seleccioneu un valor",valueTip:"Valor que ser\u00e0 el definit per defecte del widget."},_localized:{}}});