// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Vet",copy:"Kopi\u00ebren",cut:"Knippen","delete":"Wissen",indent:"Inspringen",insertHorizontalRule:"Horizontale liniaal",insertOrderedList:"Genummerde lijst",insertUnorderedList:"Lijst met opsommingstekens",italic:"Cursief",justifyCenter:"Centreren",justifyFull:"Uitvullen",justifyLeft:"Links uitlijnen",justifyRight:"Rechts uitlijnen",outdent:"Uitspringen",paste:"Plakken",redo:"Opnieuw",removeFormat:"Opmaak verwijderen",selectAll:"Alles selecteren",strikethrough:"Doorhalen",
subscript:"Subscript",superscript:"Superscript",underline:"Onderstrepen",undo:"Ongedaan maken",unlink:"Link verwijderen",createLink:"Link maken",toggleDir:"Schrijfrichting wijzigen",insertImage:"Afbeelding invoegen",insertTable:"Tabel invoegen/bewerken",toggleTableBorder:"Tabelkader wijzigen",deleteTable:"Tabel wissen",tableProp:"Tabeleigenschap",htmlToggle:"HTML-bron",foreColor:"Voorgrondkleur",hiliteColor:"Achtergrondkleur",plainFormatBlock:"Alineastijl",formatBlock:"Alineastijl",fontSize:"Lettergrootte",
fontName:"Lettertype",tabIndent:"Inspringen",fullScreen:"Volledig scherm in-/uitschakelen",viewSource:"HTML-bron bekijken",print:"Afdrukken",newPage:"Nieuwe pagina",systemShortcut:'De actie "${0}" is alleen beschikbaar in uw browser via een sneltoetscombinatie. Gebruik ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Grootte",fontName:"Lettertype",formatBlock:"Opmaak",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursief",
fantasy:"fantasy",noFormat:"Geen",p:"Alinea",h1:"Kop",h2:"Subkop",h3:"Sub-subkop",pre:"Vooraf opgemaakt",1:"xx-klein",2:"x-klein",3:"klein",4:"gemiddeld",5:"groot",6:"x-groot",7:"xx-groot",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Preview",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Zoeken:",findTooltip:"Geef de zoektekst op",replaceLabel:"Vervangen door:",replaceTooltip:"Geef de vervangende tekst op",findReplace:"Zoeken en vervangen",matchCase:"Hoofdlettergevoelig",
matchCaseTooltip:"Hoofdlettergevoelig",backwards:"Terug",backwardsTooltip:"Terugwaarts naar tekst zoeken",replaceAllButton:"Alle vervangen",replaceAllButtonTooltip:"Gehele tekst vervangen",findButton:"Zoeken:",findButtonTooltip:"Tekst zoeken",replaceButton:"Vervangen",replaceButtonTooltip:"Tekst vervangen",replaceDialogText:"${0} vervangingen.",eofDialogText:"Laatste positie ${0}",eofDialogTextFind:"gevonden",eofDialogTextReplace:"vervangen",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Plakken vanuit Word",
instructions:"Plak de content vanuit Word in het tekstvak hieronder. Klik als u klaar bent op de knop Plakken. Kies Annuleren als u de invoeging van tekst wilt afbreken.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Anker invoegen",title:"Ankereigenschappen",anchor:"Naam:",text:"Beschrijving:",set:"Instellen",cancel:"Annuleren",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/GroupFilter/setting/nls/strings":{configText:"Definieer uw filtergroepen hieronder",
labels:{groupName:"Groepsnaam:",groupNameTip:"Geef een naam voor deze filtergroep. Hij wordt weergegeven in de keuzelijst met beschikbare filtergroepen.",groupDesc:"Beschrijving:",groupDescTip:"Geef een beschrijving voor deze filtergroep.",groupOperator:"Ingestelde operator:",groupOperatorTip:"Optie om de operator van het filter vooraf te bepalen. Als er vooraf geen operator geselecteerd wordt, zal het filter de GELIJK AAN-operator gebruiken.",groupDefault:"Ingestelde waarde",groupDefaultTip:"Optie om een waarde te typen of een bestaande waarde uit een laag te kiezen. Klik op het pictogram Zoeken om door lagen te bladeren.",
sameLayerAppend:"Als een laag meer dan \u00e9\u00e9n keer vermeld wordt:",sameLayerConjunc:"Aanpassen d.m.v.:",caseSearch:"Een hoofdlettergevoelige zoekopdracht uitvoeren: ",headerTextHelp:"Geef tekst op om boven de filterkeuze weer te geven"},buttons:{addNewGroup:"Voeg nieuwe groep toe",addNewGroupTip:"Een nieuwe filtergroep toevoegen",addLayer:"Kaartlaag toevoegen",addLayerTip:"Een laag toevoegen aan de filtergroep."},inputs:{groupName:"Naam van filtergroep",groupDesc:"Beschrijving voor de groep",
groupDefault:"Voer een ingestelde waarde in",sameLayerAny:"E\u00e9n expressie geeft een resultaat",sameLayerAll:"Voldoe aan alle expressies",simpleMode:"Start in eenvoudige weergave",simpleModeTip:"Vereenvoudig de widget-interface. Als deze selectievakje is geselecteerd, worden de keuzelijst voor operators en de knoppen voor het toevoegen van criteria verborgen.",webmapAppendModeAny:"E\u00e9n expressie toevoegen aan bestaande kaartfilter",webmapAppendModeAll:"Alle expressies toevoegen aan bestaande kaartfilter",
webmapAppendModeTip:"Optie om filtergroepen toe te voegen aan bestaande filters in de webmap.",persistOnClose:"Filters behouden nadat de widget is gesloten",selectGroup:"Selecteer een groep om te filteren",hideDropDown:"Verberg koptekst en filter voor 1 groep",hideDropDownTip:"Verberg de koptekst en de keuzelijst als er maar 1 filtergroep is geconfigureerd",optionsMode:"Widgetopties verbergen",optionsModeTip:"Optie om bijkomende widgetinstellingen weer te geven. Als deze aangevinkt wordt, worden het opslaan en laden van gedefinieerde filters en het filter behouden na het sluiten van de widget verwijderd uit de interface.",
optionOR:"OF",optionAND:"AND",optionEQUAL:"IS GELIJK AAN",optionNOTEQUAL:"NIET GELIJK AAN",optionGREATERTHAN:"GROTER DAN",optionGREATERTHANEQUAL:"GROTER DAN OF GELIJK AAN",optionLESSTHAN:"KLEINER DAN",optionLESSTHANEQUAL:"KLEINER DAN OF GELIJK AAN",optionSTART:"BEGINT MET",optionEND:"EINDIGT MET",optionLIKE:"BEVAT",optionLIKESPECIFIC:"BEVAT SPECIFIEKE WAARDEN",optionNOTLIKESPECIFIC:"BEVAT GEEN SPECIFIEKE WAARDEN",optionNOTLIKE:"BEVAT NIET",optionONORBEFORE:"IS OP OF VOOR",optionONORAFTER:"IS OP OF NA",
optionNONE:"GEEN"},tables:{layer:"Kaartlagen",layerTip:"Naam van de laag zoals gedefinieerd in de kaart.",field:"Velden",fieldTip:"Veld waar de laag op gefilterd zal worden.",value:"Gebruik waarde",valueTip:"Optie om de vervolgkeuzemenuwaarden van de laag te gebruiken. Als er geen enkele laag deze parameter gebruikt, zal er een tekstvak met gewone tekst aan de gebruiker getoond worden.",zoomTo:"Inzoomen op resultaat",zoomTip:"Optie om in te zoomen op het bereik van de functies nadat het filter is toegepast",
action:"Verwijderen",actionTip:"Laag uit de filterreeks verwijderen."},popupHeader:{label:"Kies een ingestelde waarde"},errors:{noGroups:"U hebt minstens \u00e9\u00e9n groep nodig.",noGroupName:"E\u00e9n of meer groepsnamen ontbreken.",noDuplicates:"E\u00e9n of meer groepsnamen zijn dubbel.",noRows:"U hebt minimaal \u00e9\u00e9n rij in de tabel nodig.",noLayers:"U hebt geen lagen in de kaart."},picker:{description:"Zoek de ingestelde waarde voor deze groep.",layer:"Selecteer een laag",layerTip:"Naam van de laag zoals gedefinieerd in de webmap.",
field:"Selecteer een veld",fieldTip:"Veld van waaruit de vooraf ingestelde waarde zal ingesteld worden.",value:"Selecteer een waarde",valueTip:"Waarde die de standaardwaarde van de widget zal zijn."},_localized:{}}});