// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Fett",copy:"Kopieren",cut:"Ausschneiden","delete":"L\u00f6schen",indent:"Einr\u00fccken",insertHorizontalRule:"Horizontaler Strich",insertOrderedList:"Nummerierung",insertUnorderedList:"Aufz\u00e4hlungszeichen",italic:"Kursiv",justifyCenter:"Zentriert",justifyFull:"Blocksatz",justifyLeft:"Linksb\u00fcndig",justifyRight:"Rechtsb\u00fcndig",outdent:"Ausr\u00fccken",paste:"Einf\u00fcgen",redo:"Wiederholen",removeFormat:"Formatierung entfernen",selectAll:"Alles ausw\u00e4hlen",
strikethrough:"Durchgestrichen",subscript:"Tiefgestellt",superscript:"Hochgestellt",underline:"Unterstrichen",undo:"R\u00fcckg\u00e4ngig",unlink:"Link entfernen",createLink:"Link erstellen",toggleDir:"Richtung wechseln",insertImage:"Grafik einf\u00fcgen",insertTable:"Tabelle einf\u00fcgen/bearbeiten",toggleTableBorder:"Tabellenumrandung ein-/ausschalten",deleteTable:"Tabelle l\u00f6schen",tableProp:"Tabelleneigenschaft",htmlToggle:"HTML-Quelltext",foreColor:"Vordergrundfarbe",hiliteColor:"Hintergrundfarbe",
plainFormatBlock:"Absatzstil",formatBlock:"Absatzstil",fontSize:"Schriftgr\u00f6\u00dfe",fontName:"Schriftartname",tabIndent:"Registerkarteneinr\u00fcckung",fullScreen:"Gesamtanzeige",viewSource:"HTML-Quelle",print:"Drucken",newPage:"Neue Seite",systemShortcut:'Die Aktion "${0}" ist nur \u00fcber einen Direktaufruf in Ihrem Browser verf\u00fcgbar. Verwenden Sie ${1}.',ctrlKey:"Strg+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Gr\u00f6\u00dfe",fontName:"Schriftart",
formatBlock:"Format",serif:"Serife","sans-serif":"Serifenlos",monospace:"Monospaceschrift",cursive:"Kursiv",fantasy:"Fantasie",noFormat:"Keine Angabe",p:"Absatz",h1:"\u00dcberschrift",h2:"Unter\u00fcberschrift",h3:"Unterunter\u00fcberschrift",pre:"Vorformatiert",1:"XXS",2:"XS",3:"S",4:"M",5:"L",6:"XL",7:"XXL",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Vorschau",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Suchen:",findTooltip:"Text zum Suchen eingeben",replaceLabel:"Ersetzen durch:",
replaceTooltip:"Text zum Ersetzen eingeben",findReplace:"Suchen und ersetzen",matchCase:"Gro\u00df- und Kleinschreibung abgleichen",matchCaseTooltip:"Gro\u00df- und Kleinschreibung abgleichen",backwards:"Zur\u00fcck",backwardsTooltip:"R\u00fcckw\u00e4rts nach Text suchen",replaceAllButton:"Global ersetzen",replaceAllButtonTooltip:"Gesamten Text ersetzen",findButton:"Suchen",findButtonTooltip:"Text suchen",replaceButton:"Ersetzen",replaceButtonTooltip:"Text ersetzen",replaceDialogText:"${0} Vorkommen ersetzt.",
eofDialogText:"Letztes Vorkommen ${0}",eofDialogTextFind:"gefunden",eofDialogTextReplace:"ersetzt",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Aus Word einf\u00fcgen",instructions:"F\u00fcgt den Inhalt aus Word in das Textfeld unten ein. Wenn Sie mit dem einzuf\u00fcgenden Inhalt zufrieden sind, klicken Sie auf die Schaltfl\u00e4che zum Einf\u00fcgen. Um das Einf\u00fcgen von Text abzubrechen, klicken Sie auf die Schaltfl\u00e4che zum Abbrechen. ",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Anker einf\u00fcgen",
title:"Eigenschaften des Ankers",anchor:"Name:",text:"Beschreibung:",set:"Festlegen",cancel:"Abbrechen",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockzitat",_localized:{}},"widgets/GroupFilter/setting/nls/strings":{configText:"Definieren Sie unten die Filtergruppen",labels:{groupName:"Gruppenname:",groupNameTip:"Geben Sie einen Namen f\u00fcr diese Filtergruppe an. Dieser wird im Dropdown der verf\u00fcgbaren Filtergruppen angezeigt.",groupDesc:"Beschreibung:",groupDescTip:"Eine Beschreibung f\u00fcr diese Filtergruppe eingeben",
groupOperator:"Voreingestellter Operator",groupOperatorTip:'Option zum Vordefinieren des Operators f\u00fcr den Filter. Wenn kein voreingestellter Operator ausgew\u00e4hlt ist, wird vom Filter der Operator "GLEICH" verwendet.',groupDefault:"Voreingestellter Wert:",groupDefaultTip:"Option zum Eingeben eines Wertes oder zum Ausw\u00e4hlen eines vorhandenen Wertes aus einem Layer. Klicken Sie auf das Suchsymbol, um Layer zu durchsuchen.",sameLayerAppend:"Wenn ein Layer mehrmals aufgelistet ist:",sameLayerConjunc:"Anh\u00e4ngen mit:",
caseSearch:"Suche durchf\u00fchren, bei der Gro\u00df- und Kleinschreibung ber\u00fccksichtigt wird: ",headerTextHelp:"Text f\u00fcr die Anzeige \u00fcber der Filterauswahl eingeben"},buttons:{addNewGroup:"Eine neue Gruppe hinzuf\u00fcgen",addNewGroupTip:"Neue Filtergruppe hinzuf\u00fcgen",addLayer:"Layer hinzuf\u00fcgen",addLayerTip:"Layer zur Filtergruppe hinzuf\u00fcgen"},inputs:{groupName:"Filtergruppenname",groupDesc:"Beschreibung der Gruppe",groupDefault:"Vordefinierten Wert eingeben",sameLayerAny:"Einigen Ausdr\u00fccken entsprechen",
sameLayerAll:"\u00dcbereinstimmung mit allen Ausdr\u00fccken",simpleMode:"In einfacher Ansicht starten",simpleModeTip:"Vereinfachen Sie die Widget-Oberfl\u00e4che. Wenn diese Option aktiviert ist, werden die Schaltfl\u00e4chen f\u00fcr die Operator-Dropdown-Liste und zum Hinzuf\u00fcgen von Kriterien ausgeblendet.",webmapAppendModeAny:"Einige Ausdr\u00fccke an vorhandenen Kartenfilter anh\u00e4ngen",webmapAppendModeAll:"Alle Ausdr\u00fccke an vorhandenen Kartenfilter anh\u00e4ngen",webmapAppendModeTip:"Option zum Anh\u00e4ngen von Filtergruppen an vorhandene Filter in der Webkarte",
persistOnClose:"Filter nach dem Schlie\u00dfen des Widgets beibehalten",selectGroup:"Eine zu filternde Gruppe ausw\u00e4hlen",hideDropDown:"Kopfzeile und Filter f\u00fcr 1\u00a0Gruppe ausblenden",hideDropDownTip:"Kopfzeile und Dropdown ausblenden, wenn nur 1\u00a0Filtergruppe konfiguriert ist",optionsMode:"Widget-Optionen ausblenden",optionsModeTip:"Option zum Bereitstellen zus\u00e4tzlicher Widget-Einstellungen. Wenn diese Option aktiviert ist, werden die Funktionen zum Speichern und Laden definierter Filter und zum Beibehalten des Filters nach dem Schlie\u00dfen des Widgets in der Benutzeroberfl\u00e4che ausgeblendet.",
optionOR:"ODER",optionAND:"UND",optionEQUAL:"GLEICH",optionNOTEQUAL:"UNGLEICH",optionGREATERTHAN:"GR\u00d6SSER ALS",optionGREATERTHANEQUAL:"GR\u00d6SSER ODER GLEICH",optionLESSTHAN:"KLEINER ALS",optionLESSTHANEQUAL:"KLEINER ODER GLEICH",optionSTART:"BEGINNT MIT",optionEND:"ENDET MIT",optionLIKE:"ENTH\u00c4LT",optionLIKESPECIFIC:"ENTH\u00c4LT BESTIMMTE WERTE",optionNOTLIKESPECIFIC:"ENTH\u00c4LT KEINE BESTIMMTEN WERTE",optionNOTLIKE:"ENTH\u00c4LT NICHT",optionONORBEFORE:"IST AM ODER VOR",optionONORAFTER:"IST AM ODER NACH",
optionNONE:"KEIN"},tables:{layer:"Layer",layerTip:"Name des Layers gem\u00e4\u00df der Definition in der Karte",field:"Felder",fieldTip:"Feld, nach dem der Layer gefiltert wird",value:"Wert verwenden",valueTip:"Option zum Verwenden der Dropdown-Listenwerte aus dem Layer. Wenn kein Layer diesen Parameter verwendet, wird dem Benutzer ein Textfeld angezeigt.",zoomTo:"Auf Ergebnis zoomen",zoomTip:"Option zum Zoomen auf die Ausdehnung der Features nach Anwenden des Filters",action:"L\u00f6schen",actionTip:"Layer aus dem Filtersatz entfernen"},
popupHeader:{label:"Voreingestellten Wert ausw\u00e4hlen"},errors:{noGroups:"Sie ben\u00f6tigen mindestens eine Gruppe.",noGroupName:"Mindestens ein Gruppenname fehlt.",noDuplicates:"Mindestens ein Gruppenname ist dupliziert.",noRows:"Die Tabelle muss mindestens eine Zeile enthalten.",noLayers:"Ihre Karte enth\u00e4lt keine Layer."},picker:{description:"Den voreingestellten Wert f\u00fcr diese Gruppe suchen.",layer:"Einen Layer ausw\u00e4hlen",layerTip:"Name des Layers gem\u00e4\u00df der Definition in der Webkarte",
field:"Ein Feld ausw\u00e4hlen",fieldTip:"Feld, in dem der voreingestellte Wert festgelegt wird",value:"Einen Wert ausw\u00e4hlen",valueTip:"Als Standardwert des Widgets festgelegter Wert"},_localized:{}}});