// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Rasvane",copy:"Kopeeri",cut:"L\u00f5ika","delete":"Kustuta",indent:"Paremtaane",insertHorizontalRule:"Horisontaaljoon",insertOrderedList:"Nummerdatud loend",insertUnorderedList:"T\u00e4pploend",italic:"Kursiiv",justifyCenter:"Keskjoondus",justifyFull:"R\u00f6\u00f6pjoondus",justifyLeft:"Vasakjoondus",justifyRight:"Paremjoondus",outdent:"Vasaktaane",paste:"Kleebi",redo:"Tee uuesti",removeFormat:"Eemalda vorming",selectAll:"Vali k\u00f5ik",strikethrough:"L\u00e4bikriipsutus",
subscript:"Allindeks",superscript:"\u00dclaindeks",underline:"Allajoonitud",undo:"T\u00fchista",unlink:"Eemalda link",createLink:"Loo link",toggleDir:"Vaheta suund",insertImage:"Sisesta pilt",insertTable:"Lisa/muuda tabelit",toggleTableBorder:"L\u00fclita tabeli\u00e4\u00e4ris sisse/v\u00e4lja",deleteTable:"Kustuta tabel",tableProp:"Tabeli atribuut",htmlToggle:"HTML-l\u00e4htetekst",foreColor:"Esiv\u00e4rv",hiliteColor:"Taustav\u00e4rv",plainFormatBlock:"L\u00f5igu laad",formatBlock:"L\u00f5igu laad",
fontSize:"Fondi suurus",fontName:"Fondi nimi",tabIndent:"Tabeldustaane",fullScreen:"L\u00fclita t\u00e4isekraan sisse/v\u00e4lja",viewSource:"Kuva HTML-l\u00e4htetekst",print:"Prindi",newPage:"Uus leht",systemShortcut:"Seda toimingut ${0} saab Teie brauseris teha ainult kiirklahvi abil. Kasutage klahvikombinatsiooni ${1}.",ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Suurus",fontName:"Font",formatBlock:"Formaat",serif:"seriifidega","sans-serif":"groteskkiri",
monospace:"p\u00fcsisamm",cursive:"kursiiv",fantasy:"fantaasia",noFormat:"Puudub",p:"L\u00f5ik",h1:"Pealkiri",h2:"Alapealkiri",h3:"Ala-alapealkiri",pre:"Eelvormindatud",1:"eriti v\u00e4ike",2:"v\u00e4ga v\u00e4ike",3:"v\u00e4ike",4:"keskmine",5:"suur",6:"v\u00e4ga suur",7:"eriti suur",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Preview",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Find:",findTooltip:"Enter text to find",replaceLabel:"Replace with:",replaceTooltip:"Enter text to replace with",
findReplace:"Find and Replace",matchCase:"Match case",matchCaseTooltip:"Match case",backwards:"Backwards",backwardsTooltip:"Search backwards for text",replaceAllButton:"Replace All",replaceAllButtonTooltip:"Replace all the text",findButton:"Find",findButtonTooltip:"Find the text",replaceButton:"Replace",replaceButtonTooltip:"Replace the text",replaceDialogText:"Replaced ${0} occurrences.",eofDialogText:"Last occurrence ${0}",eofDialogTextFind:"found",eofDialogTextReplace:"replaced",_localized:{}},
"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Paste From Word",instructions:"Paste the content from Word into the text box below.  Once you are satisfied with the content to insert, press the paste button.  To abort inserting text, press the cancel button.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Insert Anchor",title:"Anchor Properties",anchor:"Name:",text:"Description:",set:"Set",cancel:"Cancel",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",
_localized:{}},"widgets/GroupFilter/setting/nls/strings":{configText:"M\u00e4\u00e4ratlege filtrigrupid allpool",labels:{groupName:"Grupi nimi:",groupNameTip:"Sisestage selle filtrigrupi nimi. See kuvatakse saadaolevate filtrigruppide rippmen\u00fc\u00fcs.",groupDesc:"Kirjeldus:",groupDescTip:"Sisestage selle filtrigrupi kirjeldus",groupOperator:"Eelseatud tehtem\u00e4rk:",groupOperatorTip:"V\u00f5imalus m\u00e4\u00e4ratleda filtri tehtem\u00e4rk. Kui eelseatud tehtem\u00e4rki ei valita, kasutab filter tehtem\u00e4rki V\u00d5RDUB.",
groupDefault:"Eelseatud v\u00e4\u00e4rtus:",groupDefaultTip:"V\u00f5imalus tippida v\u00e4\u00e4rtus v\u00f5i valida olemasolev v\u00e4\u00e4rtus kihist. Kl\u00f5psake kihtide sirvimiseks otsinguikooni.",sameLayerAppend:"Kui kiht on loetletud rohkem kui \u00fcks kord:",sameLayerConjunc:"Lisa kasutus:",caseSearch:"Teosta t\u00f5stutundlik otsing: ",headerTextHelp:"Esitage filtri valiku kohal kuvatav tekst"},buttons:{addNewGroup:"Lisa uus grupp",addNewGroupTip:"Lisa uus filtrigrupp",addLayer:"Lisa kiht",
addLayerTip:"Lisa kiht filtrigruppi"},inputs:{groupName:"Filtrigrupi nimi",groupDesc:"Grupi kirjeldus",groupDefault:"Sisesta eelm\u00e4\u00e4ratletud v\u00e4\u00e4rtus",sameLayerAny:"Vastenda mis tahes avaldis",sameLayerAll:"Vastenda k\u00f5ik avaldised",simpleMode:"Alusta lihtsas vaates",simpleModeTip:"Lihtsustage vidinaliidest. Kui see on m\u00e4rgitud, peidetakse tehtem\u00e4rkide ripploendi ja kriteeriumide lisamise nupud.",webmapAppendModeAny:"Lisa mis tahes avaldised olemasolevasse kaardifiltrisse",
webmapAppendModeAll:"Lisa k\u00f5ik avaldised olemasolevasse kaardifiltrisse",webmapAppendModeTip:"Suvand fitrigruppide lisamiseks veebikaardi olemasolevatele filtritele",persistOnClose:"S\u00e4ilita filtrid p\u00e4rast vidina sulgemist",selectGroup:"Vali filtreeritav grupp",hideDropDown:"Peida p\u00e4is ja filter 1 grupi jaoks",hideDropDownTip:"Peida p\u00e4is ja ripploend, kui ainult 1 grupp on konfigureeritud",optionsMode:"Peida vidinasuvandid",optionsModeTip:"Suvand t\u00e4iendavate vidinaseadete kuvamiseks. Kui see on m\u00e4rgitud, eemaldatakse p\u00e4rast vidina sulgemist liidesest eelm\u00e4\u00e4ratletud filtrite salvestamine ja laadimine ning filtri s\u00e4ilitamine.",
optionOR:"V\u00d5I",optionAND:"JA",optionEQUAL:"V\u00d5RDUB",optionNOTEQUAL:"EI OLE V\u00d5RDNE",optionGREATERTHAN:"SUUREM KUI",optionGREATERTHANEQUAL:"SUUREM KUI V\u00d5I V\u00d5RDNE",optionLESSTHAN:"V\u00c4IKSEM KUI",optionLESSTHANEQUAL:"V\u00c4IKSEM KUI V\u00d5I V\u00d5RDNE",optionSTART:"ALGAB",optionEND:"L\u00d5PEB",optionLIKE:"SISALDAB",optionLIKESPECIFIC:"SISALDAB ERIV\u00c4\u00c4RTUSI",optionNOTLIKESPECIFIC:"EI SISALDA ERIV\u00c4\u00c4RTUSI",optionNOTLIKE:"EI SISALDA",optionONORBEFORE:"ON V\u00d5RDNE V\u00d5I ENNE",
optionONORAFTER:"ON V\u00d5RDNE V\u00d5I P\u00c4RAST",optionNONE:"PUUDUB"},tables:{layer:"Kihid",layerTip:"Kaardil m\u00e4\u00e4ratletud kihi nimi.",field:"V\u00e4ljad",fieldTip:"V\u00e4li, millel kiht filtreeritakse.",value:"Kasuta v\u00e4\u00e4rtust",valueTip:"V\u00f5imalus kasutada kihi ripploendi v\u00e4\u00e4rtusi. Kui \u00fckski kiht seda parameetrit ei kasuta, kuvatakse kasutajale lihtteksti v\u00e4li.",zoomTo:"Suumi tulemini",zoomTip:"Suvand p\u00e4rast filtri rakendamist \u00fclej\u00e4\u00e4nud objektide ulatusele suumiseks",
action:"Kustuta",actionTip:"Saate filtrikogumist kihi eemaldada."},popupHeader:{label:"Vali eelseatud v\u00e4\u00e4rtus"},errors:{noGroups:"Teil peab olema v\u00e4hemalt \u00fcks grupp.",noGroupName:"V\u00e4hemalt \u00fcks grupi nimi puudub.",noDuplicates:"V\u00e4hemalt \u00fcks grupi nimi esineb kaks korda.",noRows:"Tabelis peab olema v\u00e4hemalt \u00fcks rida.",noLayers:"Teie kaardil pole kihte."},picker:{description:"Leidke selle grupi jaoks eelseatud v\u00e4\u00e4rtus.",layer:"Vali kiht",layerTip:"Veebikaardil m\u00e4\u00e4ratletud kihi nimi.",
field:"Vali v\u00e4li",fieldTip:"V\u00e4li, mille kaudu m\u00e4\u00e4ratakse eelseatud v\u00e4\u00e4rtus.",value:"Vali v\u00e4\u00e4rtus",valueTip:"Vidina vaikev\u00e4\u00e4rtus."},_localized:{}}});