// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Podebljaj",copy:"Kopiraj",cut:"Izre\u017ei","delete":"Izbri\u0161i",indent:"Uvuci",insertHorizontalRule:"Vodoravno ravnalo",insertOrderedList:"Numerirani popis",insertUnorderedList:"Popis s grafi\u010dkim oznakama",italic:"Kurziv",justifyCenter:"Centriraj",justifyFull:"Poravnaj",justifyLeft:"Poravnaj lijevo",justifyRight:"Poravnaj desno",outdent:"Izvuci",paste:"Zalijepi",redo:"Ponovno napravi",removeFormat:"Ukloni oblikovanje",selectAll:"Izaberi sve",strikethrough:"Precrtaj",
subscript:"Indeks",superscript:"Superskript",underline:"Podcrtaj",undo:"Poni\u0161ti",unlink:"Ukloni vezu",createLink:"Kreiraj vezu",toggleDir:"Prebaci smjer",insertImage:"Umetni sliku",insertTable:"Umetni/Uredi tablicu",toggleTableBorder:"Prebaci rub tablice",deleteTable:"Izbri\u0161i tablicu",tableProp:"Svojstvo tablice",htmlToggle:"HTML izvor",foreColor:"Boja prednjeg plana",hiliteColor:"Boja pozadine",plainFormatBlock:"Stil odlomka",formatBlock:"Stil odlomka",fontSize:"Veli\u010dina fonta",fontName:"Ime fonta",
tabIndent:"Tabulator uvla\u010denja",fullScreen:"Prebaci na potpun ekran",viewSource:"Pogledaj HTML izvor",print:"Ispis",newPage:"Nova stranica",systemShortcut:'"${0}" akcija je dostupna jedino u va\u0161em pregledniku upotrebom pre\u010dice tipkovnice. Koristite ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Veli\u010dina",fontName:"Font",formatBlock:"Oblikovanje",serif:"serif","sans-serif":"sans-serif",monospace:"jednaki razmak",cursive:"rukopisni",
fantasy:"fantastika",noFormat:"Nijedan",p:"Odlomak",h1:"Naslov",h2:"Podnaslov",h3:"Pod-podnaslov",pre:"Prethodno formatirano",1:"vrlo vrlo malo",2:"vrlo malo",3:"malo",4:"srednje",5:"veliko",6:"vrlo veliko",7:"vrlo vrlo veliko",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Pregled",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Tra\u017ei:",findTooltip:"Unesi tekst pretrage",replaceLabel:"Zamijeni s:",replaceTooltip:"Unesi tekst za zamjenu",findReplace:"Tra\u017ei i zamijeni",
matchCase:"Usporedi velika/mala slova",matchCaseTooltip:"Usporedi velika/mala slova",backwards:"Natrag",backwardsTooltip:"Pretra\u017ei tekst u prethodnim koracima",replaceAllButton:"Zamijeni sve",replaceAllButtonTooltip:"Zamijeni cijeli tekst",findButton:"Tra\u017ei",findButtonTooltip:"Tra\u017ei tekst",replaceButton:"Zamijeni",replaceButtonTooltip:"Zamijeni tekst",replaceDialogText:"Zamijenjeno ${0} pojavljivanja.",eofDialogText:"Zadnje pojavljivanje ${0}",eofDialogTextFind:"na\u0111eno",eofDialogTextReplace:"zamijenjeno",
_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Zalijepi iz Worda",instructions:"Zalijepite sadr\u017eaj iz Worda u donji tekstni okvir. Kad ste zadovoljni sa sadr\u017eajem za umetanje, pritisnite tipku Zalijepi.  Za prekid umetanja teksta, pritisnite tipku Opoziv.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Umetni sidro",title:"Svojstva sidra",anchor:"Naziv:",text:"Opis:",set:"Postavi",cancel:"Opoziv",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Dugi citat",
_localized:{}},"widgets/GroupFilter/setting/nls/strings":{configText:"Definirajte grupe filtara u nastavku",labels:{groupName:"Naziv grupe:",groupNameTip:"Navedite naziv za ovu grupu filtera. Prikazat \u0107e se na padaju\u0107em izborniku dostupnih grupa filtara.",groupDesc:"Opis:",groupDescTip:"Navedite opis za ovu grupu filtera",groupOperator:"Prethodno postavljeni rukovatelj:",groupOperatorTip:"Mogu\u0107nost unaprijed definiranja rukovatelja filtera. Ako ne postoji predefinirani rukovatelj, filtar \u0107e upotrijebiti JEDNAKOG rukovatelja.",
groupDefault:"Prethodno postavljena vrijednost:",groupDefaultTip:"Mogu\u0107nost upisivanja vrijednosti ili odabira postoje\u0107e vrijednosti iz sloja. Kliknite ikonu Tra\u017ei za pregledavanje slojeva.",sameLayerAppend:"Kada je sloj naveden vi\u0161e puta:",sameLayerConjunc:"Pridodajte pomo\u0107u sljede\u0107eg:",caseSearch:"Izvr\u0161ite pretra\u017eivanje osjetljivo na veli\u010dinu slova: ",headerTextHelp:"Navedite tekst za prikaz iznad odabira filtra"},buttons:{addNewGroup:"Dodaj novu grupu",
addNewGroupTip:"Dodajte novu grupu filtera",addLayer:"Dodaj sloj",addLayerTip:"Dodajte sloj u grupu filtera"},inputs:{groupName:"Naziv grupe filtera",groupDesc:"Opis za grupu",groupDefault:"Unesite prethodno definiranu vrijednost",sameLayerAny:"Prona\u0111i podudaranje s bilo kojim izrazom",sameLayerAll:"Prona\u0111i podudaranje sa svim izrazima",simpleMode:"Pokreni u pojednostavljenom prikazu",simpleModeTip:"Pojednostavni su\u010delje widgeta. Kada je ozna\u010deno, padaju\u0107i izbornik za rukovatelja i gumbi za dodavanje kriterija su sakriveni.",
webmapAppendModeAny:"Dodaj bilo koje izraze postoje\u0107em filtru karte",webmapAppendModeAll:"Dodaj sve izraze postoje\u0107em filtru karte",webmapAppendModeTip:"Mogu\u0107nost dodavanja grupa filtera postoje\u0107im filterima na web karti",persistOnClose:"Nastavi filtere nakon zatvaranja widgeta",selectGroup:"Odaberi grupu za filtriranje",hideDropDown:"Sakrij zaglavlje i filtriraj za 1 grupu",hideDropDownTip:"Sakrij zaglavlje i padaju\u0107i izbornik ako je konfigurirana samo 1 grupa filtera",optionsMode:"Sakrij opcije widgeta",
optionsModeTip:"Mogu\u0107nost prikazivanja dodatnih postavki widgeta. Ako je ozna\u010deno, spremanje i u\u010ditavanje unaprijed definiranih filtera i zadr\u017eavanje filtera nakon zatvaranja widgeta skriveni su iz su\u010delja.",optionOR:"ILI",optionAND:"I",optionEQUAL:"JEDNAKO",optionNOTEQUAL:"NIJE JEDNAKO",optionGREATERTHAN:"VE\u0106E OD",optionGREATERTHANEQUAL:"VE\u0106E OD ILI JEDNAKO",optionLESSTHAN:"MANJE OD",optionLESSTHANEQUAL:"MANJE OD ILI JEDNAKO",optionSTART:"PO\u010cINJE S",optionEND:"ZAVR\u0160AVA S",
optionLIKE:"SADR\u017dI",optionLIKESPECIFIC:"SADR\u017dI ODRE\u0110ENE VRIJEDNOSTI",optionNOTLIKESPECIFIC:"NE SADR\u017dI ODRE\u0110ENE VRIJEDNOSTI",optionNOTLIKE:"NE SADR\u017dI",optionONORBEFORE:"JE NA ILI PRIJE",optionONORAFTER:"JE NA ILI KASNIJE",optionNONE:"NEMA"},tables:{layer:"Slojevi",layerTip:"Naziv sloja kako je definirano na karti.",field:"Polja",fieldTip:"Polje prema kojem \u0107e se sloj filtrirati.",value:"Upotrijebi vrijednost",valueTip:"Opcija za upotrebu vrijednosti padaju\u0107eg izbornika sa sloja. Ako nijedan sloj ne upotrebljava ovaj parametar, korisniku \u0107e se prikazati obi\u010dan okvir za tekst.",
zoomTo:"Pove\u0107aj na rezultat",zoomTip:"Opcija pove\u0107avanja na obuhvat geoobjekta nakon \u0161to se filtar primijeni",action:"Izbri\u0161i",actionTip:"Uklonite sloj iz skupa filtara."},popupHeader:{label:"Odaberi prethodno postavljenu vrijednost"},errors:{noGroups:"Potrebna vam je barem jedna grupa.",noGroupName:"Nedostaje jedan ili vi\u0161e naziva grupa.",noDuplicates:"Kopiranu su jedan ili vi\u0161e naziva grupa.",noRows:"Potreban vam je barem jedan red u tablici.",noLayers:"Nemate slojeva u karti."},
picker:{description:"Prona\u0111i unaprijed postavljenu vrijednost za ovu grupu.",layer:"Odaberi sloj",layerTip:"Naziv sloja kako je definirano na web-karti.",field:"Odaberi polje",fieldTip:"Polje prema kojem \u0107e se postavljati predefinirana vrijednost.",value:"Odaberi vrijednost",valueTip:"Vrijednost koja \u0107e biti zadana widgetu."},_localized:{}}});