// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Grassetto",copy:"Copia",cut:"Taglia","delete":"Elimina",indent:"Rientro",insertHorizontalRule:"Righello orizzontale",insertOrderedList:"Elenco numerato",insertUnorderedList:"Elenco puntato",italic:"Corsivo",justifyCenter:"Allinea al centro",justifyFull:"Giustifica",justifyLeft:"Allinea a sinistra",justifyRight:"Allinea a destra",outdent:"Annulla rientro",paste:"Incolla",redo:"Ripristina",removeFormat:"Rimuovi formato",selectAll:"Seleziona tutto",strikethrough:"Barrato",
subscript:"Pedice",superscript:"Apice",underline:"Sottolinea",undo:"Annulla",unlink:"Rimuovi collegamento",createLink:"Crea collegamento",toggleDir:"Attiva/Disattiva direzione",insertImage:"Inserisci immagine",insertTable:"Inserisci/Modifica tabella",toggleTableBorder:"Attiva/Disattiva bordo tabella",deleteTable:"Elimina tabella",tableProp:"Propriet\u00e0 tabella",htmlToggle:"Origine HTML",foreColor:"Colore primo piano",hiliteColor:"Colore sfondo",plainFormatBlock:"Stile paragrafo",formatBlock:"Stile paragrafo",
fontSize:"Dimensione carattere",fontName:"Nome carattere",tabIndent:"Rientro tabulazione",fullScreen:"Attiva/Disattiva schermo intero",viewSource:"Visualizza origine HTML",print:"Stampa",newPage:"Nuova pagina",systemShortcut:'La azione "${0}" \u00e8 disponibile solo nel browser tramite un tasto di scelta rapida. Utilizzare ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Dimensione",fontName:"Carattere",formatBlock:"Formato",serif:"serif","sans-serif":"sans-serif",
monospace:"spaziatura fissa",cursive:"corsivo",fantasy:"fantasy",noFormat:"Nessuna",p:"Paragrafo",h1:"Intestazione",h2:"Sottointestazione",h3:"Sottointestazione secondaria",pre:"Preformattato",1:"piccolissimo",2:"molto piccolo",3:"piccolo",4:"medio",5:"grande",6:"molto grande",7:"grandissimo",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Anteprima",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Trova:",findTooltip:"Immettere il testo da ricercare",replaceLabel:"Sostituisci con:",
replaceTooltip:"Immettere il testo con cui sostituire",findReplace:"Trova e sostituisci",matchCase:"Corrispondenza maiuscolo/minuscolo",matchCaseTooltip:"Corrispondenza maiuscolo/minuscolo",backwards:"Indietro",backwardsTooltip:"Ricercare il testo all'indietro",replaceAllButton:"Sostituisci tutti",replaceAllButtonTooltip:"Sostituisci tutto il testo",findButton:"Trova",findButtonTooltip:"Trova il testo",replaceButton:"Sostituisci",replaceButtonTooltip:"Sostituisci il testo",replaceDialogText:"Sostituite ${0} ricorrenze.",
eofDialogText:"Ultime ${0} ricorrenze",eofDialogTextFind:"trovato",eofDialogTextReplace:"sostituito",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Incolla da Word",instructions:"Incollare i contenuti da Word nella seguente casella di testo. Quando si \u00e8 deciso quali contenuti inserire, fare clic sul pulsante incolla. Per interrompere l'inserimento del testo premere il pulsante annulla.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Inserisci ancoraggio",
title:"Propriet\u00e0 ancoraggio",anchor:"Nome:",text:"Descrizione:",set:"Imposta",cancel:"Annulla",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/GroupFilter/setting/nls/strings":{configText:"Definisci i gruppi di filtro sottostanti",labels:{groupName:"Nome gruppo:",groupNameTip:"Fornisci un nome per questo gruppo di filtri. Verr\u00e0 visualizzato nell'elenco a discesa dei gruppi di filtri disponibili.",groupDesc:"Descrizione:",groupDescTip:"Fornisci una descrizione per questo gruppo di filtri",
groupOperator:"Operatore preimpostato:",groupOperatorTip:"Opzione per definire l'operatore per il filtro. Se nessun Operatore predefinito \u00e8 selezionato, il filtro utlilizzer\u00e0 l'operatore EQUALS.",groupDefault:"Valore preimpostato:",groupDefaultTip:"Opzione per digitare un valore o scegliere un valore esistente da un layer. Clicca l'icona Cerca per sfogliare i layer.",sameLayerAppend:"Quando un layer \u00e8 elencato pi\u00f9 di una volta:",sameLayerConjunc:"Aggiungi utilizzando:",caseSearch:"Eseguire una ricerca con distinzione maiuscole/minuscole: ",
headerTextHelp:"Fornire testo da visualizzare al di sopra della selezione del filtro"},buttons:{addNewGroup:"Aggiungi un nuovo gruppo",addNewGroupTip:"Aggiungi un nuovo gruppo di filtri",addLayer:"Aggiungi layer",addLayerTip:"Aggiungi un layer al gruppo di filtri"},inputs:{groupName:"Nome del gruppo di filtri",groupDesc:"Descrizione del gruppo",groupDefault:"Inserisci un valore predefinito",sameLayerAny:"Corrispondenza con qualsiasi espressione",sameLayerAll:"Confronta tutte le espressioni",simpleMode:"Avvia in visualizzazione semplice",
simpleModeTip:"Semplifica l'interfaccia del widget. Se selezionata, l'elenco a discesa degli operatori e i pulsanti di aggiunta dei criteri sono nascosti.",webmapAppendModeAny:"Aggiungi una qualsiasi espressione al filtro della mappa esistente",webmapAppendModeAll:"Aggiungi tutte le espressioni al filtro della mappa esistente",webmapAppendModeTip:"Opzione per aggiungere i gruppi di filtri a filtri esistenti nella mappa Web",persistOnClose:"Mantieni i filtri dopo la chiusura del widget",selectGroup:"Selezionare un gruppo da filtrare",
hideDropDown:"Nascondi l'intestazione e il filtro per 1 gruppo",hideDropDownTip:"Nascondi l'intestazione e l'elenco a discesa se viene configurato solo 1 gruppo di filtri",optionsMode:"Nascondi le opzoni widget",optionsModeTip:"Opzione per esporre impostazioni widget aggiuntive. Se selezionata, il salvataggio e il caricamento dei filtri predefiniti e il mantenimento del filtro dopo la chiusura del widget vengono nascosti dall'interfaccia.",optionOR:"O",optionAND:"E",optionEQUAL:"UGUALE A",optionNOTEQUAL:"DIVERSO DA",
optionGREATERTHAN:"MAGGIORE DI",optionGREATERTHANEQUAL:"MAGGIORE DI O UGUALE A",optionLESSTHAN:"MINORE DI",optionLESSTHANEQUAL:"MINORE DI O UGUALE A",optionSTART:"INIZIA CON",optionEND:"TERMINA CON",optionLIKE:"CONTIENE",optionLIKESPECIFIC:"CONTIENE VALORI SPECIFICI",optionNOTLIKESPECIFIC:"NON CONTIENE VALORI SPECIFICI",optionNOTLIKE:"NON CONTIENE",optionONORBEFORE:"FINO AL GIORNO",optionONORAFTER:"DAL GIORNO",optionNONE:"NESSUNO"},tables:{layer:"Livelli",layerTip:"Nome del layer come definito nella mappa.",
field:"Campi",fieldTip:"Campo rispetto al quale \u00e8 possibile filtrare il layer.",value:"Usa valore",valueTip:"Opzione per utilizzare i valori dell'elenco a discesa dal layer. Se nessun layer utilizza questi parametri, una casella testo normale verr\u00e0 presentata all'utente.",zoomTo:"Zoom al risultato",zoomTip:"Opzione per effettuare lo zoom all'estensione delle feature dopo l'applicazione del filtro",action:"Pu\u00f2 eliminare",actionTip:"Rimuovere layer dal set di filtri."},popupHeader:{label:"Scegli un Valore preimpostato"},
errors:{noGroups:"\u00c8 necessario almeno un gruppo.",noGroupName:"Uno o pi\u00f9 nomi gruppo mancanti.",noDuplicates:"Uno o pi\u00f9 nomi gruppo sono duplicati.",noRows:"\u00c8 necessaria almeno una riga nella tabella.",noLayers:"Nessun layer nella mappa."},picker:{description:"Trova il valore preimpostato per questo gruppo.",layer:"Seleziona un layer",layerTip:"Nome del layer come definito nella mappa Web.",field:"Seleziona un campo",fieldTip:"Campo rispetto al quale verr\u00e0 impostato il valore preimpostato.",
value:"Seleziona un valore",valueTip:"Valore che verr\u00e0 usato come predefinito del widget."},_localized:{}}});