// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Podebljano",copy:"Kopiraj",cut:"Iseci","delete":"Izbri\u0161i",indent:"Uvla\u010denje ",insertHorizontalRule:"Horizontalna linija vodilja",insertOrderedList:"Numerisana lista",insertUnorderedList:"Lista sa znakovima za nabrajanje",italic:"Kurzivno",justifyCenter:"Poravnaj po centru",justifyFull:"Poravnaj obostrano",justifyLeft:"Poravnaj levo",justifyRight:"Poravnaj desno",outdent:"Izvla\u010denje",paste:"Nalepi",redo:"Ponovi radnju",removeFormat:"Ukloni format",
selectAll:"Izaberi sve",strikethrough:"Precrtani tekst",subscript:"Indeksni tekst",superscript:"Eksponentni tekst",underline:"Podvu\u010deno",undo:"Opozovi radnju",unlink:"Ukloni link",createLink:"Kreiraj link",toggleDir:"Uklju\u010di/isklju\u010di smer",insertImage:"Umetni sliku",insertTable:"Umetni/uredi tabelu",toggleTableBorder:"Uklju\u010di/isklju\u010di ivicu tabele",deleteTable:"Izbri\u0161i tabelu",tableProp:"Svojstva tabele",htmlToggle:"HTML izvor",foreColor:"Boja prednjeg plana",hiliteColor:"Boja pozadine",
plainFormatBlock:"Stil pasusa",formatBlock:"Stil pasusa",fontSize:"Veli\u010dina fonta",fontName:"Ime fonta",tabIndent:"Uvla\u010denje kartice",fullScreen:"Uklju\u010di/isklju\u010di prikaz preko celog ekrana",viewSource:"Prika\u017ei HTML izvor",print:"\u0160tampaj",newPage:"Nova stranica",systemShortcut:"Radnja \u201e${0}\u201c je dostupna u pregleda\u010du samo pomo\u0107u tasterskih pre\u010dica. Koristite ${1}.",ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Veli\u010dina",
fontName:"Font",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",monospace:"jednorazma\u010dni",cursive:"kurziv",fantasy:"fantazija",noFormat:"Bez formata",p:"Pasus",h1:"Naslov",h2:"Podnaslov",h3:"Pod-podnaslov",pre:"Preformatirano",1:"xx-malo",2:"x-malo",3:"malo",4:"srednje",5:"veliko",6:"x-veliko",7:"xx-veliko",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Pregled",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Prona\u0111i:",findTooltip:"Unesite tekst koji treba prona\u0107i",
replaceLabel:"Zameni sa:",replaceTooltip:"Unesite zamenski tekst",findReplace:"Prona\u0111i i zameni",matchCase:"Podudaranje malih i velikih slova",matchCaseTooltip:"Podudaranje malih i velikih slova",backwards:"Unazad",backwardsTooltip:"Pretra\u017eite tekst unazad",replaceAllButton:"Zameni sve",replaceAllButtonTooltip:"Zamenjuje sav tekst",findButton:"Prona\u0111i",findButtonTooltip:"Prona\u0111ite tekst",replaceButton:"Zameni",replaceButtonTooltip:"Zamenite tekst",replaceDialogText:"Zamenjeno ${0} pojava.",
eofDialogText:"Poslednja pojava ${0}",eofDialogTextFind:"prona\u0111eno",eofDialogTextReplace:"zamenjeno",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Nalepi iz programa Word",instructions:"Nalepite sadr\u017eaj iz programa Word u okvir za tekst ispod.  Kada ste zadovoljni sa sadr\u017eajem za umetanje, kliknite na dugme Nalepi.  Da otka\u017eete umetanje teksta, kliknite na dugme Otka\u017ei.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Umetni sidro",
title:"Svojstva sidra",anchor:"Ime:",text:"Opis:",set:"Podesi",cancel:"Otka\u017ei",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Citat pasusa",_localized:{}},"widgets/GroupFilter/setting/nls/strings":{configText:"Defini\u0161ite svoje grupe filtera u nastavku",labels:{groupName:"Naziv grupe:",groupNameTip:"Dajte naziv ovoj grupi filtera. On \u0107e se prikazati na padaju\u0107oj listi dostupnih grupa filtera.",groupDesc:"Opis:",groupDescTip:"Dodajte opis ovoj grupi filtera",groupOperator:"Unapred postavljeni operater:",
groupOperatorTip:"Izaberite da unapred odre\u0111ujete operatera filtera. Ako nije izabrana opcija Podesi operatera unapred, filter \u0107e iskoristiti funkciju JEDNAKO JE operater.",groupDefault:"Unapred postavljena vrednost:",groupDefaultTip:"Izaberite da otkucate vrednost ili izaberite postoje\u0107u vrednost iz sloja. Kliknite na ikonicu Pretraga da biste pretra\u017eili slojeve.",sameLayerAppend:"Kada je sloj naveden vi\u0161e puta:",sameLayerConjunc:"Dodaj pomo\u0107u:",caseSearch:"Izvr\u0161i pretragu koja razlikuje velika i mala slova: ",
headerTextHelp:"Obezbedite tekst za prikaz iznad izbora filtera"},buttons:{addNewGroup:"Dodaj novu grupu",addNewGroupTip:"Dodajte novu grupu filtera",addLayer:"Dodaj sloj",addLayerTip:"Dodajte sloj grupi filtera"},inputs:{groupName:"Naziv grupe filtera",groupDesc:"Opis grupe",groupDefault:"Unesite unapred definisanu vrednost",sameLayerAny:"Tra\u017ei podudaranje bilo kog izraza",sameLayerAll:"Uklopi sve izraze",simpleMode:"Zapo\u010dnite jednostavni prikaz",simpleModeTip:"Pojednostavite interfejs vid\u017eeta. Kada se \u0161tikliraju, padaju\u0107a lista operatera i dugmad za dodavanje kriterijuma \u0107e biti sakriveni.",
webmapAppendModeAny:"Dodaj bilo koji od izraza u postoje\u0107i filter mape",webmapAppendModeAll:"Dodaj sve izraze u postoje\u0107i filter mape",webmapAppendModeTip:"Izaberite da grupe filtera pridodate postoje\u0107im filterima na veb mapi",persistOnClose:"O\u010duvajte filtere nakon zatvaranja vid\u017eeta",selectGroup:"Izaberite grupu za filtriranje",hideDropDown:"Sakrijte zaglavlje i filter za 1 grupu",hideDropDownTip:"Sakrijte zaglavlje i padaju\u0107u listu ako je samo 1 grupa filtera konfigurisana",
optionsMode:"Sakrijte opcije vid\u017eeta",optionsModeTip:"Izaberite da izlo\u017eite dodatne postavke vid\u017eeta. Ako su \u0161tiklirane, opcije \u010duvanja i u\u010ditavanja unapred definisanih filtera i o\u010duvanja filtera nakon zatvaranja vid\u017eeta bi\u0107e sakrivene sa interfejsa.",optionOR:"ILI",optionAND:"I",optionEQUAL:"JEDNAKO JE",optionNOTEQUAL:"NIJE JEDNAKO",optionGREATERTHAN:"VE\u0106E OD",optionGREATERTHANEQUAL:"VE\u0106E OD ILI JEDNAKO",optionLESSTHAN:"MANJE OD",optionLESSTHANEQUAL:"MANJE OD ILI JEDNAKO",
optionSTART:"PO\u010cINJE SA",optionEND:"ZAVR\u0160AVA SE SA",optionLIKE:"SADR\u017dI",optionLIKESPECIFIC:"SADR\u017dI SPECIFI\u010cNE VREDNOSTI",optionNOTLIKESPECIFIC:"NE SADR\u017dI SPECIFI\u010cNE VREDNOSTI",optionNOTLIKE:"NE SADR\u017dI",optionONORBEFORE:"JE NA ILI PRE",optionONORAFTER:"JE NA ILI POSLE",optionNONE:"NI\u0160TA"},tables:{layer:"Slojevi",layerTip:"Ime sloja kako je definisano na mapi.",field:"Polja",fieldTip:"Polje po kojem \u0107e se sloj filtrirati.",value:"Koristi vrednost",valueTip:"Opcija za kori\u0161\u0107enje vrednosti iz padaju\u0107e liste iz sloja. Ako nijedan sloj ne koristi ovaj parametar, korisniku se prikazuje obi\u010dno tekstualno polje.",
zoomTo:"Zumirajte rezultat",zoomTip:"Izaberite da zumirate obuhvat geoobjekata nakon primene filtera",action:"Izbri\u0161i",actionTip:"Uklonite sloj iz skupa filtera."},popupHeader:{label:"Izaberite opciju Unapred pode\u0161ena vrednost"},errors:{noGroups:"Treba vam barem jedna grupa.",noGroupName:"Imena jedne ili vi\u0161e grupa nedostaju.",noDuplicates:"Imena jedne ili vi\u0161e grupa su duplirana.",noRows:"Treba vam barem jedan red u tabeli.",noLayers:"Nemate slojeva u mapi."},picker:{description:"Prona\u0111ite unapred pode\u0161enu vrednost za ovu grupu.",
layer:"Izaberi sloj",layerTip:"Ime sloja kako je definisano na veb mapi.",field:"Izaberi polje",fieldTip:"Polje iz kojeg \u0107e biti pode\u0161ena unapred postavljena vrednost.",value:"Izaberi vrednost",valueTip:"Vrednost koja \u0107e biti podrazumevana za vid\u017eet."},_localized:{}}});