// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Tebal",copy:"Salin",cut:"Potong","delete":"Hapus",indent:"Inden",insertHorizontalRule:"Penggaris horisontal",insertOrderedList:"Daftar Bernomor",insertUnorderedList:"Daftar Poin",italic:"Miring",justifyCenter:"Rata Tengah",justifyFull:"Rata Kanan Kiri",justifyLeft:"Rata Kiri",justifyRight:"Rata Kanan",outdent:"Hapus spasi di depan",paste:"Tempel",redo:"Ulangi",removeFormat:"Hapus Format",selectAll:"Pilih Semua",strikethrough:"Coretan",subscript:"Subskrip",
superscript:"Superskrip",underline:"Garis Bawah",undo:"Batalkan",unlink:"Hapus Tautan",createLink:"Buat Tautan",toggleDir:"Ubah Arah",insertImage:"Masukkan Gambar",insertTable:"Masukkan/Edit Tabel",toggleTableBorder:"Ubah Tepi Tabel",deleteTable:"Hapus Tabel",tableProp:"Properti Tabel",htmlToggle:"Sumber HTML",foreColor:"Warna Latar Depan",hiliteColor:"Warna Latar Belakang",plainFormatBlock:"Gaya Paragraf",formatBlock:"Gaya Paragraf",fontSize:"Ukuran Font",fontName:"Nama Font",tabIndent:"Inden Tab",
fullScreen:"Beralih ke Layar Penuh",viewSource:"Lihat Sumber HTML",print:"Cetak",newPage:"Halaman Baru",systemShortcut:'Tindakan "${0}" hanya tersedia pada peramban Anda menggunakan jalan pintas keyboard. Gunakan ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Ukuran",fontName:"Font",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"None",p:"Paragraf",h1:"Judul",
h2:"Sub Judul",h3:"Sub sub judul",pre:"Praformat",1:"xx-kecil",2:"x-kecil",3:"kecil",4:"medium",5:"besar",6:"x-besar",7:"xx-besar",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Pratinjau",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Temukan:",findTooltip:"Masukkan teks untuk menemukan",replaceLabel:"Ganti dengan:",replaceTooltip:"Masukkan teks untuk mengganti",findReplace:"Temukan dan Ganti",matchCase:"Cocokkan huruf",matchCaseTooltip:"Cocokkan huruf",backwards:"Mundur",
backwardsTooltip:"Mencari mundur teks",replaceAllButton:"Ganti Semua",replaceAllButtonTooltip:"Ganti semua teks",findButton:"Temukan",findButtonTooltip:"Temukan teks",replaceButton:"Ganti",replaceButtonTooltip:"Ganti teks",replaceDialogText:"Terjadi penggantian ${0}.",eofDialogText:"${0} terakhir kali terjadi",eofDialogTextFind:"Ditemukan",eofDialogTextReplace:"Diganti",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Tempel Dari Word",instructions:"Tempelkan konten dari Word ke dalam kotak teks di bawah.  Setelah Anda merasa yakin dengan konten yang disisipkan, tekan tombol tempel.  Untuk membatalkan penyisipan teks, tekan tombol batal.",
_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Masukkan Jangkar",title:"Properti Jangkar",anchor:"Nama:",text:"Deskripsi:",set:"Atur",cancel:"Batal",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/GroupFilter/setting/nls/strings":{configText:"Tentukan grup filter Anda di bawah",labels:{groupName:"Nama Grup:",groupNameTip:"Berikan nama untuk grup filter ini. Ini akan ditampilkan dalam drop-down grup filter yang tersedia.",
groupDesc:"Deskripsi:",groupDescTip:"Berikan deskripsi untuk grup filter ini",groupOperator:"Operator Pratata:",groupOperatorTip:"Opsi untuk menentukan terlebih dahulu operator untuk filter. Jika Operator Prasetel tidak dipilih, filter akan menggunakan operator SAMA DENGAN.",groupDefault:"Nilai Pratata:",groupDefaultTip:"Opsi untuk mengetik nilai atau memilih nilai yang ada dari layer. Klik ikon Pencarian untuk menelusuri layer.",sameLayerAppend:"Jika layer dicantumkan lebih dari sekali:",sameLayerConjunc:"Lampirkan Menggunakan:",
caseSearch:"Lakukan pencarian yang sensitif terhadap huruf besar dan kecil: ",headerTextHelp:"Berikan teks untuk menampilkan pilihan filter di atas"},buttons:{addNewGroup:"Tambahkan Grup Baru",addNewGroupTip:"Tambahkan grup filter baru",addLayer:"Tambahkan Layer",addLayerTip:"Tambahkan layer ke grup filter"},inputs:{groupName:"Nama grup filter",groupDesc:"Deskripsi untuk grup",groupDefault:"Masukkan nilai yang sudah ditentukan sebelumnya",sameLayerAny:"Cocokkan ekspresi apa pun",sameLayerAll:"Cocokkan semua ekspresi",
simpleMode:"Mulai dalam tampilan sederhana",simpleModeTip:"Sederhanakan antarmuka widget. Jika dicentang, daftar drop-down operator dan tombol tambahkan kriteria akan disembunyikan.",webmapAppendModeAny:"Tambahkan ekspresi apa saja ke filter peta yang ada",webmapAppendModeAll:"Tambahkan semua ekspresi ke filter peta",webmapAppendModeTip:"Opsi untuk melampirkan grup filter ke filter yang ada dalam web map",persistOnClose:"Pertahankan filter setelah widget ditutup",selectGroup:"Pilih Grup untuk Difilter",
hideDropDown:"Sembunyikan header dan filter untuk 1 grup",hideDropDownTip:"Sembunyikan header dan drop-down jika hanya 1 grup filter yang dikonfigurasikan",optionsMode:"Sembunyikan opsi widget",optionsModeTip:"Opsi untuk mengekspos pengaturan widget tambahan. Jika dicentang, menyimpan dan memuat filter yang ditentukan sebelumnya dan mempertahankan filter setelah widget ditutup akan disembunyikan dari antarmuka.",optionOR:"ATAU",optionAND:"DAN",optionEQUAL:"SEBANDING",optionNOTEQUAL:"TIDAK SEBANDING",
optionGREATERTHAN:"LEBIH BESAR DARI",optionGREATERTHANEQUAL:"LEBIH BESAR DARI ATAU SEBANDING",optionLESSTHAN:"KURANG DARI",optionLESSTHANEQUAL:"KURANG DARI ATAU SEBANDING",optionSTART:"MULAI DENGAN",optionEND:"BERAKHIR DENGAN",optionLIKE:"BERISI",optionLIKESPECIFIC:"BERISI NILAI SPESIFIK",optionNOTLIKESPECIFIC:"TIDAK BERISI NILAI SPESIFIK",optionNOTLIKE:"TIDAK BERISI",optionONORBEFORE:"PADA ATAU SEBELUM",optionONORAFTER:"PADA ATAU SESUDAH",optionNONE:"TIDAK ADA"},tables:{layer:"Layer",layerTip:"Nama layer sesuai yang ditentukan di peta.",
field:"Kolom",fieldTip:"Kolom yang menjadi tempat layer akan difilter.",value:"Gunakan Nilai",valueTip:"Opsi untuk menggunakan nilai daftar drop-down dari layer. Jika tidak ada layer yang menggunakan parameter ini, kotak teks biasa akan disajikan kepada pengguna.",zoomTo:"Perbesar hasil",zoomTip:"Opsi untuk zoom hingga ke jangkauan fitur setelah filter diterapkan",action:"Hapus",actionTip:"Buang layer dari rangkaian filter."},popupHeader:{label:"Pilih Nilai Prasetel"},errors:{noGroups:"Anda perlu setidaknya satu grup.",
noGroupName:"Satu atau lebih nama grup tidak ada.",noDuplicates:"Satu atau lebih nama grup digandakan.",noRows:"Anda perlu setidaknya satu baris dalam tabel.",noLayers:"Tidak ada layer di peta Anda."},picker:{description:"Temukan nilai prasetel untuk grup ini.",layer:"Pilih Layer",layerTip:"Nama layer sesuai yang ditentukan di web map.",field:"Pilih Kolom",fieldTip:"Kolom asal dimana nilai prasetel akan diatur.",value:"Pilih Nilai",valueTip:"Nilai yang akan menjadi default widget."},_localized:{}}});