// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Gras",copy:"Copier",cut:"Couper","delete":"Supprimer",indent:"Retrait",insertHorizontalRule:"R\u00e8gle horizontale",insertOrderedList:"Liste num\u00e9rot\u00e9e",insertUnorderedList:"Liste \u00e0 puces",italic:"Italique",justifyCenter:"Aligner au centre",justifyFull:"Justifier",justifyLeft:"Aligner \u00e0 gauche",justifyRight:"Aligner \u00e0 droite",outdent:"Retrait n\u00e9gatif",paste:"Coller",redo:"R\u00e9tablir",removeFormat:"Supprimer la mise en forme",
selectAll:"S\u00e9lectionner tout",strikethrough:"Barrer",subscript:"Indice",superscript:"Exposant",underline:"Souligner",undo:"Annuler",unlink:"Supprimer le lien",createLink:"Cr\u00e9er un lien",toggleDir:"Changer de sens",insertImage:"Ins\u00e9rer une image",insertTable:"Ins\u00e9rer/Modifier un tableau",toggleTableBorder:"Afficher/Masquer la bordure du tableau",deleteTable:"Supprimer le tableau",tableProp:"Propri\u00e9t\u00e9 du tableau",htmlToggle:"Source HTML",foreColor:"Couleur avant-plan",
hiliteColor:"Couleur arri\u00e8re-plan",plainFormatBlock:"Style de paragraphe",formatBlock:"Style de paragraphe",fontSize:"Taille de police",fontName:"Nom de police",tabIndent:"Retrait de tabulation",fullScreen:"Basculer en plein \u00e9cran",viewSource:"Afficher la source HTML",print:"Imprimer",newPage:"Nouvelle page",systemShortcut:'Action "${0}" uniquement disponible dans votre navigateur via un raccourci clavier. Utilisez ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Taille",
fontName:"Police",formatBlock:"Mise en forme",serif:"serif","sans-serif":"sans serif",monospace:"espacement fixe",cursive:"cursive",fantasy:"fantaisie",noFormat:"N\u00e9ant",p:"Paragraphe",h1:"En-t\u00eate",h2:"Sous-en-t\u00eate",h3:"Sous-sous-en-t\u00eate",pre:"Pr\u00e9-mise en forme",1:"tr\u00e8s tr\u00e8s petite",2:"tr\u00e8s petite",3:"petite",4:"moyenne",5:"grande",6:"tr\u00e8s grande",7:"tr\u00e8s tr\u00e8s grande",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Aper\u00e7u",_localized:{}},
"dojox/editor/plugins/nls/FindReplace":{findLabel:"Rechercher :",findTooltip:"Entrez le texte \u00e0 rechercher",replaceLabel:"Remplacer par :",replaceTooltip:"Entrez le texte de remplacement",findReplace:"Rechercher et remplacer",matchCase:"Respecter la casse",matchCaseTooltip:"Respecter la casse",backwards:"Vers l'arri\u00e8re",backwardsTooltip:"Recherchez le texte vers l'arri\u00e8re",replaceAllButton:"Remplacer tout",replaceAllButtonTooltip:"Remplacez tout le texte",findButton:"Rechercher",findButtonTooltip:"Recherchez le texte",
replaceButton:"Remplacer",replaceButtonTooltip:"Remplacez le texte",replaceDialogText:"${0} occurrence(s) remplac\u00e9e(s)",eofDialogText:"Derni\u00e8re occurrence ${0}",eofDialogTextFind:"trouv\u00e9",eofDialogTextReplace:"remplac\u00e9",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Coller depuis Word",instructions:"Collez le contenu Word dans la zone de texte ci-dessous. Quand le contenu \u00e0 ins\u00e9rer vous convient, appuyez sur le bouton Coller. Pour annuler l'insertion du texte, utilisez le bouton Annuler.",
_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Ins\u00e9rer un point d'ancrage",title:"Propri\u00e9t\u00e9s du point d'ancrage",anchor:"Nom :",text:"Description :",set:"D\u00e9finir",cancel:"Annuler",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Bloc de citation",_localized:{}},"widgets/GroupFilter/setting/nls/strings":{configText:"D\u00e9finir vos groupes de filtres ci-dessous",labels:{groupName:"Nom du groupe\u00a0:",groupNameTip:"Attribuez un nom \u00e0 ce groupe de filtres. Il s\u2019affichera dans la liste d\u00e9roulante des groupes de filtres disponibles.",
groupDesc:"Description :",groupDescTip:"Fournir une description de ce groupe de filtres",groupOperator:"Op\u00e9rateur pr\u00e9d\u00e9fini\u00a0:",groupOperatorTip:"Option permettant de pr\u00e9d\u00e9finir l\u2019op\u00e9rateur du filtre. Si aucun op\u00e9rateur pr\u00e9d\u00e9fini n\u2019est s\u00e9lectionn\u00e9, le filtre utilise l\u2019op\u00e9rateur \u00c9GAL.",groupDefault:"Valeur pr\u00e9d\u00e9finie\u00a0:",groupDefaultTip:"Option permettant de saisir une valeur ou de choisir une valeur existante dans une couche. Cliquez sur l\u2019ic\u00f4ne de recherche pour parcourir les couches.",
sameLayerAppend:"Lorsqu\u2019une couche est r\u00e9pertori\u00e9e plusieurs fois\u00a0:",sameLayerConjunc:"Ajouter avec\u00a0:",caseSearch:"Effectuer une recherche en tenant compte de la casse : ",headerTextHelp:"Indiquer le texte \u00e0 afficher au-dessus de la s\u00e9lection des filtres"},buttons:{addNewGroup:"Ajouter un nouveau groupe",addNewGroupTip:"Ajouter un nouveau groupe de filtres",addLayer:"Ajouter une couche",addLayerTip:"Ajouter une couche au groupe de filtres"},inputs:{groupName:"Nom du groupe de filtres",
groupDesc:"Description du groupe",groupDefault:"Saisir une valeur pr\u00e9d\u00e9finie",sameLayerAny:"Respecter l\u2019une des expressions",sameLayerAll:"Correspondre \u00e0 toutes les expressions",simpleMode:"Commencer dans la vue simple",simpleModeTip:"Simplifiez l\u2019interface du widget. Si vous s\u00e9lectionnez cette option, la liste d\u00e9roulante des op\u00e9rateurs et les boutons d\u2019ajout de crit\u00e8re sont masqu\u00e9s.",webmapAppendModeAny:"Ajouter l\u2019une des expressions au filtre de carte existant",
webmapAppendModeAll:"Ajouter toutes les expressions au filtre de carte existant",webmapAppendModeTip:"Option permettant d\u2019ajouter des groupes de filtres \u00e0 des filtres existants dans la carte Web",persistOnClose:"Conserver les filtres apr\u00e8s la fermeture du widget",selectGroup:"S\u00e9lectionner un groupe \u00e0 filtrer",hideDropDown:"Masquer l\u2019en-t\u00eate et le filtre pour un groupe",hideDropDownTip:"Masquer l\u2019en-t\u00eate et la liste d\u00e9roulante si un seul groupe de filtres est configur\u00e9",
optionsMode:"Masquer les options de widget",optionsModeTip:"Option permettant de pr\u00e9senter des param\u00e8tres de widget suppl\u00e9mentaires. Si l\u2019option est s\u00e9lectionn\u00e9e, l\u2019enregistrement et le chargement de filtres pr\u00e9d\u00e9finis, ainsi que la conservation du filtre apr\u00e8s la fermeture du widget, sont masqu\u00e9s dans l\u2019interface.",optionOR:"OU",optionAND:"ET",optionEQUAL:"EGAL A",optionNOTEQUAL:"DIFFERENT DE",optionGREATERTHAN:"SUPERIEUR A",optionGREATERTHANEQUAL:"SUPERIEUR OU EGAL A",
optionLESSTHAN:"INFERIEUR A",optionLESSTHANEQUAL:"INFERIEUR OU EGAL A",optionSTART:"COMMENCE PAR",optionEND:"SE TERMINE PAR",optionLIKE:"CONTIENT",optionLIKESPECIFIC:"CONTIENT DES VALEURS SP\u00c9CIFIQUES",optionNOTLIKESPECIFIC:"NE CONTIENT PAS DE VALEURS SP\u00c9CIFIQUES",optionNOTLIKE:"NE CONTIENT PAS",optionONORBEFORE:"LE OU AVANT",optionONORAFTER:"LE OU APRES",optionNONE:"AUCUN"},tables:{layer:"Couches",layerTip:"Nom de la couche selon la d\u00e9finition de la carte.",field:"Champs",fieldTip:"Champ en fonction duquel la couche va \u00eatre filtr\u00e9e.",
value:"Utiliser la valeur",valueTip:"Option permettant d'utiliser les valeurs de la liste d\u00e9roulante de la couche. Si aucune couche n'utilise ce param\u00e8tre, une simple zone de texte est pr\u00e9sent\u00e9e \u00e0 l'utilisateur.",zoomTo:"Zoom sur le r\u00e9sultat",zoomTip:"Option permettant d\u2019appliquer un zoom sur l\u2019\u00e9tendue des entit\u00e9s une fois le filtre appliqu\u00e9",action:"Effacer",actionTip:"Supprimez la couche du filtre d\u00e9fini."},popupHeader:{label:"Choisir une valeur pr\u00e9d\u00e9finie"},
errors:{noGroups:"Vous avez besoin d'au moins un groupe.",noGroupName:"Un ou plusieurs noms de groupe ne sont pas indiqu\u00e9s.",noDuplicates:"Un ou plusieurs noms de groupe sont dupliqu\u00e9s.",noRows:"Vous avoir besoin d'au moins une ligne dans la table.",noLayers:"Votre carte ne poss\u00e8de aucune couche."},picker:{description:"Recherchez la valeur pr\u00e9d\u00e9finie pour ce groupe.",layer:"S\u00e9lectionner une couche",layerTip:"Nom de la couche selon la d\u00e9finition de la carte Web.",
field:"S\u00e9lectionner un champ",fieldTip:"Champ \u00e0 partir duquel la valeur pr\u00e9d\u00e9finie va \u00eatre configur\u00e9e.",value:"S\u00e9lectionner une valeur",valueTip:"Valeur qui sera la valeur par d\u00e9faut du widget."},_localized:{}}});