// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/Stateful dojo/_base/lang dojo/Deferred esri/toolbars/draw esri/geometry/Point esri/graphic esri/geometry/geometryEngineAsync esri/units esri/tasks/GeometryService esri/SpatialReference esri/request esri/tasks/ProjectParameters esri/geometry/webMercatorUtils jimu/portalUtils".split(" "),function(p,q,e,k,r,n,t,u,f,v,l,w,x,h,y){return p([r,q],{startPoint:null,_setStartPoint:function(a){this._set("startPoint",a)},endPoint:null,_setEndPoint:function(a){this._set("endPoint",
a)},lengthUnit:"meters",_setLengthUnit:function(a){this._set("lengthUnit",a)},angleUnit:"degrees",_setAngle:function(a){this._set("angleUnit",a)},isDiameter:!0,canProjectLocally:!1,constructor:function(){u.isSimple(new n({x:-122.65,y:45.53,spatialReference:{wkid:4326}}))},initGeometryService:function(){var a=this.appConfig.geometryService;a||(a="//utility.arcgisonline.com/arcgis/rest/services/Geometry/GeometryServer");this._fetchPortalGeomSrvcUrl().then(e.hitch(this,function(c){""===e.trim(c)&&(c=
a);this.geomService=new v(c)}));var b=new n({x:0,y:0,spatialReference:this.map.spatialReference});h.canProject(b,new l(3857))&&(this.canProjectLocally=!0)},getRadiusUnitType:function(){var a=f.METERS;switch(this.lengthUnit){case "meters":a=f.METERS;break;case "feet":a=f.FEET;break;case "kilometers":a=f.KILOMETERS;break;case "miles":a=f.MILES;break;case "nautical-miles":a=f.NAUTICAL_MILES;break;case "yards":a=f.YARDS}return a},addStartGraphic:function(a,b){this.removeStartGraphic();this.startGraphic=
new t(a,b);this.map.graphics.add(this.startGraphic)},removeStartGraphic:function(){this.startGraphic&&this.map.graphics.remove(this.startGraphic);this.startGraphic=null},_processAfterMapClick:function(a){var b=new k;4326!==a.spatialReference.wkid?this.getDDPoint(a).then(e.hitch(this,function(c){b.resolve(c)}),function(c){b.reject(c)}):b.resolve(a);return b},getDDPoint:function(a){var b=new k,c=new l(3857);h.canProject(a,c)?b.resolve(h.webMercatorToGeographic(h.project(a,c))):(new w({url:this.geomService.url+
"/findTransformations",content:{f:"json",inSR:a.spatialReference.wkid,outSR:4326},handleAs:"json",callbackParamName:"callback"},{usePost:!1})).then(e.hitch(this,function(d){d=d&&d.transformations?d.transformations:void 0;this.projectPointForDD(b,a,4326,d&&0<d.length?d[0].wkid:void 0)}),e.hitch(this,function(){this.projectPointForDD(b,a,4326,null)}));return b},projectPointForDD:function(a,b,c,d){var g=new x;g.outSR=new l(c);g.geometries=[b];d&&(g.transformForward=!0,g.transformation=d);this.geomService.project(g,
e.hitch(this,function(m){a.resolve(m[0])}),function(m){a.reject(m)})},getProjectedGeometry:function(a,b){var c=new k;if(h.canProject(a,b)){var d=h.project(a,b);c.resolve(d)}else this.geomService.project([a],b,function(g){d=g[0];c.resolve(d)});return c.promise},_fetchPortalGeomSrvcUrl:function(){var a=new k;this.appConfig.portalUrl&&""!==e.trim(this.appConfig.portalUrl)?y.getPortalSelfInfo(this.appConfig.portalUrl).then(e.hitch(this,function(b){b=b&&b.helperServices;var c="";b&&b.geometry&&b.geometry.url&&
""!==b.geometry.url&&(c=b.geometry.url);a.resolve(c)}),e.hitch(this,function(){a.resolve("")})):a.resolve("");return a.promise}})});