//>>built
/*
 Sortable 1.8.4 - MIT | git://github.com/SortableJS/Sortable.git */
!function(y){"function"==typeof define&&define.amd?define(y):"undefined"!=typeof module&&void 0!==module.exports?module.exports=y():window.Sortable=y()}(function(){function y(a,b){if(!a||!a.nodeType||1!==a.nodeType)throw"Sortable: `el` must be HTMLElement, not "+{}.toString.call(a);this.el=a;this.options=b=Ta({},b);a[G]=this;var c={group:null,sort:!0,disabled:!1,store:null,handle:null,scroll:!0,scrollSensitivity:30,scrollSpeed:10,bubbleScroll:!0,draggable:/[uo]l/i.test(a.nodeName)?"\x3eli":"\x3e*",
swapThreshold:1,invertSwap:!1,invertedSwapThreshold:null,removeCloneOnHide:!0,direction:function(){return nb(a,this.options)},ghostClass:"sortable-ghost",chosenClass:"sortable-chosen",dragClass:"sortable-drag",ignore:"a, img",filter:null,preventOnFilter:!0,animation:0,easing:null,setData:function(f,h){f.setData("Text",h.textContent)},dropBubble:!1,dragoverBubble:!1,dataIdAttr:"data-id",delay:0,touchStartThreshold:T(window.devicePixelRatio,10)||1,forceFallback:!1,fallbackClass:"sortable-fallback",
fallbackOnBody:!1,fallbackTolerance:0,fallbackOffset:{x:0,y:0},supportPointer:!1!==y.supportPointer&&("PointerEvent"in window||window.navigator&&"msPointerEnabled"in window.navigator),emptyInsertThreshold:5},e;for(e in c)e in b||(b[e]=c[e]);for(var d in ob(b),this)"_"===d.charAt(0)&&"function"==typeof this[d]&&(this[d]=this[d].bind(this));(this.nativeDraggable=!b.forceFallback&&Kb)&&(this.options.touchStartThreshold=1);b.supportPointer?u(a,"pointerdown",this._onTapStart):(u(a,"mousedown",this._onTapStart),
u(a,"touchstart",this._onTapStart));this.nativeDraggable&&(u(a,"dragover",this),u(a,"dragenter",this));ia.push(this.el);b.store&&b.store.get&&this.sort(b.store.get(this)||[])}function K(a,b,c,e){if(a){c=c||n;do{if(null!=b&&("\x3e"===b[0]&&a.parentNode===c&&pb(a,b.substring(1))||pb(a,b))||e&&a===c)return a;if(a===c)break}while(a=(d=a).host&&d!==n&&d.host.nodeType?d.host:d.parentNode)}var d;return null}function u(a,b,c){a.addEventListener(b,c,qb)}function v(a,b,c){a.removeEventListener(b,c,qb)}function P(a,
b,c){if(a&&b)if(a.classList)a.classList[c?"add":"remove"](b);else{var e=(" "+a.className+" ").replace(rb," ").replace(" "+b+" "," ");a.className=(e+(c?" "+b:"")).replace(rb," ")}}function p(a,b,c){var e=a&&a.style;if(e){if(void 0===c)return n.defaultView&&n.defaultView.getComputedStyle?c=n.defaultView.getComputedStyle(a,""):a.currentStyle&&(c=a.currentStyle),void 0===b?c:c[b];b in e||-1!==b.indexOf("webkit")||(b="-webkit-"+b);e[b]=c+("string"==typeof c?"":"px")}}function Ea(a){var b="";do{var c=p(a,
"transform");c&&"none"!==c&&(b=c+" "+b)}while(a=a.parentNode);return window.DOMMatrix?new DOMMatrix(b):window.WebKitCSSMatrix?new WebKitCSSMatrix(b):window.CSSMatrix?new CSSMatrix(b):void 0}function sb(a,b,c){if(a){a=a.getElementsByTagName(b);b=0;var e=a.length;if(c)for(;b<e;b++)c(a[b],b);return a}return[]}function L(a,b,c,e,d,f,h,l,k){var m,t=(a=a||b[G]).options,w="on"+c.charAt(0).toUpperCase()+c.substr(1);!window.CustomEvent||U||va?(m=n.createEvent("Event")).initEvent(c,!0,!0):m=new CustomEvent(c,
{bubbles:!0,cancelable:!0});m.to=d||b;m.from=f||b;m.item=e||b;m.clone=x;m.oldIndex=h;m.newIndex=l;m.originalEvent=k;m.pullMode=I?I.lastPutMode:void 0;b&&b.dispatchEvent(m);t[w]&&t[w].call(a,m)}function tb(a,b,c,e,d,f,h,l){var k,m,t=a[G],w=t.options.onMove;return!window.CustomEvent||U||va?(k=n.createEvent("Event")).initEvent("move",!0,!0):k=new CustomEvent("move",{bubbles:!0,cancelable:!0}),k.to=b,k.from=a,k.dragged=c,k.draggedRect=e,k.related=d||b,k.relatedRect=f||z(b),k.willInsertAfter=l,k.originalEvent=
h,a.dispatchEvent(k),w&&(m=w.call(t,k,h)),m}function Ua(a){a.draggable=!1}function Lb(){Va=!1}function Wa(a,b,c){for(var e=0,d=0,f=a.children;d<f.length;){if("none"!==f[d].style.display&&f[d]!==r&&f[d]!==g&&K(f[d],c.draggable,a,!1)){if(e===b)return f[d];e++}d++}return null}function Xa(a){for(a=a.lastElementChild;a&&(a===r||"none"===a.style.display);)a=a.previousElementSibling;return a||null}function ub(a){return ma(g)<ma(a)?1:-1}function ma(a,b){b=0;if(!a||!a.parentNode)return-1;for(;a&&(a=a.previousElementSibling);)"TEMPLATE"!==
a.nodeName.toUpperCase()&&a!==x&&b++;return b}function pb(a,b){if(a)try{if(a.matches)return a.matches(b);if(a.msMatchesSelector)return a.msMatchesSelector(b);if(a.webkitMatchesSelector)return a.webkitMatchesSelector(b)}catch(c){}return!1}function vb(a,b){return function(){if(!wa){var c=arguments,e=this;wa=pa(function(){1===c.length?a.call(e,c[0]):a.apply(e,c);wa=void 0},b)}}}function Ta(a,b){if(a&&b)for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a}function wb(a){return Ya&&Ya.dom?Ya.dom(a).cloneNode(!0):
xb?xb(a).clone(!0)[0]:a.cloneNode(!0)}function Fa(a){return pa(a,0)}function z(a,b,c,e){if(a.getBoundingClientRect||a===ca){var d,f,h,l,k,m,t;if(t=a!==ca&&a!==ea()?(f=(d=a.getBoundingClientRect()).top,h=d.left,l=d.bottom,k=d.right,m=d.height,d.width):(h=f=0,l=window.innerHeight,k=window.innerWidth,m=window.innerHeight,window.innerWidth),e&&a!==ca&&(c=c||a.parentNode,!U)){do if(c&&c.getBoundingClientRect&&"none"!==p(c,"transform")){l=c.getBoundingClientRect();f-=l.top+T(p(c,"border-top-width"));h-=
l.left+T(p(c,"border-left-width"));l=f+d.height;k=h+d.width;break}while(c=c.parentNode)}b&&a!==ca&&(b=(a=Ea(c||a))&&a.a,c=a&&a.d,a&&(l=(f/=c)+(m/=c),k=(h/=b)+(t/=b)));return{top:f,left:h,bottom:l,right:k,width:t,height:m}}}function yb(a,b){var c=ja(a,!0);for(a=z(a)[b];c;){var e=z(c)[b];if(!("top"===b||"left"===b?e<=a:a<=e))return c;if(c===ea())break;c=ja(c,!1)}return!1}function zb(a){var b=0,c=0,e=ea();if(a){do{var d=Ea(a),f=d.d;b+=a.scrollLeft*d.a;c+=a.scrollTop*f}while(a!==e&&(a=a.parentNode))}return[b,
c]}if("undefined"==typeof window||!window.document)return function(){throw Error("Sortable.js requires a window with a document");};var g,C,r,x,q,na,Za,qa,$a,ab,M,Q,Ga,I,ra,bb,cb,xa,H,Ha,sa,ya,za,Ia,B,ta,A=[],db=!1,Aa=!1,Ja=!1,ia=[],Ba=!1,Ka=!1,eb=[],rb=/\s+/g,G="Sortable"+(new Date).getTime(),ca=window,n=ca.document,T=ca.parseInt,pa=ca.setTimeout,xb=ca.jQuery||ca.Zepto,Ya=ca.Polymer,qb={capture:!1,passive:!1},U=!!navigator.userAgent.match(/(?:Trident.*rv[ :]?11\.|msie|iemobile)/i),va=!!navigator.userAgent.match(/Edge/i),
Ab=!!navigator.userAgent.match(/firefox/i),fb=!(!navigator.userAgent.match(/safari/i)||navigator.userAgent.match(/chrome/i)||navigator.userAgent.match(/android/i)),La=!!navigator.userAgent.match(/iP(ad|od|hone)/i),Bb=va||U?"cssFloat":"float",Kb="draggable"in n.createElement("div"),gb=function(){if(U)return!1;var a=n.createElement("x");return a.style.cssText="pointer-events:auto","auto"===a.style.pointerEvents}(),Va=!1,hb=!1,fa=Math.abs,Mb=Math.min,Nb=Math.max,Ma=[],nb=function(a,b){var c=p(a),e=T(c.width)-
T(c.paddingLeft)-T(c.paddingRight)-T(c.borderLeftWidth)-T(c.borderRightWidth),d=Wa(a,0,b);a=Wa(a,1,b);var f=d&&p(d);b=a&&p(a);var h=f&&T(f.marginLeft)+T(f.marginRight)+z(d).width,l=b&&T(b.marginLeft)+T(b.marginRight)+z(a).width;return"flex"===c.display?"column"===c.flexDirection||"column-reverse"===c.flexDirection?"vertical":"horizontal":"grid"===c.display?1>=c.gridTemplateColumns.split(" ").length?"vertical":"horizontal":d&&"none"!==f.float?(c="left"===f.float?"left":"right",!a||"both"!==b.clear&&
b.clear!==c?"horizontal":"vertical"):d&&("block"===f.display||"flex"===f.display||"table"===f.display||"grid"===f.display||e<=h&&"none"===c[Bb]||a&&"none"===c[Bb]&&e<h+l)?"vertical":"horizontal"},ja=function(a,b){if(!a||!a.getBoundingClientRect)return ea();var c=!1;do if(a.clientWidth<a.scrollWidth||a.clientHeight<a.scrollHeight){var e=p(a);if(a.clientWidth<a.scrollWidth&&("auto"==e.overflowX||"scroll"==e.overflowX)||a.clientHeight<a.scrollHeight&&("auto"==e.overflowY||"scroll"==e.overflowY)){if(!a||
!a.getBoundingClientRect||a===n.body)break;if(c||b)return a;c=!0}}while(a=a.parentNode);return ea()},ea=function(){return U?n.documentElement:n.scrollingElement},Cb=function(a,b,c){a.scrollLeft+=b;a.scrollTop+=c},ib=vb(function(a,b,c,e){if(b.scroll){var d=c?c[G]:window,f=b.scrollSensitivity,h=b.scrollSpeed,l=a.clientX,k=a.clientY,m=ea(),t=!1;$a!==c&&(Na(),qa=b.scroll,ab=b.scrollFn,!0===qa&&(qa=ja(c,!0),$a=qa));c=0;var w=qa;do{var D,Y,E,da,V,J,Z,aa,N=w;var R=z(N);var ha=R.top,Ca=R.bottom,Oa=R.left,
Pa=R.right,W=R.width,F=R.height;if(D=N.scrollWidth,Y=N.scrollHeight,E=p(N),Z=N.scrollLeft,aa=N.scrollTop,J=N===m?(V=W<D&&("auto"===E.overflowX||"scroll"===E.overflowX||"visible"===E.overflowX),F<Y&&("auto"===E.overflowY||"scroll"===E.overflowY||"visible"===E.overflowY)):(V=W<D&&("auto"===E.overflowX||"scroll"===E.overflowX),F<Y&&("auto"===E.overflowY||"scroll"===E.overflowY)),R=V&&(fa(Pa-l)<=f&&Z+W<D)-(fa(Oa-l)<=f&&!!Z),da=J&&(fa(Ca-k)<=f&&aa+F<Y)-(fa(ha-k)<=f&&!!aa),!A[c])for(ha=0;ha<=c;ha++)A[ha]||
(A[ha]={});A[c].vx==R&&A[c].vy==da&&A[c].el===N||(A[c].el=N,A[c].vx=R,A[c].vy=da,clearInterval(A[c].pid),!N||0==R&&0==da||(t=!0,A[c].pid=setInterval(function(){e&&0===this.layer&&(y.active._emulateDragOver(!0),y.active._onTouchMove(H,!0));var X=A[this.layer].vy?A[this.layer].vy*h:0,S=A[this.layer].vx?A[this.layer].vx*h:0;"function"==typeof ab&&"continue"!==ab.call(d,S,X,a,H,A[this.layer].el)||Cb(A[this.layer].el,S,X)}.bind({layer:c}),24)));c++}while(b.bubbleScroll&&w!==m&&(w=ja(w,!1)));db=t}},30),
Na=function(){A.forEach(function(a){clearInterval(a.pid)});A=[]},ob=function(a){function b(d,f){return function(h,l,k,m){var t=h.options.group.name&&l.options.group.name&&h.options.group.name===l.options.group.name;if(null==d&&(f||t))return!0;if(null==d||!1===d)return!1;if(f&&"clone"===d)return d;if("function"==typeof d)return b(d(h,l,k,m),f)(h,l,k,m);h=(f?h:l).options.group.name;return!0===d||"string"==typeof d&&d===h||d.join&&-1<d.indexOf(h)}}var c={},e=a.group;e&&"object"==typeof e||(e={name:e});
c.name=e.name;c.checkPull=b(e.pull,!0);c.checkPut=b(e.put);c.revertClone=e.revertClone;a.group=c},Db=function(a){g&&g.parentNode&&g.parentNode[G]&&g.parentNode[G]._computeIsAligned(a)},Eb=function(a,b){for(;!b[G];)b=b.parentNode;return a===b},Fb=function(a,b,c){for(a=a.parentNode;a&&!a[G];)a=a.parentNode;a&&a[G][c](Ta(b,{artificialBubble:!0}))},Gb=function(){!gb&&r&&p(r,"display","none")},Hb=function(){!gb&&r&&p(r,"display","")};n.addEventListener("click",function(a){if(Ja)return a.preventDefault(),
a.stopPropagation&&a.stopPropagation(),a.stopImmediatePropagation&&a.stopImmediatePropagation(),Ja=!1},!0);var wa,jb=function(a){if(a=a.touches?a.touches[0]:a,g){a:{var b=a.clientX;for(var c=a.clientY,e=0;e<ia.length;e++)if(!Xa(ia[e])){var d=z(ia[e]),f=ia[e][G].options.emptyInsertThreshold,h=c>=d.top-f&&c<=d.bottom+f;if(b>=d.left-f&&b<=d.right+f&&h){b=ia[e];break a}}b=void 0}b&&b[G]._onDragOver({clientX:a.clientX,clientY:a.clientY,target:b,rootEl:b})}};return u(n,"dragover",jb),u(n,"mousemove",jb),
u(n,"touchmove",jb),y.prototype={constructor:y,_computeIsAligned:function(a){var b;if(r&&!gb?(Gb(),b=n.elementFromPoint(a.clientX,a.clientY),Hb()):b=a.target,b=K(b,this.options.draggable,this.el,!1),!hb&&g&&g.parentNode===this.el){for(var c,e,d,f,h,l,k,m,t=this.el.children,w=0;w<t.length;w++)K(t[w],this.options.draggable,this.el,!1)&&t[w]!==b&&(t[w].sortableMouseAligned=(c=a.clientX,e=a.clientY,d=t[w],f=this._getDirection(a,null),this.options,void 0,h=z(d),l="vertical"===f?h.left:h.top,k="vertical"===
f?h.right:h.bottom,l<(m="vertical"===f?c:e)&&m<k));K(b,this.options.draggable,this.el,!0)||(sa=null);hb=!0;pa(function(){hb=!1},30)}},_getDirection:function(a,b){return"function"==typeof this.options.direction?this.options.direction.call(this,a,b,g):this.options.direction},_onTapStart:function(a){if(a.cancelable){var b,c=this,e=this.el,d=this.options,f=d.preventOnFilter,h=a.type,l=a.touches&&a.touches[0],k=(l||a).target,m=a.target.shadowRoot&&(a.path&&a.path[0]||a.composedPath&&a.composedPath()[0])||
k,t=d.filter;if(function(w){Ma.length=0;w=w.getElementsByTagName("input");for(var D=w.length;D--;){var Y=w[D];Y.checked&&Ma.push(Y)}}(e),!(U&&!a.artificialBubble&&!Eb(e,k)||g||/mousedown|pointerdown/.test(h)&&0!==a.button||d.disabled||m.isContentEditable))if(k=K(k,d.draggable,e,!1)){if(Za!==k){if(b=ma(k,d.draggable),"function"==typeof t){if(t.call(this,a,k,this))return L(c,m,"filter",k,e,e,b),void(f&&a.cancelable&&a.preventDefault())}else if(t&&(t=t.split(",").some(function(w){if(w=K(m,w.trim(),e,
!1))return L(c,w,"filter",k,e,e,b),!0})))return void(f&&a.cancelable&&a.preventDefault());d.handle&&!K(m,d.handle,e,!1)||this._prepareDragStart(a,l,k,b)}}else U&&Fb(e,a,"_onTapStart")}},_handleAutoScroll:function(a,b){if(g&&this.options.scroll){var c=a.clientX,e=a.clientY,d=n.elementFromPoint(c,e),f=this;if(b||va||U||fb){ib(a,f.options,d,b);var h=ja(d,!0);!db||ra&&c===bb&&e===cb||(ra&&clearInterval(ra),ra=setInterval(function(){if(g){var l=ja(n.elementFromPoint(c,e),!0);l!==h&&(h=l,Na(),ib(a,f.options,
h,b))}},10),bb=c,cb=e)}else{if(!f.options.bubbleScroll||ja(d,!0)===ea())return void Na();ib(a,f.options,ja(d,!1),!1)}}},_prepareDragStart:function(a,b,c,e){var d,f=this,h=f.el,l=f.options,k=h.ownerDocument;c&&!g&&c.parentNode===h&&(q=h,C=(g=c).parentNode,na=g.nextSibling,Za=c,Ga=l.group,M=e,xa={target:g,clientX:(b||a).clientX,clientY:(b||a).clientY},this._lastX=(b||a).clientX,this._lastY=(b||a).clientY,g.style["will-change"]="all",g.style.transition="",g.style.transform="",d=function(){f._disableDelayedDragEvents();
!Ab&&f.nativeDraggable&&(g.draggable=!0);f._triggerDragStart(a,b);L(f,q,"choose",g,q,q,M);P(g,l.chosenClass,!0)},l.ignore.split(",").forEach(function(m){sb(g,m.trim(),Ua)}),l.supportPointer?u(k,"pointerup",f._onDrop):(u(k,"mouseup",f._onDrop),u(k,"touchend",f._onDrop),u(k,"touchcancel",f._onDrop)),Ab&&this.nativeDraggable&&(this.options.touchStartThreshold=4,g.draggable=!0),!l.delay||this.nativeDraggable&&(va||U)?d():(u(k,"mouseup",f._disableDelayedDrag),u(k,"touchend",f._disableDelayedDrag),u(k,
"touchcancel",f._disableDelayedDrag),u(k,"mousemove",f._delayedDragTouchMoveHandler),u(k,"touchmove",f._delayedDragTouchMoveHandler),l.supportPointer&&u(k,"pointermove",f._delayedDragTouchMoveHandler),f._dragStartTimer=pa(d,l.delay)))},_delayedDragTouchMoveHandler:function(a){a=a.touches?a.touches[0]:a;Nb(fa(a.clientX-this._lastX),fa(a.clientY-this._lastY))>=Math.floor(this.options.touchStartThreshold/(this.nativeDraggable&&window.devicePixelRatio||1))&&this._disableDelayedDrag()},_disableDelayedDrag:function(){g&&
Ua(g);clearTimeout(this._dragStartTimer);this._disableDelayedDragEvents()},_disableDelayedDragEvents:function(){var a=this.el.ownerDocument;v(a,"mouseup",this._disableDelayedDrag);v(a,"touchend",this._disableDelayedDrag);v(a,"touchcancel",this._disableDelayedDrag);v(a,"mousemove",this._delayedDragTouchMoveHandler);v(a,"touchmove",this._delayedDragTouchMoveHandler);v(a,"pointermove",this._delayedDragTouchMoveHandler)},_triggerDragStart:function(a,b){b=b||("touch"==a.pointerType?a:null);!this.nativeDraggable||
b?this.options.supportPointer?u(n,"pointermove",this._onTouchMove):u(n,b?"touchmove":"mousemove",this._onTouchMove):(u(g,"dragend",this),u(q,"dragstart",this._onDragStart));try{n.selection?Fa(function(){n.selection.empty()}):window.getSelection().removeAllRanges()}catch(c){}},_dragStarted:function(a,b){if(Aa=!1,q&&g){this.nativeDraggable&&(u(n,"dragover",this._handleAutoScroll),u(n,"dragover",Db));var c=this.options;!a&&P(g,c.dragClass,!1);P(g,c.ghostClass,!0);p(g,"transform","");y.active=this;a&&
this._appendGhost();L(this,q,"start",g,q,q,M,void 0,b)}else this._nulling()},_emulateDragOver:function(a){if(H&&(this._lastX!==H.clientX||this._lastY!==H.clientY||a)){this._lastX=H.clientX;this._lastY=H.clientY;Gb();for(var b=a=n.elementFromPoint(H.clientX,H.clientY);a&&a.shadowRoot;)b=a=a.shadowRoot.elementFromPoint(H.clientX,H.clientY);if(b){do{if(b[G]&&b[G]._onDragOver({clientX:H.clientX,clientY:H.clientY,target:a,rootEl:b})&&!this.options.dragoverBubble)break;a=b}while(b=b.parentNode)}g.parentNode[G]._computeIsAligned(H);
Hb()}},_onTouchMove:function(a,b){if(xa){var c=this.options,e=c.fallbackTolerance,d=c.fallbackOffset;c=a.touches?a.touches[0]:a;var f=r&&Ea(r),h=r&&f&&f.a;f=r&&f&&f.d;var l=La&&B&&zb(B);h=(c.clientX-xa.clientX+d.x)/(h||1)+(l?l[0]-eb[0]:0)/(h||1);d=(c.clientY-xa.clientY+d.y)/(f||1)+(l?l[1]-eb[1]:0)/(f||1);d=a.touches?"translate3d("+h+"px,"+d+"px,0)":"translate("+h+"px,"+d+"px)";if(!y.active&&!Aa){if(e&&Mb(fa(c.clientX-this._lastX),fa(c.clientY-this._lastY))<e)return;this._onDragStart(a,!0)}!b&&this._handleAutoScroll(c,
!0);Ha=!0;H=c;p(r,"webkitTransform",d);p(r,"mozTransform",d);p(r,"msTransform",d);p(r,"transform",d);a.cancelable&&a.preventDefault()}},_appendGhost:function(){if(!r){var a=this.options.fallbackOnBody?n.body:q,b=z(g,!0,a,!La),c=(p(g),this.options);if(La){for(B=a;"static"===p(B,"position")&&"none"===p(B,"transform")&&B!==n;)B=B.parentNode;if(B!==n){var e=z(B,!0);b.top-=e.top;b.left-=e.left}B!==n.body&&B!==n.documentElement?(B===n&&(B=ea()),b.top+=B.scrollTop,b.left+=B.scrollLeft):B=ea();eb=zb(B)}P(r=
g.cloneNode(!0),c.ghostClass,!1);P(r,c.fallbackClass,!0);P(r,c.dragClass,!0);p(r,"box-sizing","border-box");p(r,"margin",0);p(r,"top",b.top);p(r,"left",b.left);p(r,"width",b.width);p(r,"height",b.height);p(r,"opacity","0.8");p(r,"position",La?"absolute":"fixed");p(r,"zIndex","100000");p(r,"pointerEvents","none");a.appendChild(r)}},_onDragStart:function(a,b){var c=this,e=a.dataTransfer,d=c.options;(x=wb(g)).draggable=!1;x.style["will-change"]="";this._hideClone();P(x,c.options.chosenClass,!1);c._cloneId=
Fa(function(){c.options.removeCloneOnHide||q.insertBefore(x,g);L(c,q,"clone",g)});!b&&P(g,d.dragClass,!0);b?(Ja=!0,c._loopId=setInterval(c._emulateDragOver,50)):(v(n,"mouseup",c._onDrop),v(n,"touchend",c._onDrop),v(n,"touchcancel",c._onDrop),e&&(e.effectAllowed="move",d.setData&&d.setData.call(c,e,g)),u(n,"drop",c),p(g,"transform","translateZ(0)"));Aa=!0;c._dragStartId=Fa(c._dragStarted.bind(c,b,a));u(n,"selectstart",c);fb&&p(n.body,"user-select","none")},_onDragOver:function(a){function b(O){return O&&
(t?m._hideClone():m._showClone(D),m&&(P(g,I?I.options.ghostClass:m.options.ghostClass,!1),P(g,l.ghostClass,!0)),I!==D&&D!==y.active?I=D:D===y.active&&(I=null),e&&D._animate(e,g),h&&E&&D._animate(E,h)),(h===g&&!g.animated||h===f&&!h.animated)&&(sa=null),l.dragoverBubble||a.rootEl||h===n||(D._handleAutoScroll(a),g.parentNode[G]._computeIsAligned(a)),!l.dragoverBubble&&a.stopPropagation&&a.stopPropagation(),!0}function c(){L(D,q,"change",h,f,q,M,ma(g,l.draggable),a)}var e,d,f=this.el,h=a.target,l=this.options,
k=l.group,m=y.active,t=Ga===k,w=l.sort,D=this;if(!Va&&(!U||a.rootEl||a.artificialBubble||Eb(f,h))){if(void 0!==a.preventDefault&&a.cancelable&&a.preventDefault(),Ha=!0,h=K(h,l.draggable,f,!0),K(a.target,null,g,!0)||h.animated)return b(!1);if(h!==g&&(Ja=!1),m&&!l.disabled&&(t?w||(d=!q.contains(g)):I===this||(this.lastPutMode=Ga.checkPull(this,m,g,a))&&k.checkPut(this,m,g,a))){k=this._getDirection(a,h);if(e=z(g),d)return this._hideClone(),C=q,na?q.insertBefore(g,na):q.appendChild(g),b(!0);if((d=Xa(f))&&
(W=a,F=k,X=z(Xa(f)),S="vertical"===F?W.clientY:W.clientX,ka="vertical"===F?W.clientX:W.clientY,oa="vertical"===F?X.bottom:X.right,kb="vertical"===F?X.left:X.top,Qa="vertical"===F?X.right:X.bottom,!("vertical"===F?Qa+10<ka||ka<=Qa&&oa<S&&kb<=ka:oa<S&&kb<ka||S<=oa&&Qa+10<ka)||d.animated)){if(h&&h!==g&&h.parentNode===f){var Y;S=0;ka=h.sortableMouseAligned;oa=g.parentNode!==f;W="vertical"===k?"top":"left";X=(F=yb(h,"top")||yb(g,"top"))?F.scrollTop:void 0;if(sa!==h&&(za=null,Y=z(h)[W],Ba=!1),V=h,J=k,Z=
(da=g)===g&&ta||z(da),aa=V===g&&ta||z(V),N="vertical"===J?Z.left:Z.top,R="vertical"===J?Z.right:Z.bottom,ha="vertical"===J?Z.width:Z.height,Ca="vertical"===J?aa.left:aa.top,Oa="vertical"===J?aa.right:aa.bottom,Pa="vertical"===J?aa.width:aa.height,za=(N===Ca||R===Oa||N+ha/2===Ca+Pa/2)&&ka||oa||F||l.invertSwap||"insert"===za||"swap"===za?("swap"!==za&&(Ka=l.invertSwap||oa),S=function(O,Ib,ua,lb,Ra,Jb,Ob){var ba=z(Ib);O="vertical"===ua?O.clientY:O.clientX;var la="vertical"===ua?ba.height:ba.width,Da=
"vertical"===ua?ba.top:ba.left;ba="vertical"===ua?ba.bottom:ba.right;var Sa=z(g),mb=!1;if(!Jb)if(Ob&&Ia<la*lb)if(!Ba&&(1===ya?Da+la*Ra/2<O:O<ba-la*Ra/2)&&(Ba=!0),Ba)mb=!0;else{if("vertical"===ua?Sa.top:Sa.left,"vertical"===ua?Sa.bottom:Sa.right,1===ya?O<Da+Ia:ba-Ia<O)return-1*ya}else if(Da+la*(1-lb)/2<O&&O<ba-la*(1-lb)/2)return ub(Ib);return(mb=mb||Jb)&&(O<Da+la*Ra/2||ba-la*Ra/2<O)?Da+la/2<O?1:-1:0}(a,h,k,l.swapThreshold,null==l.invertedSwapThreshold?l.swapThreshold:l.invertedSwapThreshold,Ka,sa===
h),"swap"):(S=ub(h),"insert"),0===S)return b(!1);ta=null;ya=S;var E=z(sa=h);da=h.nextElementSibling;V=!1;J=tb(q,f,g,e,h,E,a,V=1===S);if(!1!==J)return 1!==J&&-1!==J||(V=1===J),Va=!0,pa(Lb,30),t?m._hideClone():m._showClone(this),V&&!da?f.appendChild(g):h.parentNode.insertBefore(g,V?da:h),F&&Cb(F,0,X-F.scrollTop),C=g.parentNode,void 0===Y||Ka||(Ia=fa(Y-z(h)[W])),c(),b(!0)}}else if(d&&f===a.target&&(h=d),h&&(E=z(h)),t?m._hideClone():m._showClone(this),!1!==tb(q,f,g,e,h,E,a,!!h))return f.appendChild(g),
C=f,ta=null,c(),b(!0);if(f.contains(g))return b(!1)}var da,V,J,Z,aa,N,R,ha,Ca,Oa,Pa,W,F,X,S,ka,oa,kb,Qa;return U&&!a.rootEl&&Fb(f,a,"_onDragOver"),!1}},_animate:function(a,b){var c=this.options.animation;if(c){var e=z(b);if(b===g&&(ta=e),1===a.nodeType&&(a=z(a)),a.left+a.width/2!==e.left+e.width/2||a.top+a.height/2!==e.top+e.height/2){var d=Ea(this.el),f=d&&d.a;d=d&&d.d;p(b,"transition","none");p(b,"transform","translate3d("+(a.left-e.left)/(f||1)+"px,"+(a.top-e.top)/(d||1)+"px,0)");b.offsetWidth;
p(b,"transition","transform "+c+"ms"+(this.options.easing?" "+this.options.easing:""));p(b,"transform","translate3d(0,0,0)")}"number"==typeof b.animated&&clearTimeout(b.animated);b.animated=pa(function(){p(b,"transition","");p(b,"transform","");b.animated=!1},c)}},_offUpEvents:function(){var a=this.el.ownerDocument;v(n,"touchmove",this._onTouchMove);v(n,"pointermove",this._onTouchMove);v(a,"mouseup",this._onDrop);v(a,"touchend",this._onDrop);v(a,"pointerup",this._onDrop);v(a,"touchcancel",this._onDrop);
v(n,"selectstart",this)},_onDrop:function(a){var b=this.el,c=this.options;Ba=Ka=db=Aa=!1;clearInterval(this._loopId);clearInterval(ra);Na();clearTimeout(wa);wa=void 0;clearTimeout(this._dragStartTimer);clearTimeout(this._cloneId);clearTimeout(this._dragStartId);v(n,"mousemove",this._onTouchMove);this.nativeDraggable&&(v(n,"drop",this),v(b,"dragstart",this._onDragStart),v(n,"dragover",this._handleAutoScroll),v(n,"dragover",Db));fb&&p(n.body,"user-select","");this._offUpEvents();a&&(Ha&&(a.cancelable&&
a.preventDefault(),!c.dropBubble&&a.stopPropagation()),r&&r.parentNode&&r.parentNode.removeChild(r),(q===C||I&&"clone"!==I.lastPutMode)&&x&&x.parentNode&&x.parentNode.removeChild(x),g&&(this.nativeDraggable&&v(g,"dragend",this),Ua(g),g.style["will-change"]="",P(g,I?I.options.ghostClass:this.options.ghostClass,!1),P(g,this.options.chosenClass,!1),L(this,q,"unchoose",g,C,q,M,null,a),q!==C?(0<=(Q=ma(g,c.draggable))&&(L(null,C,"add",g,C,q,M,Q,a),L(this,q,"remove",g,C,q,M,Q,a),L(null,C,"sort",g,C,q,M,
Q,a),L(this,q,"sort",g,C,q,M,Q,a)),I&&I.save()):g.nextSibling!==na&&0<=(Q=ma(g,c.draggable))&&(L(this,q,"update",g,C,q,M,Q,a),L(this,q,"sort",g,C,q,M,Q,a)),y.active&&(null!=Q&&-1!==Q||(Q=M),L(this,q,"end",g,C,q,M,Q,a),this.save())));this._nulling()},_nulling:function(){q=g=C=r=na=x=Za=qa=$a=A.length=ra=bb=cb=xa=H=Ha=Q=M=sa=ya=ta=I=Ga=y.active=null;Ma.forEach(function(a){a.checked=!0});Ma.length=0},handleEvent:function(a){switch(a.type){case "drop":case "dragend":this._onDrop(a);break;case "dragenter":case "dragover":g&&
(this._onDragOver(a),a.dataTransfer&&(a.dataTransfer.dropEffect="move"),a.cancelable&&a.preventDefault());break;case "selectstart":a.preventDefault()}},toArray:function(){for(var a,b=[],c=this.el.children,e=0,d=c.length,f=this.options;e<d;e++)if(K(a=c[e],f.draggable,this.el,!1)){var h=b,l=h.push,k;if(!(k=a.getAttribute(f.dataIdAttr))){a=a.tagName+a.className+a.src+a.href+a.textContent;k=a.length;for(var m=0;k--;)m+=a.charCodeAt(k);k=m.toString(36)}l.call(h,k)}return b},sort:function(a){var b={},c=
this.el;this.toArray().forEach(function(e,d){d=c.children[d];K(d,this.options.draggable,c,!1)&&(b[e]=d)},this);a.forEach(function(e){b[e]&&(c.removeChild(b[e]),c.appendChild(b[e]))})},save:function(){var a=this.options.store;a&&a.set&&a.set(this)},closest:function(a,b){return K(a,b||this.options.draggable,this.el,!1)},option:function(a,b){var c=this.options;if(void 0===b)return c[a];c[a]=b;"group"===a&&ob(c)},destroy:function(){var a=this.el;a[G]=null;v(a,"mousedown",this._onTapStart);v(a,"touchstart",
this._onTapStart);v(a,"pointerdown",this._onTapStart);this.nativeDraggable&&(v(a,"dragover",this),v(a,"dragenter",this));Array.prototype.forEach.call(a.querySelectorAll("[draggable]"),function(b){b.removeAttribute("draggable")});this._onDrop();ia.splice(ia.indexOf(this.el),1);this.el=a=null},_hideClone:function(){x.cloneHidden||(p(x,"display","none"),x.cloneHidden=!0,x.parentNode&&this.options.removeCloneOnHide&&x.parentNode.removeChild(x))},_showClone:function(a){"clone"===a.lastPutMode?x.cloneHidden&&
(q.contains(g)&&!this.options.group.revertClone?q.insertBefore(x,g):na?q.insertBefore(x,na):q.appendChild(x),this.options.group.revertClone&&this._animate(g,x),p(x,"display",""),x.cloneHidden=!1):this._hideClone()}},u(n,"touchmove",function(a){(y.active||Aa)&&a.cancelable&&a.preventDefault()}),y.utils={on:u,off:v,css:p,find:sb,is:function(a,b){return!!K(a,b,a,!1)},extend:Ta,throttle:vb,closest:K,toggleClass:P,clone:wb,index:ma,nextTick:Fa,cancelNextTick:function(a){return clearTimeout(a)},detectDirection:nb,
getChild:Wa},y.create=function(a,b){return new y(a,b)},y.version="1.8.4",y});