// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/array jimu/LayerInfos/LayerInfos dojo/Deferred dojo/promise/all dojo/on exports dojo/store/Observable dojo/store/Cache dojo/store/Memory esri/lang ./table/FeatureLayerQueryStore jimu/ArcadeUtils esri/ArcadeExpression esri/arcadeProfiles/popupProfile jimu/utils esri/graphic dojo/i18n!./nls/strings".split(" "),function(k,q,M,G,J,Q,d,R,S,N,K,T,H,aa,ba,A,U,V){function W(a,b){if(!a||!a.length)return b||[];if(!b||!b.length)return a;for(var e=[],c=0,h=a.length;c<h;c++)for(var f=
a[c],l=0,r=b.length;l<r;l++){var m=b[l];if(m.name===f.name){m.alias!==f.alias&&(f.alias=m.alias);e.push(f);break}}return e}d.readLayerInfosObj=function(a){return M.getInstance(a,a.itemInfo)};d.readLayerInfosFromMap=function(a,b,e){var c=new G;M.getInstance(a,a.itemInfo).then(k.hitch(this,function(h){var f=[];b?h.traversalLayerInfosOfWebmap(function(m){f.push(m)}):h.traversal(function(m){f.push(m)});if(e){var l=[],r=h.getMapNotesLayerInfoArray();q.forEach(r,function(m){l.push(m.id);m.traversal(function(u){l.push(u.id)})});
f=q.filter(f,function(m){return-1===l.indexOf(m.id)})}h=h.getTableInfoArray();f=f.concat(h);c.resolve(f)}),k.hitch(this,function(h){console.error(h);c.reject(h)}));return c.promise};d.generateColumnsFromFields=function(a,b,e,c,h,f,l,r,m,u){function I(g){var p=g.name;if(D&&K.isDefined(D.fieldInfos))for(var y=0,B=D.fieldInfos.length;y<B;y++){var z=D.fieldInfos[y];if(z.fieldName===p&&z.format)return z.format}return(g=A.getDefaultPortalFieldInfo(g))&&g.format?g.format:null}var D=e.getPopupInfo()||e.getPopupInfoFromLayerObject&&
e.getPopupInfoFromLayerObject(),w={selectionHandle:{label:"",className:"selection-handle-column",hidden:!1,unhidable:!0,field:null,sortable:!1,_cache:{sortable:!1,statistics:!1},renderCell:function(g,p,y){y.setAttribute("role","button");y.setAttribute("title",V.selectionHandleLabel)}}};q.forEach(h,k.hitch(d,function(g,p,y){p="field"+p;var B=!!g.domain,z="esriFieldTypeDate"===g.type,E=f&&g.name===f,O="esriFieldTypeDouble"===g.type||"esriFieldTypeSingle"===g.type||"esriFieldTypeInteger"===g.type||"esriFieldTypeSmallInteger"===
g.type,X="esriFieldTypeString"===g.type,L=0===g.name.indexOf("expression/"),Y=g.alias||g.name;var P=1===y.length?!1:a&&a[p]?a[p].hidden:g?!g.show&&K.isDefined(g.show):!1;w[p]={label:Y,className:p,hidden:P,unhidable:1===y.length?!1:!g.show&&K.isDefined(g.show)&&g._pk,field:g.name,sortable:!1,_cache:{sortable:!!r,statistics:m&&!B&&O}};L?w[p].formatter=k.hitch(d,d.urlFormatter):X?w[p].formatter=k.hitch(d,d.urlFormatter):z?w[p].formatter=k.hitch(d,d.dateFormatter,I(g)):O&&(w[p].formatter=k.hitch(d,d.numberFormatter,
I(g)));B?w[p].get="range"===(g.domain&&g.domain.type)?k.hitch(d,function(v,t,x){return this.getRangeDomainValue(t.name,x)},u,g):k.hitch(d,function(v,t,x){return this.getCodeValue(v,t.name,x)},u,g):E?w[p].get=k.hitch(d,function(v,t,x){return this.getTypeName(x[v.name],t)},g,l):L?(y=A.getFeatureLayerDefinition(u),w[p]._cache.sortable=!1,B=H.isAsync(g.name,c),z=g.name.split("expression/")[1],E={},E[z]=c[z],B?w[p].renderCell=k.hitch(this,function(v,t,x){var n=document.createElement("span");n.innerText=
jimuNls.common.show;n.style="cursor: pointer; text-decoration: underline; color: #518dca;";var F=Q(n,"click",k.hitch(this,function(){this.arcade.getAttributes(x,v,u,b)[t.name].then(function(C){n.style="cursor: inherit; text-decoration: inherit; color: inherit;";n.innerText=C||""});k.hitch(this,function(C){def.reject(C);n.style="cursor: inherit; text-decoration: inherit; color: inherit;";n.innerText=""});F.remove()}));return n},E,g):w[p].get=k.hitch(d,function(v,t,x,n){return this.arcade.getAttributes(n,
v,x,b)[t.name]||""},E,g,y)):B||z||E||L||(w[p].get=k.hitch(d,function(v,t,x,n,F){var C=null;x&&n&&0<n.length&&(n=(n=q.filter(n,k.hitch(d,function(Z){return Z.id===F[x]})))&&n[0]||null)&&n.domains&&n.domains[t.name]&&n.domains[t.name].codedValues&&(C=this.getCodeValue(v,t.name,F));return(v=null!==C?C:F[t.name])||isFinite(v)?v:""},u,g,f,l))}));return w};d.getTypeName=function(a,b){return A.fieldFormatter.getTypeName(a,b)};d.getCodeValue=function(a,b,e){return(a=A.getDisplayValueForCodedValueOrSubtype(a,
b,e))&&a.isCodedValueOrSubtype?a.displayValue||e[b]||"":e[b]||""};d.getRangeDomainValue=function(a,b){return(a=b[a])?a:""};d.urlFormatter=function(a){return A.fieldFormatter.getFormattedUrl(a)};d.dateFormatter=function(a,b){return A.fieldFormatter.getFormattedDate(b,a)};d.numberFormatter=function(a,b){return A.fieldFormatter.getFormattedNumber(b,a)};d.readLayerObjectsFromMap=function(a,b,e){var c=new G,h=[];this.readLayerInfosFromMap(a,b,e).then(k.hitch(this,function(f){q.forEach(f,k.hitch(this,function(l){h.push(l.getLayerObject())}));
J(h).then(k.hitch(this,function(l){c.resolve(l)}),k.hitch(this,function(l){c.reject(l);console.error(l)}))}),k.hitch(this,function(f){c.reject(f)}));return c.promise};d.readSupportTableInfoFromLayerInfos=function(a){var b=new G,e=[];q.forEach(a,k.hitch(this,function(c){e.push(c.getSupportTableInfo())}));J(e).then(k.hitch(this,function(c){c=k.clone(c);q.forEach(c,function(h,f){h.id=a[f].id});b.resolve(c)}),function(c){b.reject(c)});return b.promise};d.readConfigLayerInfosFromMap=function(a,b,e){var c=
new G,h=[];this.readLayerInfosFromMap(a,b,e).then(k.hitch(this,function(f){var l=[];q.forEach(f,function(r){h.push(r.getSupportTableInfo())});J(h).then(k.hitch(this,function(r){q.forEach(r,k.hitch(this,function(m,u){m.isSupportedLayer&&(f[u].name=f[u].title,l.push(f[u]))}));c.resolve(l)}),k.hitch(this,function(r){c.reject(r)}))}),k.hitch(this,function(f){c.reject(f)}));return c.promise};d.getConfigInfosFromLayerInfos=function(a){return q.map(a,function(b){return d.getConfigInfoFromLayerInfo(b)})};
d.getConfigInfoFromLayerInfo=function(a){var b={};b.name=a.name||a.title;b.id=a.id;b.show=a.isShowInMap();b.layer={url:a.getUrl()};var e=a.getPopupInfo();e&&!e.description&&(b.layer.fields=q.map(e.fieldInfos,function(c){return{name:c.fieldName,alias:c.label,show:c.visible,format:c.format}}),a=k.getObject("layerObject.fields",!1,a),b.layer.fields=W(b.layer.fields,a),q.some(b.layer.fields,function(c){return c.show})||(b.layer.fields&&0<b.layer.fields.length?b.layer.fields[0].show=!0:console.warn("We do not get fields info.")));
return b};d.generateCacheStore=function(a,b,e,c,h){a=new T({layer:a,objectIds:a._objectIds||null,totalCount:b,batchCount:e,where:c||"1\x3d1",spatialFilter:h});b=new N;return new S(a,b,{})};d.generateMemoryStore=function(a,b){return new R(new N({data:a||[],idProperty:b}))};d.merge=function(a,b,e,c){for(var h=q.map(b,function(m){return m[e]}),f=0,l=a.length;f<l;f++){var r=h.indexOf(a[f][e]);-1<r&&c(a[f],b[r])}};d.syncOrderWith=function(a,b,e){function c(u,I){return q.map(u,function(D){return D[I]})}
if(!k.isArray(b)||!e)return a;for(var h=c(a,e),f=[],l=0,r=b.length;l<r;l++){var m=h.indexOf(b[l][e]);-1<m&&(f=f.concat(a.splice(m,1)),h=c(a,e))}return f.concat(a)};d.arcade={};d.arcade.getExpressionInfosFromLayer=function(a,b){a=H.readExprInfo.getArcadeProfilesByType(a,b,"infoTemplate");return 0<a.length&&a[0].expressionInfos?a[0].expressionInfos:[]};d.arcade.getExpressionInfosFromLayerInfo=function(a){return(a=a&&a.getPopupInfo())&&a.expressionInfos||[]};d.arcade.getAttributes=function(a,b,e,c){a=
new U(a.geometry,null,a);return H.customExpr.getAsynAttributesFromCustomArcadeExpr(b,a,e,c)};d.arcade.appendArcadeExpressionsToFields=function(a,b){if(a){b=d.arcade.getExpressionInfosFromLayerInfo(b);if(0<b.length){var e=RegExp("^expression/");q.forEach(b,function(c){q.some(a,function(h){if(e.test(h.name))return h=h.name.substr(11),c.name===h})||a.push({name:"expression/"+c.name,alias:c.title,show:!0})})}return a}};d.arcade.isArcadeExpressionField=function(a){return a&&"string"===typeof a.name&&0===
a.name.indexOf("expression/")};d.arcade.parseArcadeExpressions=function(a){return H.InfoTemplate._parseArcadeExpressions(a)};d.getSortbyFields=function(a,b){a=a&&a.get("sort")||[];b=b&&b.objectIdField;0<a.length?a=q.map(a,function(e){return e.attribute+" "+(e.descending?"DESC":"ASC")}):b&&a.push(b+" ASC");return a}});