// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/SmartEditor/setting/FieldValidation.html":'\x3cdiv\x3e\r\n    \x3cdiv class\x3d"settingsDesc" data-dojo-attach-point\x3d"validationDesc"\x3e${nls.actionPage.description}\x3c/div\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"validationTable"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/on dojo/dom-construct dojo/query dojo/json dojox/html/entities dojo/text!./FieldValidation.html dijit/_TemplatedMixin jimu/BaseWidgetSetting jimu/dijit/SimpleTable jimu/dijit/Popup jimu/LayerInfos/LayerInfos ./FilterPage".split(" "),function(m,d,f,g,h,n,k,p,q,r,t,u,l,v,w){return m([t,r],{baseClass:"jimu-widget-smartEditor-rule-table",templateString:q,_resourceInfo:null,_url:null,_fieldName:null,_fieldValidations:null,_layerId:null,_fieldsPopUp:null,
postCreate:function(){this.inherited(arguments);this._fieldsPopUp=null;this._initActionsTable();this._setActionsTable()},getSettings:function(){return this._fieldValidations},_getConfigActionOrder:function(){var b=[];return void 0!==this._fieldValidations&&null!==this._fieldValidations&&this._fieldValidations.hasOwnProperty(this._fieldName)&&(f.forEach(this._fieldValidations[this._fieldName],function(a){b.push(a.actionName)}),null!==b&&0!==b.length)?b:["Hide","Required","Disabled"]},_getConfigAction:function(b){var a=
null;void 0!==this._fieldValidations&&null!==this._fieldValidations&&this._fieldValidations.hasOwnProperty(this._fieldName)&&f.some(this._fieldValidations[this._fieldName],function(c){return c.actionName===b?(a=c,!0):!1});return a},_nlsActionToConfig:function(b){switch(b){case this.nls.actionPage.actions.hide:return"Hide";case this.nls.actionPage.actions.disabled:return"Disabled";case this.nls.actionPage.actions.required:return"Required";default:return b}},popupActionsPage:function(){this._fieldsPopUp&&
(this._fieldsPopUp.close(),this._fieldsPopUp=null);this._fieldsPopUp=new l({titleLabel:this.popupTitle,width:920,maxHeight:600,autoHeight:!0,content:this,buttons:[{label:this.nls.ok,onClick:d.hitch(this,function(){var b=this._validationTable.getRows();if(void 0===this._fieldValidations||null===this._fieldValidations)this._fieldValidations={};this._fieldValidations[this._fieldName]=[];f.forEach(b,function(a){var c=this._validationTable.getRowData(a);a={};a.actionName=this._nlsActionToConfig(c.label);
a.submitWhenHidden=c.submitWhenHidden;void 0!==c.expression&&null!==c.expression&&""!==c.expression&&""!==c.filter&&(c=k.parse(p.decode(c.filter)),a.expression=c.expr,a.filter=c);this._fieldValidations[this._fieldName].push(a)},this);this._fieldsPopUp.close()})},{label:this.nls.cancel,classNames:["jimu-btn jimu-btn-vacation"],onClick:d.hitch(this,function(){this._fieldsPopUp.close()})}],onClose:d.hitch(this,function(){})})},_initActionsTable:function(){this._validationTable=new u({fields:[{name:"label",
title:this.nls.actionPage.actionsSettingsTable.rule,type:"text",width:"15%","class":"rule"},{name:"expression",title:this.nls.actionPage.actionsSettingsTable.expression,type:"text",width:"55%","class":"expression"},{name:"groupName",title:this.nls.actionPage.actionsSettingsTable.groupName,type:"text",width:"20%","class":"expression"},{name:"submitWhenHidden",title:"submitWhenHidden",type:"checkbox",hidden:!0},{name:"filter",title:"filter",type:"text",hidden:!0},{name:"actions",title:this.nls.actionPage.actionsSettingsTable.actions,
type:"actions",actions:["up","down","edit"],width:"10%","class":"actions"}],selectable:!1,style:{height:"300px",maxHeight:"300px"}});this._validationTable.onBeforeRowEdit=d.hitch(this,function(b){var a=this._validationTable.getRowData(b);if(a.groupName){var c=h.create("div");h.create("div",{innerHTML:this.nls.actionPage.editOptionsPopup.expression,className:"settingsDesc"},c);h.create("div",{innerHTML:this.nls.actionPage.editOptionsPopup.editGroupHint,className:"editGroupHint"},c);var e=new l({titleLabel:this.nls.actionPage.editOptionsPopup.popupTitle,
width:500,maxHeight:445,autoHeight:!0,content:c,"class":this.baseClass,buttons:[{label:this.nls.actionPage.editOptionsPopup.editGroupButton,onClick:d.hitch(this,function(){this._editGroup(a.groupName);e.close()})},{label:this.nls.actionPage.editOptionsPopup.editIndependentlyButton,onClick:d.hitch(this,function(){this._validationTable._onActionsEdit(b);e.close()})}]})}else this._validationTable._onActionsEdit(b)});this.own(g(this._validationTable,"row-edit",d.hitch(this,function(b){var a=this._validationTable.getRowData(b);
a.groupName&&(a={groupName:a.groupName,layerId:this._layerId,fieldName:this._fieldName,action:this._nlsActionToConfig(a.label)},this.removeFromGroup(a),this._validationTable.editRow(b,{groupName:null}))})));this._validationTable.placeAt(this.validationTable);this._validationTable.startup();n("th.simple-table-field",this._validationTable.domNode).forEach(function(b){switch(void 0===b.innerText||""===b.innerText?"":b.innerText.replace(/(\r\n|\n|\r)/gm,"")){case this.nls.actionPage.actionsSettingsTable.rule:b.title=
this.nls.actionPage.actionsSettingsTable.ruleTip;break;case this.nls.actionPage.actionsSettingsTable.expression:b.title=this.nls.actionPage.actionsSettingsTable.expressionTip;break;case this.nls.actionPage.actionsSettingsTable.actions:b.title=this.nls.actionPage.actionsSettingsTable.actionsTip;break;case this.nls.actionPage.actionsSettingsTable.groupName:b.title=this.nls.actionPage.actionsSettingsTable.groupNameTip}},this);this.own(g(this._validationTable,"actions-edit",d.hitch(this,this._onEditFieldInfoClick)));
this.own(g(this._validationTable,"actions-delete",d.hitch(this,this._onDeleteFieldInfoClick)))},_onDeleteFieldInfoClick:function(b){this._removeFilter(b)},_onEditFieldInfoClick:function(b){this._showFilter(b)},_setActionsTable:function(){var b=this._getConfigActionOrder();f.forEach(b,function(a){var c=this._getConfigAction(a),e=a;switch(a){case "Hide":this.nls.actionPage.hasOwnProperty("actions")&&this.nls.actionPage.actions.hasOwnProperty("hide")&&(e=this.nls.actionPage.actions.hide);break;case "Required":this.nls.actionPage.hasOwnProperty("actions")&&
this.nls.actionPage.actions.hasOwnProperty("required")&&(e=this.nls.actionPage.actions.required);break;case "Disabled":this.nls.actionPage.hasOwnProperty("actions")&&this.nls.actionPage.actions.hasOwnProperty("disabled")&&(e=this.nls.actionPage.actions.disabled);break;default:e=a}a={label:e,expression:null};void 0!==c&&null!==c&&(c.hasOwnProperty("filter")&&void 0!==c.filter&&null!==c.filter&&(c.filter.smartActionGroupName&&(a.groupName=c.filter.smartActionGroupName),a.filter=k.stringify(c.filter),
a.expression=c.filter.expr),c.hasOwnProperty("expression")&&(a.expression=c.expression),c.hasOwnProperty("submitWhenHidden")&&(a.submitWhenHidden=c.submitWhenHidden));this._validationTable.addRow(a)},this)},_removeFilter:function(b){this._validationTable.editRow(b,{expression:"",filter:null,submitWhenHidden:!1})},_showFilter:function(b){this._filterPage&&this._filterPage.destroy();var a=v.getInstanceSync().getLayerOrTableInfoById(this._layerId);a&&a.layerObject&&(a=a.layerObject);this._filterPage=
new w({nls:this.nls,_resourceInfo:this._resourceInfo,_url:this._url,_layerId:this._layerId,_validationTable:this._validationTable,_layerDefinition:a});this._filterPage.popup(b)},_editGroup:function(b){if(this._smartActionsTable){var a=this._smartActionsTable.getRows();f.some(a,function(c){if(this._smartActionsTable.getRowData(c).name===b)return this._fieldsPopUp.close(),this.onGroupEditingStart(),this._smartActionsTable._onActionsEdit(c),!0},this)}},onGroupEditingStart:function(){},removeFromGroup:function(b){}})});