// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/SmartEditor/setting/FilterPage.html":'\x3cdiv\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"submitWhenHidden"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"filterControl"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/Evented dojo/_base/lang dojo/json dojo/text!./FilterPage.html dijit/_TemplatedMixin jimu/BaseWidgetSetting jimu/dijit/Popup jimu/dijit/Filter esri/lang dijit/form/CheckBox dojo/dom-construct jimu/dijit/Message".split(" "),function(l,m,g,f,n,p,q,r,t,u,v,h,w){return l([q,m,p],{baseClass:"jimu-widget-smartEditor-filter-page",templateString:n,_filter:null,_url:null,_layerId:null,_layerDefinition:null,_validationTable:null,postCreate:function(){this.inherited(arguments);
this._init()},_init:function(){this._origNLS=window.jimuNls.filterBuilder.matchMsg;window.jimuNls.filterBuilder.matchMsg=this.nls.filterPage.filterBuilder},destroy:function(){window.jimuNls.filterBuilder.matchMsg=this._origNLS;this._filter&&(this._filter.destroyRecursive(),this._filter=null,delete this._filter);this._submitHidden&&(this._submitHidden.destroyRecursive(),this._submitHidden=null,delete this._submitHidden)},popup:function(e){var a;e&&this._validationTable&&(a=this._validationTable.getRowData(e));
if(a&&a.label===this.nls.actionPage.actions.hide){this.submitWhenHidden.style.display="block";this._submitHidden=new v({id:"submitHidden",checked:void 0===a.submitWhenHidden?!1:a.submitWhenHidden,value:this.nls.filterPage.submitHidden},null);this.submitWhenHidden.appendChild(this._submitHidden.domNode);var x=g.replace("\x3clabel class\x3d'submithide' for\x3d'submitWhenHidden'\x3e{replace}\x3c/label\x3e\x3c/br\x3e\x3c/br\x3e",{replace:this.nls.filterPage.submitHidden});h.place(x,this._submitHidden.domNode,
"after")}else this.submitWhenHidden.style.display="none";this._filter=new t({style:"width:100%;margin-top:22px;",noFilterTip:this.nls.filterPage.noFilterTip});this._filter.placeAt(this.filterControl);h.create("div",{innerHTML:this.nls.valueProviderHint,class:"esriCTHint",style:"display: inline-block"},this._filter.desktopAddSection);var k=new r({titleLabel:u.substitute({action:a?a.label:this._groupName},this.nls.filterPage.title),width:850,height:485,content:this,rowData:a,buttons:[{label:this.nls.ok,
onClick:g.hitch(this,function(){var b=this._filter.toJson();if(!b)return new w({message:window.jimuNls.filterBuilder.setFilterTip}),!1;var d=!1;this._submitHidden&&this._submitHidden.checked&&(d=this._submitHidden.checked);b&&b.expr&&("1\x3d1"===b.expr?this._validationTable?this._validationTable.editRow(e,{expression:"",filter:null,submitWhenHidden:d}):(this._filterInfo={expression:"",filter:null,submitWhenHidden:d},this.emit("filterInfo",this._filterInfo)):this._validationTable?this._validationTable.editRow(e,
{expression:b.displaySQL,filter:f.stringify(b),submitWhenHidden:d}):(this._filterInfo={expression:b.displaySQL,filter:f.stringify(b),submitWhenHidden:d},this.emit("filterInfo",this._filterInfo)),k.close())})},{label:this.nls.cancel,classNames:["jimu-btn jimu-btn-vacation"],onClick:function(){k.close()}}]});if(a)var c=a;else this._filterInfo&&(c=this._filterInfo);c&&(void 0===c.filter||null===c.filter||""===c.filter?this._filter.build({url:this._url,partsObj:null,layerDefinition:this._layerDefinition,
featureLayerId:this._layerId}):c.filter.parts?this._filter.build({url:this._url,partsObj:c.filter,layerDefinition:this._layerDefinition,featureLayerId:this._layerId}):this._filter.build({url:this._url,partsObj:f.parse(c.filter),layerDefinition:this._layerDefinition,featureLayerId:this._layerId}))}})});