// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/nls/strings":{_widgetLabel:"An\u00e1lise de amea\u00e7as",threatAnalysisMainPageTitle:"Baseado no Guia de contraterrorismo JCAT",jcatURL:"https://www.dni.gov/nctc/jcat/references.html",inputLocation:"Introduzir localiza\u00e7\u00e3o",interactive:"Interativo",fromCoord:"Coordenadas fixas",existingFeature:"A partir de elementos existentes",threatAnalysisCoordInputLabel:"Localiza\u00e7\u00e3o de amea\u00e7as",enterCoords:"Introduzir Coordenadas",threatAddPointToolTip:"Adicionar localiza\u00e7\u00e3o da amea\u00e7a",
threatDrawPointToolTip:"Clicar para adicionar localiza\u00e7\u00e3o da amea\u00e7a",threatType:"Tipo de amea\u00e7a",threatPlaceholder:"Come\u00e7ar a digitar para pesquisar uma amea\u00e7a",zoneTypeLabel:"Tipo de zona",feetLabel:"P\u00e9s",metersLabel:"Metros",unitsLabel:"Unidades",threatGraphicLayer:"Gr\u00e1fico de Amea\u00e7as",style:"Estilo",settingsTitle:"Configura\u00e7\u00f5es",colorPicker:"colorPicker",lineStyles:{esriSLSDash:"Tra\u00e7o",esriSLSDashDot:"Tra\u00e7o e Ponto",esriSLSDashDotDot:"Tra\u00e7o, Ponto e Ponto",
esriSLSDot:"Ponto",esriSLSLongDash:"Tra\u00e7o Longo",esriSLSLongDashDot:"Tra\u00e7o Longo e Ponto",esriSLSNull:"Nulo",esriSLSShortDash:"Tra\u00e7o Curto",esriSLSShortDashDot:"Tra\u00e7o Curto e Ponto",esriSLSShortDashDotDot:"Tra\u00e7o Curto, Ponto e Ponto",esriSLSShortDot:"Tra\u00e7o Curto",esriSLSSolid:"S\u00f3lido"},fillStyles:{esriSFSBackwardDiagonal:"Ao Contr\u00e1rio",esriSFSCross:"Cruz",esriSFSDiagonalCross:"Diagonal",esriSFSForwardDiagonal:"Para a frente",esriSFSHorizontal:"Horizontal",esriSFSNull:"Nulo",
esriSFSSolid:"S\u00f3lido",esriSFSVertical:"Vertical"},resultsTitle:"Resultados",publishTABtn:"Publicar",layerName:"Nome da camada publicada",invalidLayerName:"O nome da camada pode apenas conter caracteres alfanum\u00e9ricos e tra\u00e7os inferiores.",missingLayerNameMessage:"Tem de introduzir um nome de camada v\u00e1lido antes de poder publicar",publishingFailedLayerExists:"Falha ao publicar: j\u00e1 possui um servi\u00e7o de elementos denominado {0}. Escolha outro nome para a camada.",checkService:"Verificar Servi\u00e7o: {0}",
createService:"Criar Servi\u00e7o: {0}",unableToCreate:"N\u00e3o \u00e9 poss\u00edvel criar: {0}",addToDefinition:"Adicionar a defini\u00e7\u00e3o: {0}",successfullyPublished:"Camada web publicada com sucesso",successfullyAppended:"Novos elementos anexados \u00e0 camada web com \u00eaxito",manageWebLayerText:"Gerir a camada web",userRole:"N\u00e3o \u00e9 poss\u00edvel criar o servi\u00e7o porque o utilizador n\u00e3o possui permiss\u00f5es",retrieveExistingLayerError:"N\u00e3o foi poss\u00edvel obter {0}. Publique utilizando outro nome para a camada",
publishToNewLayer:"Publicar resultados numa nova camada de elementos",layerNameExists:"O nome da camada j\u00e1 existe. Utilize um nome da camada diferente.",pipeBombLabel:"Bomba de Tubo",suicideBombLabel:"Bomba Suicida",briefcaseLabel:"Pasta",carLabel:"Carro",suvVanLabel:"SUV/CARRINHA",smallDeliveryTruckLabel:"Carrinha de Entregas Pequena",containerWaterTruckLabel:"Cami\u00e3o Cisterna/de \u00c1gua",semiTrailerLabel:"Semirreboque",transparencyLabel:"Transpar\u00eancia",outline:"Contorno",fill:"Preenchimento (Apenas \u00e9 aplicada cor quando o estilo \u00e9 definido como s\u00f3lido)",
createBtn:"Criar Zonas",clearBtn:"Apagar",invalidNumberMessage:"O valor introduzido n\u00e3o \u00e9 v\u00e1lido",invalidRangeMessage:"O valor tem de ser maior do que 0",parseCoordinatesError:"N\u00e3o foi poss\u00edvel analisar as coordenadas. Verifique a introdu\u00e7\u00e3o.",selectDrawModeLabel:"Selecionar Modo de Desenho",selectFeatureLabel:"Selecionar Elemento Desta Camada",smallLPGTank:"Tanque Pequeno GPL",largeLPGTank:"Tanque Grande GPL",commercialResidentialLPGTank:"Tanque GPL Comercial/Residencial",
smallLPGTruck:"Cami\u00e3o Pequeno GPL",semiTankerLPG:"Semirreboque GPL",zoneDescriptionColLabel:"Descri\u00e7\u00e3o de zona",distanceColLabel:"Dist\u00e2ncia",zoneDescColLabel:"Descri\u00e7\u00e3o de zona",descriptionLabel:"Descri\u00e7\u00e3o",editThreatZonePopupLabel:"Editar simbologia de zona de amea\u00e7a",symbologyColLabel:"Simbologia",actions:"A\u00e7\u00f5es",threatTypeSelectLabel:"Selecionar tipo de amea\u00e7a:",distanceLabel:"Dist\u00e2ncia (${unitAbbr})",layerCountHint:"Sugest\u00e3o: uma camada web com ${layerCount} elemento(s) de camada ser\u00e1 publicada.",
selectLabel:"Selecionar",mandatoryLabel:"Dist\u00e2ncia de evacua\u00e7\u00e3o obrigat\u00f3ria",safeLabel:"Dist\u00e2ncia de evacua\u00e7\u00e3o segura",fireBallDiameterLable:"Di\u00e2metro de Bola de Fogo",lpgSafeDistanceLable:"Dist\u00e2ncia Segura",_localized:{}}});