// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/array dojo/Deferred dojo/topic dojo/promise/all esri/geometry/Point esri/geometry/Extent esri/geometry/scaleUtils esri/SpatialReference esri/tasks/ProjectParameters esri/config esri/geometry/webMercatorUtils esri/symbols/jsonUtils esri/graphic esri/layers/GraphicsLayer esri/InfoTemplate esri/tasks/query ./utils ./LayerInfos/LayerInfos ./shareUtils".split(" "),function(I,x,y,J,z,q,A,K,m,L,M,B,C,D,N,O,P,n,E,r){function Q(a,d){var b=a.center.split(";");1===b.length&&
(b=a.center.split(","));if(2===b.length||3===b.length){a=parseFloat(b[0]);var c=parseFloat(b[1]);if(isNaN(a)||isNaN(c))a=parseFloat(b[0]),c=parseFloat(b[1]);if(!isNaN(a)&&!isNaN(c)){var e=4326;3!==b.length||isNaN(b[2])||(e=parseInt(b[2],10));b=new q(a,c,new m(e));t(b.spatialReference,d.spatialReference)?d.centerAt(b):u(b,d.spatialReference,function(g){d.centerAt(g[0])},function(){console.error("Project center point error.")})}}}function R(a,d){var b=a.extent.split("wkt\x3d"),c=null;2===b.length?(c=
b[1],b=b[0],b=b.split(",")):(b=a.extent.split(";"),1===b.length&&(b=a.extent.split(",")));if(4===b.length||5===b.length){a=parseFloat(b[0]);var e=parseFloat(b[1]),g=parseFloat(b[2]),f=parseFloat(b[3]);if(isNaN(a)||isNaN(a)||isNaN(a)||isNaN(a))a=parseFloat(b[0]),e=parseFloat(b[1]),g=parseFloat(b[2]),f=parseFloat(b[3]);if(isNaN(a)||isNaN(e)||isNaN(g)||isNaN(f))console.error("Wrong extent parameters.");else{var k=4326;5!==b.length||isNaN(b[4])||(k=parseInt(b[4],10));b=null;b=c?new A(a,e,g,f,new m({wkt:c})):
new A(a,e,g,f,new m({wkid:k}));t(d.spatialReference,b.spatialReference)?d.setExtent(b):u(b,d.spatialReference,function(h){d.setExtent(h[0])},function(){console.error("Project extent error.")})}}else console.error("Wrong extent parameters.")}function S(a,d){var b=null;if(a.markertemplate){b={title:"",content:"",isIncludeShareUrl:!1};try{var c=JSON.parse(decodeURIComponent(a.markertemplate));I.mixin(b,c)}catch(l){console.error("urlParams: \x26markertemplate JSON.parse error."+l.stack)}}c=a.marker.split(";");
1===c.length&&(c=a.marker.split(","));if(2<=c.length&&6>=c.length&&c[0].length&&!isNaN(c[0])&&c[1].length&&!isNaN(c[1])){var e=parseFloat(c[0]),g=parseFloat(c[1]),f=4326;3<=c.length&&c[2].length&&!isNaN(c[2])&&(f=parseInt(c[2],10));var k="";4<=c.length&&(k=c[3]);a=null;5<=c.length&&0===c[4].indexOf("http")&&(a=c[4]);var h=null;6===c.length&&(h=c[5]);var v=C.fromJson({type:"esriPMS",url:a,contentType:"image/png"}),w=null;h&&(w=C.fromJson({color:[0,0,0,255],type:"esriTS",verticalAlignment:"baseline",
horizontalAlignment:"left",angle:0,xoffset:0,yoffset:0,rotated:!1,kerning:!0,font:{size:12,style:"normal",weight:"bold",family:"Arial"},text:h}));T(v).then(function(){var l=new q(e,g,new m({wkid:f}));t(l.spatialReference,d.spatialReference)?F(l,v,w,k,b,d):u(l,d.spatialReference,function(U){F(U[0],v,w,k,b,d)},function(){console.error("Project center point error.")})})}}function F(a,d,b,c,e,g){c=new O("",c);if(e){var f=r.getXyContent(e);e.isIncludeShareUrl&&(e=r.getShareUrl(g,e,!0),e=r.getShareUrlContent(e),
f+=e);c.setContent(f)}f=new N({id:"marker-feature-action-layer"});g.addLayer(f);c=new D(a,d,null,c);f.add(c);b&&(b.xoffset=d.width/2,b.yoffset=d.height/2+d.yoffset,d=new D(new q(a.toJson()),b),f.add(d),c._textSymbol=d);g.centerAt(a)}function T(a){var d=new y;a.url?n.getImagesSize(a.url).then(function(b){a.width=b[0];a.height=b[1];d.resolve(a)},function(){a.url=require.toUrl("jimu")+"/images/EsriBluePinCircle26.png";a.width=26;a.height=26;a.setOffset(0,a.height/2);d.resolve(a)}):(a.url=require.toUrl("jimu")+
"/images/EsriBluePinCircle26.png",a.width=26,a.height=26,a.setOffset(0,a.height/2),d.resolve(a));return d}function V(a,d){var b=a.query.split(";");1===b.length&&(b=a.query.split(","));if(2!==b.length&&3!==b.length)console.error("query URL parameter is not correct.");else{var c=b[0];G("name",c,d).then(function(e){null===e?G("id",c,d).then(function(g){null===g?console.error("Invalid layer name or id."):H(d,g,b)}):H(d,e,b)})}}function H(a,d,b){var c=new P,e="";c.outSpatialReference=a.spatialReference;
if(2===b.length)c.where=b[1];else if(3===b.length&&(d.layerObject.url&&n.isHostedService(d.layerObject.url)&&n.containsNonLatinCharacter(b[2])&&(e="N"),x.forEach(d.layerObject.fields,function(g){if(g.alias.toLowerCase()===b[1].toLowerCase()||g.name.toLowerCase()===b[1].toLowerCase())-1<["esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble","esriFieldTypeOID"].indexOf(g.type)?c.where=g.name+"\x3d"+b[2]:-1<["esriFieldTypeString"].indexOf(g.type)&&(c.where=b[1]+
"\x3d"+e+"'"+b[2].replace(/'/g,"''")+"'")},this),!c.where)){console.error("Invalid field name or type in query URL parameter.");return}c.maxAllowableOffset=1E-5;d.layerObject.queryFeatures(c).then(function(g){g=g.features;if(0===g.length)console.log("No result from query URL parameter.");else{if("esriGeometryPoint"===d.layerObject.geometryType&&1===g.length)a.setExtent(K.getExtentForScale(a,1E3)),a.centerAt(g[0].geometry);else{var f=n.graphicsExtent(g);a.setExtent(f)}W(a,d,g)}},function(g){console.error(g)})}
function W(a,d,b){function c(f){x.forEach(b,function(k){k.setInfoTemplate(f)})}function e(){a.infoWindow.setFeatures(b);var f=a.infoWindow,k=f.show;var h=b[0].geometry;"point"!==h.type&&("multipoint"===h.type?h=h.getPoint(0):"polyline"===h.type?h=h.getExtent().getCenter():"polygon"===h.type?h=h.getExtent().getCenter():"extent"===h.type?h=h.getCenter():(console.error("Can not get layer geometry type, unknow error."),h=null));k.call(f,h)}if(a.getLayer(d.layerInfo.id))e();else{var g=d.layerInfo.getInfoTemplate();
g?(c(g),e()):d.layerInfo.loadInfoTemplate().then(function(f){c(f);e()})}}function G(a,d,b){var c=new y,e=[];E.getInstance(b,b.itemInfo).then(function(g){g.traversal(function(f){if(c.isResolved())return!0;("id"===a&&f.id.toLowerCase()===d.toLowerCase()||"name"===a&&f.title.toLowerCase()===d.toLowerCase())&&e.push(z({layerType:f.getLayerType(),layerObject:f.getLayerObject()}).then(function(k){"FeatureLayer"===k.layerType&&c.resolve({layerInfo:f,layerObject:k.layerObject})},function(k){console.error("Find layer error from query URL parameter",
k);c.resolve(null)}))});z(e).then(function(){c.isResolved()||c.resolve(null)})});return c}function u(a,d,b,c){var e=[102113,102100,3857];if(4326===a.spatialReference.wkid&&p(e,d.wkid)){a.ymin=Math.max(a.ymin,-89.99);a.ymax=Math.min(a.ymax,89.99);a=B.geographicToWebMercator(a);if((c=a.spatialReference._getInfo())&&a.xmin>a.xmax){e=c.valid[1]-a.xmin;var g=a.xmax-c.valid[0];e>g?a.xmax=c.valid[1]+g:a.xmin=c.valid[0]-e}a.spatialReference.wkid=d.wkid;b([a],null)}else p(e,a.spatialReference.wkid)&&4326===
d.wkid?(a=B.webMercatorToGeographic(a),(c=a.spatialReference._getInfo())&&a.xmin>a.xmax&&(e=c.valid[1]-a.xmin,g=a.xmax-c.valid[0],e>g?a.xmax=c.valid[1]+g:a.xmin=c.valid[0]-e),b([a],null)):(e=new L,e.geometries=[a],e.outSR=d,M.defaults.geometryService.project(e,function(f){!(f&&0<f.length&&f[0]&&"extent"===f[0].type)||isNaN(f[0].xmin)||isNaN(f[0].ymin)||isNaN(f[0].xmax)||isNaN(f[0].ymax)?f&&0<f.length&&f[0]&&"point"===f[0].type&&!isNaN(f[0].x)&&!isNaN(f[0].y)&&b(f,null):b(f,null)},c))}function t(a,
d){var b=[102113,102100,3857];return a&&d&&a.wkt===d.wkt&&(a.wkid===d.wkid||a.latestWkid&&a.latestWkid===d.wkid||d.latestWkid&&a.wkid===d.latestWkid||a.latestWkid&&a.latestWkid===d.latestWkid)||a&&d&&a.wkid&&d.wkid&&p(b,a.wkid)&&p(b,d.wkid)?!0:!1}function p(a,d){for(var b=a.length;b--;)if(a[b]===d)return!0;return!1}function X(a,d,b,c){var e=[];a&&a[d]&&a[d].split&&(e=a[d].split(";"));if(e&&0<=e.length){var g={};g[b]=e;E.getInstance(c,c.itemInfo).then(function(f){f.setSimplificationState(g)})}}return{postProcessUrlParams:function(a,
d){a:for(var b=["showLayers","hideLayers","showLayersEncoded","hideLayersEncoded"],c=0,e=b.length;c<e;c++){var g=b[c],f=g.toLowerCase(),k;for(k in a){var h=k.toLowerCase();if(f===h){X(a,k,g,d);break a}}}if("extent"in a)return R(a,d);if("center"in a)return Q(a,d);if("marker"in a)return S(a,d);if("find"in a)J.publish("publishData","framework","framework",{searchString:a.find},!0);else if("query"in a)return V(a,d)}}});