// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-construct dijit/_TemplatedMixin dijit/_WidgetBase jimu/utils".split(" "),function(n,h,g,f,p,q,l){return n([q,p],{name:"SEFilterEditor",baseClass:"jimu-widget-sefilterEditor",declaredClass:"jimu.dijit.SEFilterEditor",templateString:"\x3cdiv style\x3d'width:100%'\x3e\x3cdiv data-dojo-attach-point\x3d'filterEditorDiv'\x3e\x3c/div\x3e\x3c/div\x3e",_templatePicker:null,_layers:null,map:null,nls:null,_origGetItemsFromLayerFunc:null,gpFilterTemplates:!1,
postCreate:function(){this._createFilterTool()},_createFilterTool:function(){this._createLayerFilter();this._createTemplateFilter();this._loadTemplates()},_createLayerFilter:function(){this.selectDropDown=f.create("select",{"class":"flDropDown templatePicker",tabindex:"0","aria-label":this.nls.filterEditor.filterLayerLabel});f.place(this.selectDropDown,this.filterEditorDiv);this.selectDropDown.onchange=h.hitch(this,function(){var a=!0;""===this.filterTextBox.value||this.gpFilterTemplates||(a=!1);
this._onLayerFilterChanged(a)})},removeOptions:function(a){var b;for(b=a.options.length-1;0<=b;b--)a.remove(b)},_loadTemplates:function(){var a=this.selectDropDown.value===this.nls.filterEditor.all||""===this.selectDropDown.value?null:this.selectDropDown.value,b=l.sanitizeHTML(this.filterTextBox.value),c=!1;this.removeOptions(this.selectDropDown);var d=f.create("option",{value:this.nls.filterEditor.all,innerHTML:this.nls.filterEditor.all});f.place(d,this.selectDropDown);for(d=0;d<this._layers.length;d++){var e=
this._layers[d];!0===e.visible&&!0===e.visibleAtMapScale&&(null!==a&&e.id===a&&(c=!0),e=f.create("option",{value:e.id,innerHTML:e.name}),f.place(e,this.selectDropDown))}!0===c&&(this.selectDropDown.value=a,this._onLayerFilterChanged());null!==b&&""!==b&&(this.filterTextBox.value=b,this._onTemplateFilterChanged())},setTemplatePicker:function(a,b){this._layers=b;this._templatePicker=a;this._overrideTemplatePicker();this._loadTemplates()},_createTemplateFilter:function(){this.filterTextBox=f.create("input",
{"class":"searchtextbox templatePicker",type:"text",placeholder:this.nls.filterEditor.searchTemplates},this.filterEditorDiv);this.filterTextBox.onkeyup=h.hitch(this,function(){this._onTemplateFilterChanged()});this._overrideTemplatePicker()},_overrideTemplatePicker:function(){this._origGetItemsFromLayerFunc=this._templatePicker._getItemsFromLayer;this._templatePicker._getItemsFromLayer=h.hitch(this,function(){var a=this._origGetItemsFromLayerFunc.apply(this._templatePicker,arguments);var b=l.sanitizeHTML(this.filterTextBox.value);
b&&(a=g.filter(a,function(c){var d=!1,e=new RegExp(b,"ig");c.hasOwnProperty("label")&&c.label.match(e)&&0<c.label.match(e).length&&(d=!0);c.hasOwnProperty("template")&&c.template.hasOwnProperty("name")&&c.template.name.match(e)&&0<c.template.name.match(e).length&&(d=!0);return d},b));0===a.length&&(this._templatePicker.grid.noDataMessage=this.nls.filterEditor.noAvailableTempaltes,this._templatePicker.grid.params.noDataMessage=this.nls.filterEditor.noAvailableTempaltes,this._templatePicker.grid.messagesNode.innerText=
this.nls.filterEditor.noAvailableTempaltes);return a})},_onLayerFilterChanged:function(a){var b=!0;this._templatePicker.clearSelection();var c=this.selectDropDown.options[this.selectDropDown.selectedIndex].text;""!==c&&(c===this.nls.filterEditor.all?(c=this._filter_layers(l.sanitizeHTML(this.filterTextBox.value)),b=0!==c.length,this._templatePicker.attr("featureLayers",c),!0===this.gpFilterTemplates||a?this._templatePicker.attr("grouping",!0):this._templatePicker.attr("grouping",!1)):(a=this.map.getLayer(this.selectDropDown.value),
this._templatePicker.attr("featureLayers",[a]),this._templatePicker.attr("grouping",!1)),this._templatePicker.update(),b||(this._templatePicker.grid.messagesNode.innerText=this.nls.filterEditor.noAvailableTempaltes))},_filter_layers:function(a){return g.filter(this._layers,h.hitch(this,function(b){if(!1===b.visible||!1===b.visibleAtMapScale)return!1;if(""===a)return!0;var c=g.filter(b.templates,function(d){var e=!1,k=new RegExp(a,"ig");d.hasOwnProperty("name")&&d.name.match(k)&&0<d.name.match(k).length&&
(e=!0);return e},a);type_items=g.filter(b.types,function(d){return 0<g.filter(d.templates,function(e){var k=!1,m=new RegExp(a,"ig");e.hasOwnProperty("name")&&e.name.match(m)&&0<e.name.match(m).length&&(k=!0);return k},a).length},a);return 0<type_items.length||0<c.length}))},_onTemplateFilterChanged:function(){var a=this.selectDropDown.options[this.selectDropDown.selectedIndex].text,b=l.sanitizeHTML(this.filterTextBox.value),c=!0;a===this.nls.filterEditor.all&&(c=this._filter_layers(b),this._templatePicker.attr("featureLayers",
c),c=0!==c.length);a===this.nls.filterEditor.all?""===b?this._templatePicker.attr("grouping",!0):!0===this.gpFilterTemplates?this._templatePicker.attr("grouping",!0):this._templatePicker.attr("grouping",!1):this._templatePicker.attr("grouping",!1);this._templatePicker.update();c||(this._templatePicker.grid.messagesNode.innerText=this.nls.filterEditor.noAvailableTempaltes)},addNewLayerInEditor:function(a){var b=!1,c=!0;g.some(this.selectDropDown.options,h.hitch(this,function(e){if(e.value===a.id)return b=
!0}));if(!b){var d=f.create("option",{value:a.id,innerHTML:a.name});f.place(d,this.selectDropDown.options[0],"after")}this._layers.splice(0,0,a);""===this.filterTextBox.value||this.gpFilterTemplates||(c=!1);this._onLayerFilterChanged(c)},removeLayerFromEditor:function(a){var b=!0;g.some(this._layers,h.hitch(this,function(c,d){if(c.id===a.id)return this._layers.splice(d,1),!0}));g.some(this.selectDropDown.options,h.hitch(this,function(c,d){if(c.value===a.id)return this.selectDropDown.remove(d),""!==
this.filterTextBox.value&&(b=!1),this._onLayerFilterChanged(b),!0}))}})});