// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/array dojo/promise/all dojo/Deferred esri/layers/FeatureLayer esri/layers/GeoRSSLayer esri/layers/WFSLayer esri/request jimu/LayerInfos/LayerInfos jimu/shared/utils".split(" "),function(u,k,r,q,t,w,x,y,v,z){var g={},n,p={};g.getLayerObjects=function(a){var e=new q,b=[];v.getInstanceSync().traversal(function(c){b.push(c)});var f=k.map(b,function(c){var h;return c.getItemInfo().then(function(d){d&&(h=d.getItem())}).then(function(){return c.getLayerType()}).then(function(d){"GeoRSSLayer"===
d&&(c.isLeaf()||k.forEach(c.getSubLayers(),function(m){m.layerObject.name||(m.layerObject.name=m.title)}));return c.getLayerObjectTryUsingFeatureService()}).then(function(d){if(d)return d.itemInfo=h,d})});r(f).then(function(c){var h=[];k.forEach(c,function(d,m){if(d&&d.geometryType)if(d instanceof t&&"esri.layers.StreamLayer"!==d.declaredClass||d instanceof w)d.id=d.id||b[m].id,h.push(d);else if(d instanceof x){var l=g.createFeatureCollectionJsonFromWFS(d);l=new t(l,{mode:t.MODE_SNAPSHOT,outFields:["*"]});
l.id=d.id||b[m].id;l.title=d._layerName;l.name=d._layerName;l.capabilities?-1===l.capabilities.indexOf("Extract")&&(l.capabilities+=",Extract"):l.capabilities="Extract";h.push(l)}});g.checkLayers(h,a).then(function(){e.resolve(h)})},function(){e.resolve([])});return e};g.checkLayers=function(a,e){if(n)return n;var b=new q;if(e||0===a.length)return b.resolve(),b;n=b;var f=[];a.forEach(function(c){!c.url||z.isHostedService(c.url)||g.isPortalHostedService(c.url)||c.analysisProxyCheck||f.push(g._getProxyServiceInfo(c))});
0===f.length?(b.resolve(),n=null):r(f).always(function(){b.resolve();n=null});return b};g.isPortalHostedService=function(a){return a?-1!==a.toLowerCase().indexOf("/hosted/"):!1};g._getProxyServiceInfo=function(a){var e=new q,b,f=a.url+(-1<a.url.indexOf("?")?"\x26":"?")+"f\x3djson",c=a.url,h="function"===typeof a._getToken?a._getToken():null,d=c.substring(0,c.indexOf("/",9));k.some(Object.keys(p),function(m){b=c.substring(0,c.indexOf("/",9));if(m===b)return a.analysisProxyCheck=p[m],!0},this)?e.resolve():
(h&&(f+="\x26token\x3d"+h),y({url:f,content:null},{useProxy:!0}).then(function(){a.analysisProxyCheck="success";p[d]="success";e.resolve({})},function(){a.analysisProxyCheck="failure";p[d]||(p[d]="failure");e.resolve()}));return e};g.getTableInfos=function(){var a=v.getInstanceSync();a=[].concat(a.getTableInfoArray(),a.getLayerInfoArray());return k.filter(a,function(e){return!0===e.isTable})};g.getTableLayerObjects=function(){var a=new q,e=g.getTableInfos();e=k.map(e,function(b){return b.getLayerObject()});
r(e).then(function(b){b=k.filter(b,function(f){return null!==f});a.resolve(b)});return a};g.getMainGeometryType=function(a){var e=0,b=0,f=0;k.forEach(a.graphics,function(c){"point"===c.geometry.type?e++:"polyline"===c.geometry.type?b++:"polygon"===c.geometry.type&&f++});return e>b&&e>f?"esriGeometryPoint":b>e&&b>f?"esriGeometryPolyline":"esriGeometryPolygon"};g.createFeatureCollectionJsonFromWFS=function(a){var e=g.getMainGeometryType(a),b={layerDefinition:null,featureSet:{features:[],geometryType:e}};
b.layerDefinition={geometryType:e,objectIdField:"__OBJECTID",type:"Feature Layer",typeIdField:"",drawingInfo:{renderer:{type:"simple",symbol:("esriGeometryPoint"===e?a._pointSymbol:"esriGeometryPolyline"===e?a._lineSymbol:a._polygonSymbol).toJson()},fixedSymbols:!0},fields:[{name:"__OBJECTID",alias:"__OBJECTID",type:"esriFieldTypeOID"}],types:[],capabilities:"Query"};k.forEach(a.fields,function(c){-1<k.indexOf(["esriFieldTypeInteger","esriFieldTypeDouble","esriFieldTypeDate","esriFieldTypeString"],
c.type)&&b.layerDefinition.fields.push(u.clone(c))});var f=[];k.forEach(a.graphics,function(c,h){var d=u.clone(c.attributes);d.__OBJECTID=h;f.push({geometry:c.geometry.toJson(),attributes:d})});b.featureSet.features=f;return b};return g});